/** Espansione SANITÀ — 13 sotto-settori con stili esclusivi. */
import { X, type ExpansionRow } from "./mockup-identity-expansion-core";

export const HEALTHCARE_EXPANSION: ExpansionRow[] = [
  X("healthcare", "hc-dentista", "dentista-smalto-bianco-menta", "Dentista Smalto", "Studio Sorriso Chiaro", "Odontoiatria, igiene e implantologia.",
    "#F6FFFD,#FFFFFF,#0C1F1E,#6C8A88,#14B8A6,#0F172A", "Sans pulito 32px|Sans 15px|denti numerati secondo mappa dentale",
    "12px|1px menta|8pt · mappa dentale interattiva|balanced", "tab bar bianca con arcata attiva|dark|mappa dentale delle arcate",
    "riunito odontoiatrico, strumenti lucidi, luce clinica bianca",
    "arcata → trattamenti → preventivo → appuntamento igiene",
    "smalto ceramico e acciaio odontoiatrico|luce clinica bianca da lampada del riunito|bianco menta con strumenti allineati|device sul vassoio del riunito|mappa dentale delle arcate in filigrana",
    ["home:Il tuo sorriso", "catalog:Trattamenti odontoiatrici", "quote:Preventivo e piano cure", "booking:Igiene semestrale", "D:crm:Pazienti, cure e richiami"]),

  X("healthcare", "hc-fisioterapia", "fisio-arancio-muscolo-anatomia", "Fisioterapia Anatomia", "Movimento Ritrovato", "Fisioterapia, riabilitazione e rieducazione.",
    "#FFF8F3,#FFFFFF,#1C1410,#857267,#EA580C,#0E7490", "Sans tecnico-sportivo 34px|Sans 14px|gradi di mobilità in numeri",
    "10px|1px arancio|8pt · schede esercizio|dense", "tab bar chiara con figura anatomica|dark|figura anatomica con zona attiva evidenziata",
    "lettini, elastici e attrezzi riabilitativi, luce chiara da studio",
    "zona del dolore → percorso → esercizi a casa → sedute",
    "gomma elastica da riabilitazione e lettino in similpelle|luce chiara diffusa da studio fisioterapico|avorio caldo con elastici|device sul lettino con elastico accanto|figura anatomica con zona dolente illuminata",
    ["home:Dove hai dolore", "detail:Percorso riabilitativo", "schedule:Esercizi a casa", "wallet:Pacchetto sedute", "D:crm:Pazienti, sedute e progressi"]),

  X("healthcare", "hc-oculista", "oculista-blu-ottotipo", "Oculista Ottotipo", "Visione Nitida", "Visite oculistiche e ortottica.",
    "#F4F8FF,#FFFFFF,#0B1424,#6F809A,#1E40AF,#22D3EE", "Sans nitido 34px|Sans 14px|decimi di visione in scala",
    "6px|1px blu|8pt · tabella ottotipo|balanced", "tab bar chiara con scala di nitidezza|dark|tabella ottotipo che rimpicciolisce",
    "strumenti ottici, lenti di prova, luce fredda da sala visita",
    "test → esami → risultati in decimi → controllo annuale",
    "vetro ottico molato e metallo del forottero|luce fredda puntiforme da sala visita|blu notte con lenti sfocate|device accanto a valigetta di lenti di prova|tabella ottotipo che rimpicciolisce lungo i titoli",
    ["home:Controlla la vista", "catalog:Esami disponibili", "report:Risultati in decimi", "booking:Controllo annuale", "D:crm:Pazienti e referti"]),

  X("healthcare", "hc-dermatologia", "derma-pelle-beige-macro", "Dermatologia Macro", "Pelle Sana", "Dermatologia, nevi e mappatura cutanea.",
    "#FBF7F4,#FFFFFF,#1B1614,#877B75,#B45309,#0891B2", "Sans clinico-caldo 32px|Sans 14px|misure lesioni in millimetri",
    "14px|1px beige|8pt · mappa corporea a punti|balanced", "tab bar beige con mappa dei nevi|dark|mappa corporea con nei mappati",
    "dermatoscopio, pelle in macro, luce clinica calda",
    "mappatura → controllo nevi → referto → richiamo annuale",
    "pelle in macro e vetro del dermatoscopio|luce clinica calda con polarizzatore|beige con reticolo di mappatura|device accanto al dermatoscopio|mappa corporea con nei numerati in filigrana",
    ["home:Mappatura della pelle", "catalog:Visite e trattamenti", "report:Referto dermatologico", "booking:Richiamo annuale", "D:crm:Pazienti e mappature"]),

  X("healthcare", "hc-poliambulatorio", "poliambulatorio-multi-specialita-grid", "Poliambulatorio Griglia", "Centro Salute Insieme", "Poliambulatorio multi-specialistico.",
    "#F7F9FA,#FFFFFF,#12181B,#6F787C,#0284C7,#16A34A", "Sans istituzionale 30px|Sans 14px|specialità in griglia di icone",
    "8px|1px grigio-blu|8pt · griglia di specialità|dense", "tab bar chiara con specialità attiva|dark|griglia di icone specialistiche",
    "sala d'attesa ordinata, corridoi luminosi, luce neutra ospedaliera",
    "specialità → medico → agenda unica → convenzioni",
    "linoleum ospedaliero e alluminio da corridoio|luce neutra uniforme da corridoio sanitario|grigio-blu con corridoio in fuga|device sul bancone dell'accoglienza|griglia di icone specialistiche dietro l'header",
    ["home:Specialità disponibili", "team:Scegli il medico", "booking:Agenda unica", "docs:Convenzioni e ticket", "D:ops:Agende, sale e liste d'attesa"]),

  X("healthcare", "hc-psicologia", "psicologia-salvia-cerchio-ascolto", "Psicologia Ascolto", "Spazio d'Ascolto", "Psicoterapia individuale e di coppia.",
    "#F5F8F4,#FFFFFF,#1A1F1B,#78827A,#6D8B74,#B08968", "Serif gentile 34px|Sans 15px|durata seduta discreta",
    "26px|nessuno|8pt · colonna unica calmissima|airy", "tab bar salvia con cerchio d'ascolto|dark|cerchio d'ascolto concentrico",
    "poltrone affacciate, pianta, luce morbida da lampada di carta",
    "percorsi → primo colloquio → riservatezza → seduta online",
    "tessuto di poltrona in cotone e carta di lampada|luce morbida da lampada di carta|verde salvia con pianta sfocata|device su tavolino tra due poltrone|cerchi concentrici d'ascolto attorno ai titoli",
    ["home:Uno spazio per te", "catalog:Percorsi e approcci", "booking:Primo colloquio", "docs:Riservatezza e consenso", "D:crm:Pazienti, sedute e note"]),

  X("healthcare", "hc-nutrizione", "nutrizione-verde-piatto-macro", "Nutrizione Piatto", "Bilancia Giusta", "Nutrizionista, piani alimentari e composizione.",
    "#F6FDF7,#FFFFFF,#0F1F14,#6D8574,#22C55E,#F59E0B", "Sans chiaro 34px|Sans 14px|macronutrienti in anelli percentuali",
    "18px|1px verde|8pt · anelli di macro|balanced", "tab bar chiara con anello macro|dark|anelli di macronutrienti sovrapposti",
    "piatti bilanciati dall'alto, verdure fresche, luce naturale pulita",
    "obiettivo → piano settimanale → macro → controllo peso",
    "ceramica opaca e verdura fresca|luce naturale pulita da cucina luminosa|verde chiarissimo con verdure|device su tagliere di legno chiaro|anelli di macronutrienti sovrapposti dietro i dati",
    ["home:Il tuo obiettivo", "schedule:Piano settimanale", "report:Macro e composizione", "booking:Controllo mensile", "D:crm:Pazienti, piani e misure"]),

  X("healthcare", "hc-pediatria", "pediatria-giallo-cielo-nuvole", "Pediatria Nuvole", "Piccoli Passi", "Pediatria e pediatra di famiglia.",
    "#FFFDF6,#FFFFFF,#1B1A12,#7C7A66,#38BDF8,#FBBF24", "Sans tondo grande 36px|Sans 15px|percentili in curve colorate",
    "24px|nessuno|8pt · card a nuvola|airy", "tab bar chiara con nuvola attiva|dark|nuvole illustrate che contengono i dati",
    "ambulatorio pediatrico colorato, giochi, luce solare gentile",
    "crescita → vaccinazioni → sintomi → visita",
    "carta illustrata e feltro morbido da ambulatorio pediatrico|luce solare gentile da finestra con tende chiare|azzurro cielo con nuvole|device su tappeto gioco con cubi colorati|nuvole illustrate che contengono i dati",
    ["home:Il tuo bambino", "report:Curve di crescita", "docs:Calendario vaccinale", "booking:Visita pediatrica", "D:crm:Pazienti pediatrici e richiami"]),

  X("healthcare", "hc-laboratorio-analisi", "laboratorio-provette-viola-dati", "Laboratorio Provette", "Analisi Precisa", "Laboratorio analisi e prelievi.",
    "#FAF8FF,#FFFFFF,#150F22,#7A7290,#7C3AED,#06B6D4", "Sans dati 30px|Sans 14px|valori di riferimento in mono tabulare",
    "6px|1px viola tenue|8pt · tabella referti densa|dense", "tab bar chiara con codice prelievo|dark|file di provette etichettate",
    "provette etichettate in rack, strumenti automatici, luce da laboratorio",
    "esami → prelievo → referto digitale → storico valori",
    "vetro di provetta e etichetta a codice a barre|luce fredda da laboratorio automatizzato|bianco viola con rack di provette|device accanto a un rack di provette|file di provette etichettate lungo il bordo",
    ["home:Prenota il prelievo", "catalog:Pannelli di esami", "docs:Referto digitale", "report:Storico dei valori", "D:ops:Prelievi, macchine e referti"]),

  X("healthcare", "hc-radiologia", "radiologia-nero-lastra-lightbox", "Radiologia Lastra", "Immagine Chiara", "Radiologia, TAC e risonanza.",
    "#0A0C0F,#141821,#E8EDF5,#7C8698,#60A5FA,#F1F5F9", "Sans tecnico 32px|Sans 14px|dose e sezioni in mono",
    "4px|1px blu freddo|8pt · viewer a griglia|dense", "tab bar scura con selettore sezione|light|diafanoscopio retroilluminato",
    "lastre su diafanoscopio, sala macchine, luce fredda bassa",
    "esami → preparazione → immagini → referto refertato",
    "pellicola radiografica e vetro retroilluminato|luce fredda bassa di sala refertazione|nero con lastre retroilluminate|device davanti a diafanoscopio accesso|diafanoscopio retroilluminato dietro le immagini",
    ["home:Esami per immagini", "detail:Preparazione all'esame", "docs:Immagini e referto", "booking:Prenota la TAC", "D:ops:Macchine, slot e refertazione"]),

  X("healthcare", "hc-ostetricia", "ostetricia-rosa-tenue-battito", "Ostetricia Battito", "Nove Mesi", "Ostetricia, gravidanza e corsi preparto.",
    "#FFF7FA,#FFFFFF,#1F141A,#877480,#EC4899,#8B5CF6", "Serif dolce 36px|Sans 15px|settimane di gestazione in cerchi",
    "22px|1px rosa tenue|8pt · timeline delle settimane|airy", "tab bar rosa con settimana attiva|dark|linea di battito cardiaco fetale",
    "ecografie, mani sul pancione, luce calda e morbida",
    "settimane → controlli → corso preparto → contatto ostetrica",
    "cotone morbido e gel per ecografia|luce calda morbidissima da sala ecografia|rosa tenue con eco sfocata|device su cuscino di cotone con ecografia stampata|linea di battito fetale che unisce le settimane",
    ["home:La tua gravidanza", "schedule:Controlli per settimana", "detail:Corso preparto", "chat:Contatta l'ostetrica", "D:crm:Assistite, visite e scadenze"]),

  X("healthcare", "hc-osteopatia", "osteopatia-argilla-mani-vertebre", "Osteopatia Argilla", "Equilibrio Manuale", "Osteopatia e terapia manuale.",
    "#F7F3EE,#FFFFFF,#1E1A16,#847B70,#92400E,#0F766E", "Serif essenziale 34px|Sans 15px|zone trattate in etichette sobrie",
    "16px|1px argilla|8pt · colonna vertebrale come indice|balanced", "tab bar argilla con vertebra attiva|dark|colonna vertebrale come indice laterale",
    "mani sul dorso, lettino in pelle, luce calda e ferma",
    "valutazione → trattamento manuale → postura → seduta",
    "argilla cruda e pelle di lettino invecchiata|luce calda e ferma da abat-jour di studio|argilla con ombra di mani|device sul lettino in pelle scura|colonna vertebrale come indice laterale delle sezioni",
    ["home:Valutazione posturale", "detail:Trattamento manuale", "report:Postura e progressi", "booking:Seduta osteopatica", "D:crm:Pazienti e trattamenti"]),

  X("healthcare", "hc-farmacia", "farmacia-croce-verde-cassetti", "Farmacia Cassetti", "Farmacia del Corso", "Farmacia con prenotazioni e servizi.",
    "#F4FCF7,#FFFFFF,#0F1D14,#6F8577,#15803D,#DC2626", "Sans leggibile 32px|Sans 15px|dosaggi in etichette prescrittive",
    "8px|1px verde farmacia|8pt · cassettiera a griglia|dense", "tab bar chiara con croce verde|dark|cassettiera da farmacia a griglia",
    "cassettiere in legno, banco farmaceutico, luce chiara e ordinata",
    "prodotti → ricetta digitale → servizi in farmacia → ritiro",
    "legno di cassettiera e vetro di banco farmaceutico|luce chiara ordinata da banco farmacia|verde farmacia con cassetti in fila|device sul banco con cassettiera dietro|cassettiera a griglia che struttura le sezioni",
    ["home:Servizi della farmacia", "catalog:Prodotti e integratori", "docs:Ricetta digitale", "booking:Ritiro o servizio in sede", "D:admin:Ordini, scorte e servizi"]),
];
