/** Espansione IMMOBILIARE — 12 sotto-settori con stili esclusivi. */
import { X, type ExpansionRow } from "./mockup-identity-expansion-core";

export const REALESTATE_EXPANSION: ExpansionRow[] = [
  X("realestate", "re-agenzia-quartiere", "agenzia-quartiere-carta-verde", "Agenzia di Quartiere", "Chiavi di Quartiere", "Compravendita residenziale di zona.",
    "#F7F8F5,#FFFFFF,#161A16,#737A72,#166534,#B45309", "Sans affidabile 32px|Sans 15px|metri quadri in badge",
    "8px|1px verde tenue|8pt · lista annunci compatta|dense", "tab bar chiara con pin di zona|dark|pin di quartiere ritagliato",
    "palazzine di quartiere, interni luminosi, luce diurna naturale",
    "annunci → filtri zona → visita → valutazione casa",
    "carta di mappa catastale e vernice verde bottiglia|luce diurna naturale da appartamento vuoto|bianco carta con mappa di quartiere|device su tavolo d'agenzia con mazzo di chiavi|pin di quartiere ritagliato sopra le card",
    ["home:Annunci in zona", "catalog:Immobili disponibili", "booking:Prenota la visita", "quote:Valutazione gratuita", "D:crm:Portafoglio immobili e clienti"]),

  X("realestate", "re-ville-lusso", "ville-lusso-onice-champagne", "Ville di Lusso Onice", "Ville Onice", "Ville e proprietà esclusive.",
    "#0F0E0D,#191817,#F4F1EC,#8D8880,#C6A664,#7A8B8B", "Serif alto lusso 46px|Sans 14px|prezzi su richiesta in maiuscoletto",
    "0px|hairline champagne|8pt · doppia pagina cinematografica|airy", "tab bar onice con filetto champagne|light|sigillo di riservatezza",
    "ville al tramonto, piscine a sfioro, luce cinematografica calda",
    "presentazione → proprietà riservate → visita privata → dossier",
    "onice lucidato e champagne spazzolato|luce cinematografica calda al tramonto|nero onice con piscina a sfioro|device su lastra di onice retroilluminata|sigillo di riservatezza in rilievo sui titoli",
    ["home:Collezione di proprietà", "catalog:Ville riservate", "detail:Dossier immobile", "booking:Visita privata", "D:crm:Trattative riservate"]),

  X("realestate", "re-nuove-costruzioni", "nuove-costruzioni-render-ciano", "Nuove Costruzioni Render", "Cantiere Aurora", "Nuove costruzioni in vendita su carta.",
    "#F2F7FB,#FFFFFF,#0B1620,#6B7F90,#0EA5E9,#F97316", "Sans progettuale 34px|Sans 14px|stato lavori in percentuale",
    "6px|1px ciano|8pt · piante e sezioni|balanced", "tab bar chiara con avanzamento lavori|dark|barra di avanzamento cantiere",
    "render architettonici, gru, luce di rendering pulita",
    "render → piante → avanzamento cantiere → prenotazione unità",
    "carta da render lucida e acciaio da ponteggio|luce pulita da rendering architettonico|azzurro render con gru sfocata|device su tavolo da cantiere con elmetto|barra di avanzamento cantiere sotto l'header",
    ["home:Il nuovo complesso", "catalog:Unità e piante", "report:Avanzamento lavori", "booking:Prenota unità", "D:admin:Unità, acconti e SAL"]),

  X("realestate", "re-affitti-brevi", "affittibrevi-corallo-calendario", "Affitti Brevi Corallo", "Soggiorno Corallo", "Gestione affitti brevi e multi-canale.",
    "#FFF6F3,#FFFFFF,#22140F,#8A7269,#FB7185,#0D9488", "Sans dinamico 34px|Sans 14px|tasso di occupazione in percentuale",
    "18px|1px corallo|8pt · calendario a griglia|dense", "tab bar corallo con calendario attivo|dark|calendario a griglia con notti piene",
    "appartamenti pronti per l'ospite, luce da servizio fotografico immobiliare",
    "calendario → tariffe dinamiche → pulizie → resa annuale",
    "corallo opaco e lino da appartamento turistico|luce da shooting immobiliare senza ombre|rosa corallo con calendario stampato|device su letto rifatto con calendario accanto|griglia di calendario con notti piene evidenziate",
    ["home:Occupazione del mese", "schedule:Calendario prenotazioni", "wallet:Tariffe dinamiche", "report:Resa annuale", "D:ops:Multi-canale, pulizie e prezzi"]),

  X("realestate", "re-commerciale-uffici", "commerciale-uffici-navy-vetro", "Commerciale Uffici", "Ufficio Metropoli", "Uffici e spazi commerciali in locazione.",
    "#0F1420,#18202E,#EDF1F7,#8290A4,#1D4ED8,#94A3B8", "Sans corporate 32px|Sans 14px|rendimenti in percentuale mono",
    "4px|1px navy|8pt · tabella metrature e rendimenti|dense", "tab bar navy con filtro metratura|light|griglia di piani in sezione verticale",
    "uffici vuoti con vetrate, skyline diurno, luce neutra alta",
    "spazi → metrature → rendimento → trattativa",
    "vetro strutturale e moquette da ufficio|luce neutra alta da vetrata continua|navy con skyline diurno|device su scrivania vuota in ufficio vetrato|sezione verticale dei piani a lato",
    ["home:Spazi in locazione", "catalog:Metrature e piani", "report:Rendimento atteso", "docs:Trattativa e contratto", "D:crm:Locatari, canoni e scadenze"]),

  X("realestate", "re-terreni-agricoli", "terreni-agricoli-ocra-catasto", "Terreni Agricoli Catasto", "Terre di Mezzo", "Terreni agricoli e aziende agricole.",
    "#FAF6E9,#FFFFFF,#211E12,#807A64,#A16207,#4D7C0F", "Serif rurale 36px|Sans 15px|ettari in numerali grandi",
    "2px|1px ocra|8pt · mappa a particelle|balanced", "tab bar ocra con particella attiva|dark|particelle catastali tratteggiate",
    "campi arati dall'alto, confini visibili, luce di pieno giorno agricolo",
    "particelle → ettari e colture → accesso e acqua → proposta",
    "carta catastale ingiallita e terra arata|luce di pieno giorno su campo arato|ocra con particelle tratteggiate|device su terra arata con paletto di confine|particelle catastali tratteggiate dietro le sezioni",
    ["home:Terreni disponibili", "map:Particelle e confini", "detail:Colture, acqua e accessi", "quote:Proposta d'acquisto", "D:admin:Particelle, contratti e affitti"]),

  X("realestate", "re-aste-immobiliari", "aste-immobiliari-carta-timbro", "Aste Immobiliari Timbro", "Asta Trasparente", "Aste giudiziarie e immobili all'asta.",
    "#FBFAF7,#FFFFFF,#141312,#787672,#B91C1C,#1F2937", "Serif giudiziario 34px|Sans 14px|base d'asta in cifre grandi",
    "0px|1px nero|8pt · fascicolo con marginalia|dense", "tab bar chiara con numero di lotto|dark|timbro di deposito sui titoli",
    "fascicoli, planimetrie fotocopiate, luce da ufficio pubblico",
    "lotti → perizia → rilancio minimo → deposito cauzione",
    "carta da fascicolo e inchiostro da timbro|luce piatta da ufficio giudiziario|carta ingiallita con timbri|device su fascicolo aperto con timbro accanto|timbro di deposito impresso sopra i titoli",
    ["home:Lotti in asta", "catalog:Fascicoli e perizie", "detail:Rilancio minimo", "docs:Deposito cauzionale", "D:admin:Lotti, scadenze e offerte"]),

  X("realestate", "re-coworking", "coworking-giallo-postazione", "Coworking Postazione", "Scrivania Comune", "Coworking con postazioni e sale riunioni.",
    "#FFFDF4,#FFFFFF,#1A1808,#7C7862,#FACC15,#2563EB", "Sans amichevole 36px|Sans 14px|postazioni numerate in cerchi",
    "20px|1px giallo|8pt · planimetria a postazioni|balanced", "tab bar chiara con postazione attiva|dark|planimetria con postazioni libere",
    "scrivanie condivise, piante, luce naturale abbondante",
    "postazioni libere → abbonamento → sale riunioni → community",
    "laminato giallo e feltro fonoassorbente|luce naturale abbondante da lucernari|avorio con planimetria gialla|device su scrivania condivisa con pianta accanto|planimetria con postazioni libere illuminate",
    ["home:Postazioni libere", "map:Planimetria dello spazio", "wallet:Abbonamento mensile", "booking:Sala riunioni", "D:admin:Postazioni, membri e sale"]),

  X("realestate", "re-industriale-logistica", "industriale-logistica-acciaio-nero", "Industriale Logistica", "Capannone Nord", "Capannoni e immobili logistici.",
    "#111315,#1B1E21,#E9EDEF,#7F868C,#F59E0B,#3F6212", "Sans industriale 34px|Sans 14px|altezze e portate in mono",
    "2px|2px acciaio|8pt · schede tecniche|dense", "tab bar scura con portata al metro quadro|light|griglia di scaffalature in prospettiva",
    "capannoni vuoti, ribalte di carico, luce da lucernari industriali",
    "immobili → dati tecnici → accessi e ribalte → locazione",
    "acciaio zincato e resina da pavimento industriale|luce da lucernari industriali a shed|grigio acciaio con scaffalature|device su pavimento in resina con muletto sfocato|griglia di scaffalature in prospettiva dietro i dati",
    ["home:Immobili logistici", "catalog:Capannoni e superfici", "detail:Ribalte e portate", "docs:Contratto di locazione", "D:admin:Immobili, canoni e tecnici"]),

  X("realestate", "re-rustici-ristrutturare", "rustici-ristrutturare-calce-ruggine", "Rustici da Ristrutturare", "Casolare da Rinascere", "Rustici e case da ristrutturare.",
    "#F6F1E8,#FFFFFF,#231D16,#857A6B,#9A3412,#57534E", "Serif materico 38px|Sans 15px|costi di recupero stimati",
    "4px|1px ruggine|8pt · prima-dopo affiancati|balanced", "tab bar calce con slider prima-dopo|dark|slider prima-dopo sulle foto",
    "muri scrostati, travi antiche, luce polverosa che entra dalle fessure",
    "stato attuale → potenziale → stima recupero → sopralluogo",
    "calce scrostata e ferro ossidato|luce polverosa che entra dalle fessure del tetto|beige calce con polvere sospesa|device su muretto scrostato con cazzuola|slider prima-dopo che taglia le immagini",
    ["home:Rustici da recuperare", "gallery:Stato attuale e progetto", "quote:Stima di recupero", "booking:Sopralluogo tecnico", "D:crm:Immobili, progetti e preventivi"]),

  X("realestate", "re-property-management", "property-management-blu-report", "Property Management", "Rendita Serena", "Gestione patrimoni immobiliari per proprietari.",
    "#F5F7FA,#FFFFFF,#131722,#727A8C,#4338CA,#059669", "Sans gestionale 30px|Sans 14px|flussi di cassa in tabelle",
    "8px|1px indaco tenue|8pt · dashboard cliente|dense", "tab bar chiara con indicatore rendimento|dark|grafico di flusso di cassa continuo",
    "portafoglio immobili in schede, luce d'ufficio ordinata",
    "portafoglio → incassi → morosità → report al proprietario",
    "carta da report patinata e alluminio da cartella|luce ordinata da studio di gestione|bianco freddo con grafici stampati|device su cartella di report aperta|grafico di flusso di cassa continuo dietro i KPI",
    ["home:Il tuo portafoglio", "report:Incassi e rendimento", "docs:Morosità e solleciti", "profile:Report al proprietario", "D:crm:Immobili, canoni e insoluti"]),

  X("realestate", "re-mutui-consulenza", "mutui-consulenza-verde-abaco", "Mutui Consulenza", "Tasso Chiaro", "Consulenza mutui e finanziamenti casa.",
    "#F4FBF6,#FFFFFF,#0E1F16,#6E8A7B,#047857,#0369A1", "Sans finanziario 32px|Sans 14px|tassi con due decimali in mono",
    "10px|1px verde banca|8pt · simulatore a slider|balanced", "tab bar chiara con slider di importo|dark|abaco di rate a colonne",
    "documenti e calcolatrice su scrivania, luce neutra rassicurante",
    "simulazione → rata → documenti → appuntamento consulente",
    "carta contabile e metallo di calcolatrice|luce neutra rassicurante da scrivania|verde banca con colonne di rate|device accanto a calcolatrice e documenti|abaco di rate a colonne dietro il simulatore",
    ["home:Simula il mutuo", "quote:Rata e piano", "docs:Documenti richiesti", "booking:Appuntamento consulente", "D:crm:Pratiche, banche e delibere"]),
];
