/** Espansione BEAUTY & WELLNESS — 12 sotto-settori con stili esclusivi. */
import { X, type ExpansionRow } from "./mockup-identity-expansion-core";

export const BEAUTY_EXPANSION: ExpansionRow[] = [
  X("beauty", "beauty-barber-vintage", "barber-cuoio-latte", "Barber Cuoio & Latte", "Bottega del Rasoio", "Barberia classica, rasoio e panno caldo.",
    "#F4EFE6,#FFFFFF,#191410,#7E7263,#8B1E1E,#1B4D4A", "Serif inciso 38px|Sans 14px|orari in numerali incisi",
    "2px|2px solido|8pt · righe compatte|balanced", "tab bar con palo da barbiere verticale|dark|insegna smaltata bicolore",
    "rasoi e panni caldi su cuoio, vapore leggero, luce da specchio a lampadine",
    "insegna → servizi a listino → barbiere → slot",
    "cuoio conciato e smalto da insegna|luce da lampadine dello specchio|avorio con striscia rossa e blu|device su poltrona in cuoio con panno caldo|palo da barbiere che scorre sul bordo sinistro",
    ["home:Bottega e servizi", "catalog:Listino taglio e barba", "team:Scegli il barbiere", "booking:Slot in poltrona", "D:admin:Poltrone e incassi giornata"]),

  X("beauty", "beauty-salon-couture", "salon-avorio-couture", "Salone Avorio Couture", "Maison Riccio", "Colore, piega e cura del capello.",
    "#FBF7F2,#FFFFFF,#1E1A19,#8A8078,#B98A5E,#3E3A38", "Serif couture 44px|Sans 14px|nomi servizi in small caps",
    "0px|hairline oro|8pt · editoriale a 2 colonne|airy", "tab bar minimale con filetto oro|dark|numero di collezione stagionale",
    "capelli in luce da studio moda, riflessi setosi, sfondo avorio",
    "copertina → collezione servizi → colorista → appuntamento",
    "carta couture e riflesso setoso del capello|luce da set di moda con softbox laterale|avorio caldissimo|device su tessuto avorio drappeggiato|filetto oro sottile che corre da bordo a bordo",
    ["home:Collezione stagione", "catalog:Servizi e trattamenti", "team:Colorista dedicato", "booking:Appuntamento in salone", "D:crm:Clienti e schede colore"]),

  X("beauty", "beauty-nail-gel-pop", "nail-gel-pop-candy", "Nail Gel Pop", "Studio Smalto", "Gel, refill e nail art.",
    "#FFF4FA,#FFFFFF,#2A0F22,#8E6F82,#FF5FA2,#7C4DFF", "Sans arrotondato grasso 36px|Sans 14px|prezzi in bolle colorate",
    "26px|nessuno|8pt · griglia di bolle|balanced", "tab bar con bolle colorate|dark|goccia di smalto come indicatore attivo",
    "mani con nail art su fondo candy, luce piatta satura, dettagli macro",
    "hero mani → catalogo nail art → durata refill → prenotazione",
    "smalto gel lucidissimo e acrilico candy|luce piatta satura da macro beauty|rosa candy con bolle viola|device tra flaconi di smalto colorati|goccia di smalto che cola sotto l'header",
    ["home:Nail art del mese", "gallery:Catalogo unghie", "detail:Durata e refill", "booking:Prenota il refill", "D:admin:Cabine e materiali gel"]),

  X("beauty", "beauty-waxing-clinic", "waxing-clinica-verde-acqua", "Waxing Clinic", "Pelle Lieve", "Epilazione professionale e protocolli pelle.",
    "#F1FAF8,#FFFFFF,#0D2621,#6C8B85,#149B87,#C8E6DF", "Sans neutro 32px|Sans 15px|durata trattamento in badge",
    "12px|1px verde tenue|8pt · elenco protocolli|balanced", "tab bar clinica con icone lineari|dark|scheda protocollo numerata",
    "cabina pulita, teli bianchi, strumenti ordinati, luce neutra",
    "protocolli → zone corpo → preparazione → richiamo ciclo",
    "resina depilatoria e telo di cotone teso|luce neutra da cabina estetica|verde acqua chiarissimo con teli piegati|device su lettino con telo bianco teso|mappa delle zone corpo in filigrana",
    ["home:Protocolli pelle", "catalog:Zone e durate", "detail:Preparazione e post", "booking:Richiamo del ciclo", "D:admin:Cabine e ricambi cere"]),

  X("beauty", "beauty-massage-oil", "massage-olio-terracotta", "Massage Olio", "Mani Sapienti", "Massaggi decontratturanti e sportivi.",
    "#F6EDE4,#FFFFFF,#241A14,#8A7565,#B4623A,#5C7D63", "Serif morbido 36px|Sans 15px|durate in minuti evidenziate",
    "20px|1px terracotta|8pt · card impilate morbide|airy", "tab bar terracotta opaca|dark|goccia d'olio come bullet",
    "olio che scorre su pelle, pietre calde, luce ambrata bassa",
    "hero mani → tipi di massaggio → durata → operatore",
    "olio caldo e pietra levigata|luce ambrata bassa da lampada di sale|terracotta con pietre impilate|device tra pietre calde e ciotola d'olio|gocce d'olio che scorrono lungo il bordo destro",
    ["home:Massaggi disponibili", "catalog:Trattamenti e durate", "team:Operatore scelto", "booking:Slot in cabina", "D:admin:Agenda cabine e operatori"]),

  X("beauty", "beauty-hammam-spa", "hammam-vapore-ottone", "Hammam Vapore", "Bagno di Levante", "Hammam, scrub e rituali di vapore.",
    "#101A1D,#17242A,#EDE3D4,#8B9AA0,#C79A4B,#2E6E6B", "Serif orientale 38px|Sans 15px|nomi rituali in maiuscoletto",
    "14px|1px ottone|8pt · sezioni a fasce|balanced", "tab bar scura con arco a sesto acuto|light|arco moresco come cornice",
    "vapore denso, mosaico e ottone, luce che filtra dal lucernario",
    "arco → rituali → percorso vapore → prenotazione a coppie",
    "mosaico bagnato e ottone brunito|luce a lama dal lucernario tra il vapore|verde petrolio con vapore denso|device su mosaico bagnato, vapore in primo piano|arco moresco che incornicia le sezioni",
    ["home:Rituali del vapore", "catalog:Percorsi hammam", "detail:Rituale a coppie", "booking:Turno riservato", "D:admin:Turni sale e rituali"]),

  X("beauty", "beauty-medspa-clinical", "medspa-bianco-clinico-viola", "MedSpa Clinico", "Aesthetica Nova", "Medicina estetica non invasiva.",
    "#FFFFFF,#F6F4FF,#141326,#767390,#6C4DF6,#00C2FF", "Sans tecnico 34px|Sans 14px|dati trattamento in mono",
    "8px|1px viola tenue|8pt · griglia dati 12 col|dense", "tab bar bianca con indicatore viola|dark|codice protocollo medico",
    "macchinari estetici in luce clinica, pelle in macro, fondo bianco",
    "protocollo → macchinari → simulazione risultato → consulto",
    "vetro medicale e silicone bianco|luce clinica bianca senza ombre|bianco puro con alone viola|device su piano clinico con macchinario dietro|linee di misurazione viola sul volto",
    ["home:Protocolli medici", "catalog:Trattamenti e macchinari", "detail:Risultati attesi", "booking:Consulto medico", "D:crm:Cartelle e consensi"]),

  X("beauty", "beauty-tattoo-studio", "tattoo-inchiostro-nero-carta", "Tattoo Inchiostro", "Ago d'Oro", "Studio tatuaggi su appuntamento.",
    "#0E0E0E,#161616,#F2F2F2,#8A8A8A,#E0C060,#B03030", "Sans stencil 40px|Sans 14px|dimensioni in cm accanto ai disegni",
    "0px|2px bianco|8pt · griglia disegni serrata|dense", "tab bar nera con linea inchiostro|light|firma dell'artista tracciata",
    "disegni su carta da lucido, aghi e inchiostri, luce dura da lampada",
    "portfolio → stile → preventivo per area → caparra",
    "carta da lucido e inchiostro nero denso|luce dura da lampada da studio tattoo|nero con schizzi d'inchiostro|device su carta da lucido con stencil accanto|schizzi d'inchiostro che macchiano i bordi",
    ["home:Portfolio dello studio", "gallery:Stili e artisti", "quote:Preventivo per area", "booking:Caparra e seduta", "D:admin:Agenda artisti e cabine"]),

  X("beauty", "beauty-solar-tan", "solarium-bronzo-ambra", "Solarium Bronzo", "Sole Privato", "Abbronzatura guidata e lampade di ultima generazione.",
    "#1A1207,#241A0C,#FFF3DC,#A08A66,#FFB020,#C56A12", "Sans largo 34px|Sans 15px|minuti sessione in display grande",
    "16px|1px ambra|8pt · card sessione|balanced", "tab bar ambrata con timer|light|timer circolare della sessione",
    "lettini abbronzanti accesi, luce ambrata, riflessi sul plexiglass",
    "hero cabina → tipi di lampada → minuti → abbonamento",
    "plexiglass ambrato e alluminio del lettino|luce ambrata dalle lampade UV|ambra scura con tubi luminosi|device sul plexiglass del lettino acceso|timer circolare che pulsa dietro i titoli",
    ["home:Cabine disponibili", "catalog:Lampade e programmi", "wallet:Abbonamento minuti", "booking:Sessione riservata", "D:admin:Lampade, ore e ricambi"]),

  X("beauty", "beauty-makeup-artist", "makeup-set-cipria-metal", "Makeup Set", "Volto d'Autore", "Make-up sposa, eventi e shooting.",
    "#F7F2F4,#FFFFFF,#211A1E,#877A80,#C8788A,#8E8FA8", "Serif moda 42px|Sans 14px|crediti shooting in micro-caps",
    "4px|hairline argento|8pt · doppia pagina moda|airy", "tab bar chiara tipografica|dark|crediti fotografici in colonna",
    "volti in beauty light, pennelli e ciprie, fondo cipria",
    "copertina → look disponibili → prova sposa → data evento",
    "cipria compatta e metallo dei pennelli|beauty light frontale con doppio catchlight|cipria con pennelli allineati|device tra pennelli disposti a raggiera|crediti in colonna verticale a lato",
    ["home:Look d'autore", "gallery:Portfolio sposa e shooting", "detail:Prova look", "booking:Data evento", "D:crm:Clienti sposa e scadenze"]),

  X("beauty", "beauty-hair-extension", "extension-seta-perla", "Extension Seta", "Chioma Lunga", "Extension, infoltimento e cura.",
    "#FDF9F6,#FFFFFF,#241C1A,#8B7E78,#A9855F,#E7D3C4", "Serif sottile 40px|Sans 14px|lunghezze in cm con righello",
    "10px|hairline perla|8pt · schede lunghezza|airy", "tab bar perla con indicatore lunghezza|dark|righello centimetrato laterale",
    "ciocche setose in luce perlata, prima e dopo, fondo perla",
    "prima-dopo → metodi → lunghezza in cm → mantenimento",
    "seta di capello naturale e madreperla|luce perlata avvolgente senza ombre|perla caldo con ciocche sfocate|device tra ciocche setose disposte a ventaglio|righello centimetrato lungo il bordo dello schermo",
    ["home:Prima e dopo", "catalog:Metodi di applicazione", "detail:Lunghezza e volume", "booking:Manutenzione programmata", "D:admin:Stock ciocche e cabine"]),

  X("beauty", "beauty-wellness-sauna", "wellness-legno-sauna-notte", "Wellness Sauna", "Silenzio Caldo", "Sauna finlandese e area relax silenziosa.",
    "#141110,#1E1917,#F0E7DA,#94897C,#D08A3C,#4E6B5A", "Sans caldo 34px|Sans 15px|temperature in gradi grandi",
    "18px|1px legno|8pt · fasce orizzontali calme|airy", "tab bar legno con indicatore temperatura|light|termometro a colonna",
    "listelli di legno caldo, vapore secco, luce bassa dorata",
    "hero sauna → sessioni → temperatura → silenzio garantito",
    "legno di abete caldo e pietra vulcanica|luce dorata bassa da lampada in sauna|bruno legno con vapore secco|device su panca in legno con secchiello e mestolo|termometro a colonna che sale lungo il lato",
    ["home:Sauna e area relax", "schedule:Sessioni della giornata", "wallet:Abbonamento accessi", "booking:Turno in silenzio", "D:admin:Temperature, turni e presenze"]),
];
