/** Espansione NCC & MOBILITÀ — 12 sotto-settori con stili esclusivi. */
import { X, type ExpansionRow } from "./mockup-identity-expansion-core";

export const NCC_EXPANSION: ExpansionRow[] = [
  X("ncc", "ncc-transfer-aeroporto", "transfer-terminal-board", "Transfer Terminal", "Volo Sicuro Transfer", "Transfer aeroportuali con voli monitorati.",
    "#0B1220,#131C2C,#EAF1FA,#8496AC,#3B82F6,#22D3A6", "Sans tecnico 32px|Sans 14px|codici volo in mono tabulare",
    "8px|1px blu tenue|8pt · righe da tabellone|dense", "tab bar scura con riga di stato volo|light|tabellone a lettere ribaltabili",
    "terminal notturno visto dal vetro, scie di fari, riflessi blu",
    "stato volo → veicolo → punto di incontro → prezzo bloccato",
    "vetro del terminal e alluminio anodizzato|luce blu freddissima da area arrivi|blu notte con scie di fari|device su banco arrivi con tabellone dietro|righe di tabellone che ribaltano dietro l'header",
    ["home:Volo monitorato", "catalog:Classi veicolo", "map:Punto di incontro", "order:Prezzo bloccato", "D:ops:Voli, autisti e ritardi"]),

  X("ncc", "ncc-limousine-cerimonie", "limousine-satin-perla", "Limousine Satin", "Cerimonia Bianca", "Auto per matrimoni e cerimonie.",
    "#FCFAF6,#FFFFFF,#1D1A17,#8C837A,#B99B6B,#9FB4A6", "Serif nuziale 42px|Sans 14px|date in stile invito",
    "0px|hairline oro pallido|8pt · impaginato da invito|airy", "tab bar avorio con filetto sottile|dark|nastro di raso come divisorio",
    "auto bianca con nastri, riso in aria, luce di mezzogiorno morbida",
    "invito → allestimenti → percorso cerimonia → conferma",
    "raso nuziale e vernice bianca perlata|luce di mezzogiorno filtrata da velo|avorio con petali sospesi|device su cofano bianco con nastro di raso|nastro di raso che lega le sezioni",
    ["home:Cerimonie e allestimenti", "catalog:Auto per il rito", "map:Percorso della cerimonia", "booking:Data e orari", "D:crm:Cerimonie in agenda"]),

  X("ncc", "ncc-minivan-gruppi", "minivan-grafico-arancio-blocchi", "Minivan Blocchi", "Otto Posti", "Minivan per gruppi e famiglie.",
    "#FFFFFF,#F4F6F8,#101418,#6B7480,#FF6A13,#1D4ED8", "Sans grasso a blocchi 36px|Sans 15px|posti in griglia numerata",
    "12px|3px solido|8pt · blocchi affiancati|balanced", "tab bar bianca con blocco attivo pieno|dark|planimetria posti a blocchi",
    "minivan con portellone aperto, bagagli, luce piena diurna",
    "posti → bagagli → tappe → prezzo per gruppo",
    "PVC arancione e lamiera verniciata bianca|luce piena diurna senza filtri|bianco con blocchi arancio geometrici|device su portellone aperto del minivan|blocchi geometrici che numerano i posti",
    ["home:Gruppi fino a otto", "detail:Posti e bagagli", "map:Tappe del viaggio", "quote:Prezzo per gruppo", "D:admin:Flotta minivan e turni"]),

  X("ncc", "ncc-wine-tour", "winetour-vigna-porpora", "Wine Tour Vigna", "Strada del Vino", "Tour enogastronomici con autista.",
    "#1A1016,#241820,#F4E9E4,#A08A92,#7B2D4A,#C9A227", "Serif vinicolo 38px|Sans 15px|cantine in maiuscoletto",
    "6px|1px porpora|8pt · itinerario verticale|balanced", "tab bar porpora scura|light|mappa delle vigne incisa",
    "filari al tramonto, calici controluce, polvere dorata",
    "itinerario → cantine → degustazioni → conferma giornata",
    "vetro di calice e terra di vigna|luce di tramonto tra i filari|porpora con filari sfocati|device tra calici pieni su barile|mappa dei filari incisa dietro l'itinerario",
    ["home:Itinerari del vino", "catalog:Cantine convenzionate", "schedule:Giornata di degustazione", "booking:Prenota il tour", "D:crm:Tour, cantine e commissioni"]),

  X("ncc", "ncc-transfer-sci", "transfer-neve-ghiaccio", "Transfer Neve", "Passo Bianco", "Transfer per stazioni sciistiche.",
    "#F2F8FF,#FFFFFF,#0C1B26,#6E8496,#0E7490,#E2E8F0", "Sans alpino 34px|Sans 14px|quote altimetriche accanto ai luoghi",
    "14px|1px ghiaccio|8pt · profilo altimetrico|balanced", "tab bar chiara con profilo di quota|dark|profilo altimetrico del tragitto",
    "strada innevata, catene, luce bianca di alta quota",
    "quota → attrezzatura → catene e sicurezza → prezzo stagionale",
    "neve compatta e vetro ghiacciato|luce bianca abbagliante di alta quota|azzurro ghiaccio con cristalli|device su neve compatta con catene accanto|profilo altimetrico che attraversa lo schermo",
    ["home:Stazioni servite", "detail:Attrezzatura e bagagli", "map:Stato strada e catene", "booking:Transfer stagionale", "D:ops:Meteo, tratte e mezzi"]),

  X("ncc", "ncc-shuttle-aziendale", "shuttle-corporate-grigio-acciaio", "Shuttle Corporate", "Navetta Impresa", "Navette aziendali e trasferte ricorrenti.",
    "#F5F6F7,#FFFFFF,#15181B,#6E757C,#0F766E,#334155", "Sans corporate 30px|Sans 14px|centri di costo in mono",
    "6px|1px grigio|8pt · tabella turni|dense", "tab bar grigia con badge dipendente|dark|badge aziendale con QR",
    "navette in fila davanti a sede vetrata, luce neutra d'ufficio",
    "turni → dipendenti → centro di costo → report mensile",
    "acciaio spazzolato e badge in policarbonato|luce neutra da ufficio a soffitto|grigio acciaio con sede vetrata|device su reception aziendale con badge accanto|griglia di badge aziendali sullo sfondo",
    ["home:Navette attive", "schedule:Turni e corse", "wallet:Centro di costo", "report:Report mensile trasferte", "D:admin:Contratti aziendali e corse"]),

  X("ncc", "ncc-auto-storiche", "auto-storica-crema-cromo", "Auto Storica Cromo", "Garage Anni Venti", "Auto d'epoca per shooting e matrimoni.",
    "#F4EFE2,#FFFDF6,#211C14,#8A7E68,#8E5A2B,#3F5E4C", "Serif d'epoca 40px|Sans 14px|anni in numerali incisi",
    "2px|1px cromo|8pt · impaginato d'archivio|airy", "tab bar crema con cornice a cartiglio|dark|cartiglio d'archivio con anno",
    "cromature lucide, pelle d'epoca, luce da garage storico",
    "archivio → modelli per anno → shooting → noleggio giornata",
    "cromo lucidato e pelle d'epoca screpolata|luce da lucernario di garage storico|crema con cromature riflettenti|device su parafango cromato d'epoca|cartiglio d'archivio attorno ai titoli",
    ["home:Archivio del garage", "catalog:Modelli per decennio", "detail:Shooting e set", "booking:Noleggio giornata", "D:admin:Manutenzioni e noleggi"]),

  X("ncc", "ncc-security-executive", "security-nero-tattico-ambra", "Security Executive", "Scorta Discreta", "Autisti con formazione security per executive.",
    "#0A0A0B,#131315,#E9E9EC,#83858B,#F59E0B,#DC2626", "Sans condensato 32px|Sans 14px|codici missione in mono",
    "4px|1px ambra|8pt · schede missione|dense", "tab bar nera con indicatore livello rischio|light|livello di rischio a barre ambra",
    "auto blindata in garage sotterraneo, luce ambrata puntuale",
    "livello rischio → team → percorso alternativo → protocollo",
    "kevlar opaco e vetro blindato|luce ambrata puntuale da garage interrato|nero con alone ambra basso|device su cofano di auto blindata|barre di livello rischio sopra ogni sezione",
    ["home:Livello di protezione", "team:Team assegnato", "map:Percorsi alternativi", "docs:Protocollo operativo", "D:ops:Missioni e turni scorta"]),

  X("ncc", "ncc-night-transfer", "night-transfer-viola-club", "Night Transfer Club", "Notte Lunga", "Transfer notturni per locali ed eventi.",
    "#0C0716,#160D24,#F1E9FF,#9184AB,#A855F7,#F472B6", "Sans display 38px|Sans 14px|orari notturni in neon",
    "20px|1px viola glow|8pt · card notturne|balanced", "tab bar viola con glow morbido|light|insegna neon che ronza",
    "vie notturne bagnate, luci di locali, riflessi viola e rosa",
    "hero notte → locali convenzionati → rientro garantito → tariffa notturna",
    "asfalto bagnato notturno e neon viola|luce di insegne neon riflesse sull'asfalto|viola notte con pozzanghere luminose|device su asfalto bagnato con riflesso neon|insegna neon che pulsa dietro i titoli",
    ["home:Notte e locali", "catalog:Locali convenzionati", "tracking:Rientro garantito", "order:Tariffa notturna", "D:ops:Corse notturne live"]),

  X("ncc", "ncc-bus-turistico", "bus-turistico-giallo-mappa", "Bus Turistico Mappa", "Giro Città", "Bus turistici e city tour con guida.",
    "#FFFDF5,#FFFFFF,#1A1710,#7C7565,#EAB308,#0EA5E9", "Sans tondo 36px|Sans 15px|fermate numerate in cerchi",
    "16px|2px giallo|8pt · linea di fermate|balanced", "tab bar chiara con linea di percorso|dark|linea di metropolitana con fermate",
    "bus scoperto in piazza, monumenti sfocati, luce turistica calda",
    "linea → fermate → audioguida → biglietto giornaliero",
    "carta da mappa turistica piegata e vernice gialla|luce turistica calda di mezzogiorno in piazza|avorio con mappa stampata|device su mappa turistica aperta|linea di percorso con fermate numerate lungo il lato",
    ["home:Linee del city tour", "map:Fermate e monumenti", "detail:Audioguida e lingue", "order:Biglietto giornaliero", "D:admin:Linee, bus e affluenze"]),

  X("ncc", "ncc-lungo-raggio", "lungoraggio-blu-notte-strada", "Lungo Raggio", "Mille Chilometri", "Trasferimenti a lungo raggio con doppio autista.",
    "#0E1116,#171C23,#E7ECF2,#7E8896,#2563EB,#94A3B8", "Sans stretto 32px|Sans 14px|chilometri in display grande",
    "10px|1px blu acciaio|8pt · timeline di viaggio|balanced", "tab bar scura con contachilometri|light|contachilometri analogico",
    "autostrada notturna, linee di mezzeria, fari lunghi",
    "distanza → soste → doppio autista → preventivo al km",
    "asfalto autostradale e plastica di plancia|luce dei fari lunghi in autostrada notturna|blu acciaio con mezzeria in fuga|device sulla plancia con fari accesi davanti|mezzeria che scorre come indicatore di avanzamento",
    ["home:Tratte lungo raggio", "map:Soste programmate", "team:Doppio autista", "quote:Preventivo al chilometro", "D:ops:Tratte, riposi e costi"]),

  X("ncc", "ncc-city-elettrico", "city-elettrico-verde-menta-soft", "City Elettrico", "Corsa Zero", "Flotta 100% elettrica per la città.",
    "#F6FFFB,#FFFFFF,#0B1F19,#6C8A80,#10B981,#0891B2", "Sans leggero 34px|Sans 14px|CO₂ risparmiata in badge",
    "24px|nessuno|8pt · card morbide|airy", "tab bar bianca con indicatore batteria|dark|indicatore di carica a segmenti",
    "auto elettrica silenziosa in città verde, luce chiara pulita",
    "hero carica → veicoli → CO₂ risparmiata → abbonamento urbano",
    "policarbonato bianco opaco e foglia fresca|luce chiara diffusa urbana di mattina|menta chiarissimo con foglie|device su colonnina di ricarica bianca|segmenti di carica che si riempiono sotto l'header",
    ["home:Flotta a zero emissioni", "catalog:Veicoli disponibili", "report:CO₂ risparmiata", "wallet:Abbonamento urbano", "D:admin:Ricariche e utilizzo flotta"]),
];
