/** Espansione FITNESS & SPORT — 12 sotto-settori con stili esclusivi. */
import { X, type ExpansionRow } from "./mockup-identity-expansion-core";

export const FITNESS_EXPANSION: ExpansionRow[] = [
  X("fitness", "fitness-crossfit-box", "crossfit-box-cemento-lime", "CrossFit Box", "Box Ventuno", "Box functional con WOD giornaliero.",
    "#161819,#1F2224,#F1F4F5,#8A9296,#C7F53F,#F97316", "Sans stencil grasso 40px|Sans 14px|tempi WOD in cronometro mono",
    "2px|2px lime|8pt · griglia WOD serrata|dense", "tab bar scura con cronometro attivo|light|cronometro a scatti sopra il titolo",
    "atleti su rig, magnesite in aria, luce industriale dura",
    "WOD di oggi → classi → punteggio personale → abbonamento",
    "cemento grezzo e gomma da pavimento palestra|luce industriale dura al neon da capannone|grigio cemento con magnesite sospesa|device su piastra di ghisa con magnesite|cronometro a scatti che segna le sezioni",
    ["home:WOD di oggi", "schedule:Classi della settimana", "report:Punteggio personale", "wallet:Abbonamento box", "D:admin:Classi, coach e presenze"]),

  X("fitness", "fitness-sala-pesi", "salapesi-nero-ferro-rosso", "Sala Pesi Ferro", "Ferro Vivo", "Sala pesi, schede e powerlifting.",
    "#0D0D0E,#151517,#EDEDEE,#84868C,#EF4444,#A3A3A3", "Sans compresso 42px|Sans 14px|carichi in kg giganti",
    "4px|1px ferro|8pt · tabella serie e ripetizioni|dense", "tab bar nera con barra di carico|light|dischi da bilanciere come indicatore",
    "bilancieri caricati, mani gessate, luce dura laterale",
    "scheda → esercizi → carichi progressivi → massimali",
    "ferro grezzo verniciato e gesso da presa|luce dura laterale da faretto singolo|nero con dischi impilati|device tra dischi olimpici allineati|dischi da bilanciere che indicano il progresso",
    ["home:Scheda del giorno", "catalog:Esercizi e gruppi", "report:Progressione carichi", "profile:Massimali personali", "D:admin:Schede, sale e rinnovi"]),

  X("fitness", "fitness-yoga-studio", "yoga-lino-sabbia-respiro", "Yoga Lino", "Respiro Lento", "Yoga, meditazione e respirazione.",
    "#F7F3EC,#FFFFFF,#221F1A,#8A8378,#A98C63,#7A8F7B", "Serif calmo 38px|Sans 15px|durate in minuti discrete",
    "28px|nessuno|8pt · colonna singola ariosa|airy", "tab bar lino con cerchio del respiro|dark|cerchio del respiro che si dilata",
    "tappetini su parquet, luce d'alba dalla finestra, tessuti di lino",
    "respiro → lezioni → livello → pacchetto lezioni",
    "lino grezzo e parquet oliato chiaro|luce d'alba morbida da finestra bassa|sabbia con tende di lino|device su tappetino di sughero, incenso accanto|cerchio del respiro che si dilata dietro i titoli",
    ["home:Pratica di oggi", "schedule:Lezioni in studio", "detail:Livello e focus", "wallet:Pacchetto lezioni", "D:admin:Sale, insegnanti e pacchetti"]),

  X("fitness", "fitness-padel-club", "padel-vetro-blu-cobalto", "Padel Vetro", "Campo Cobalto", "Prenotazione campi da padel e tornei.",
    "#0A1730,#10203F,#EAF2FF,#8298BC,#2DD4BF,#FACC15", "Sans sportivo 36px|Sans 14px|punteggi in tabellone digitale",
    "12px|1px cobalto|8pt · griglia campi|balanced", "tab bar blu con indicatore campo libero|light|tabellone punteggi a segmenti",
    "campo in vetro dall'alto, pallina in volo, luci artificiali",
    "campi liberi → orario → compagni → torneo",
    "vetro temperato da campo e erba sintetica blu|luce da fari a LED su campo coperto|blu cobalto con vetro riflettente|device appoggiato alla parete di vetro del campo|tabellone a segmenti che mostra il punteggio",
    ["home:Campi liberi ora", "schedule:Orari e prenotazioni", "team:Trova compagni", "detail:Tornei del club", "D:admin:Campi, tornei e incassi"]),

  X("fitness", "fitness-boxe-ring", "boxe-canvas-sangue-corda", "Boxe Canvas", "Ring Dodici", "Palestra di boxe e preparazione atletica.",
    "#12100F,#1B1817,#F3EDE6,#8E857C,#B91C1C,#D4A24C", "Sans pugilato 44px|Sans 14px|round numerati in cifre romane",
    "0px|3px corda|8pt · fasce da round|dense", "tab bar scura con campana di round|light|corda del ring come cornice",
    "guantoni consumati, sudore, luce dall'alto sul ring",
    "round → tecniche → sparring → tessera annuale",
    "tela del ring e cuoio dei guantoni|luce a campana dall'alto sul quadrato|marrone tela con corde tese|device sulla tela del ring tra i guantoni|corde del ring che delimitano le sezioni",
    ["home:Allenamento del giorno", "schedule:Corsi e sparring", "detail:Tecniche e round", "wallet:Tessera annuale", "D:admin:Atleti, corsi e certificati"]),

  X("fitness", "fitness-arti-marziali", "artimarziali-indaco-dojo-carta", "Dojo Indaco", "Via del Bambù", "Karate, judo e arti marziali per tutte le età.",
    "#101529,#182038,#EEF1FA,#8B93AC,#4F46E5,#F5F5F4", "Serif orientale 38px|Sans 15px|gradi di cintura a barre colorate",
    "8px|1px indaco|8pt · pannelli shoji|balanced", "tab bar indaco con grado di cintura|light|pannelli shoji come divisori",
    "tatami, kimono bianco, luce che filtra da carta di riso",
    "gradi → corsi per età → esami cintura → iscrizione",
    "carta di riso e tatami intrecciato|luce filtrata da pannelli di carta di riso|indaco con pannelli shoji|device su tatami con cintura piegata accanto|pannelli shoji che scorrono tra le sezioni",
    ["home:Dojo e discipline", "schedule:Corsi per fascia d'età", "profile:Grado e progressi", "booking:Iscrizione al corso", "D:admin:Allievi, esami e cinture"]),

  X("fitness", "fitness-piscina-nuoto", "piscina-corsia-azzurro-clorata", "Piscina Corsia", "Vasca Blu", "Corsi di nuoto e nuoto libero.",
    "#EAF7FF,#FFFFFF,#062033,#6A8CA6,#0284C7,#22D3EE", "Sans acquatico 34px|Sans 14px|tempi vasca in cronometro",
    "18px|1px azzurro|8pt · corsie orizzontali|balanced", "tab bar bianca con corsia attiva|dark|galleggianti di corsia come separatori",
    "acqua clorata mossa, corsie, luce riflessa sul soffitto",
    "corsie libere → corsi → tempi personali → abbonamento vasca",
    "acqua clorata mossa e piastrella smaltata|luce riflessa dall'acqua sul soffitto|azzurro con riflessi ondulati|device sul bordo vasca bagnato|galleggianti di corsia che separano le sezioni",
    ["home:Vasca e corsie libere", "schedule:Corsi di nuoto", "report:Tempi e distanze", "wallet:Abbonamento vasca", "D:admin:Corsie, istruttori e presenze"]),

  X("fitness", "fitness-spinning-indoor", "spinning-dark-neon-cadenza", "Spinning Cadenza", "Ruota Notte", "Indoor cycling con classifiche live.",
    "#0B0A12,#14121E,#F0EDFB,#8C87A5,#FB7185,#38BDF8", "Sans dinamico 38px|Sans 14px|watt e cadenza in display LED",
    "14px|1px rosa glow|8pt · barre di potenza|dense", "tab bar scura con barra watt|light|barre di potenza che salgono a ritmo",
    "sala buia con bike, luci rosa e blu, sudore illuminato",
    "classe → posto in sala → watt e cadenza → classifica",
    "alluminio della bike e sudore illuminato|luce rosa e blu da faretti a ritmo di musica|nero con fasci rosa pulsanti|device sul manubrio della bike|barre di potenza che pulsano a tempo",
    ["home:Classe di oggi", "schedule:Posti in sala", "report:Watt, cadenza e calorie", "loyalty:Classifica del mese", "D:ops:Sale, bike e classifiche live"]),

  X("fitness", "fitness-personal-studio", "personal-studio-grafite-oro", "Personal Studio", "Uno a Uno", "Studio privato di personal training.",
    "#1A1A1C,#232326,#F4F4F5,#8B8B90,#D4AF37,#5EEAD4", "Serif discreto 36px|Sans 14px|obiettivi in schede numerate",
    "10px|hairline oro|8pt · schede cliente|balanced", "tab bar grafite con filetto oro|light|scheda cliente con numero progressivo",
    "studio privato con attrezzi essenziali, luce calda controllata",
    "obiettivo → protocollo → misurazioni → pacchetto sedute",
    "grafite opaca e ottone dell'attrezzatura|luce calda controllata da faretti orientabili|grafite con riflesso oro|device su panca in pelle grafite|scheda numerata sovrapposta all'header",
    ["home:Il tuo obiettivo", "detail:Protocollo su misura", "report:Misurazioni e composizione", "wallet:Pacchetto sedute", "D:crm:Clienti, protocolli e rinnovi"]),

  X("fitness", "fitness-running-club", "running-club-asfalto-fluo", "Running Club", "Passo Costante", "Club di corsa con uscite di gruppo.",
    "#F5F7F6,#FFFFFF,#111614,#6E7A76,#84CC16,#0F766E", "Sans atletico 36px|Sans 14px|passo al km in mono grande",
    "16px|1px verde fluo|8pt · tracciato verticale|balanced", "tab bar chiara con tracciato GPS|dark|tracciato GPS disegnato a mano libera",
    "gambe in corsa su asfalto all'alba, ombre lunghe, pettorali",
    "uscite → percorsi → passo medio → gara di club",
    "asfalto ruvido e mesh fluo da scarpa|luce d'alba radente sull'asfalto|grigio asfalto con tracciato fluo|device su asfalto con scarpe accanto|tracciato GPS che serpeggia tra le sezioni",
    ["home:Prossima uscita", "map:Percorsi del club", "report:Passo medio e distanze", "schedule:Gare di club", "D:admin:Uscite, iscritti e percorsi"]),

  X("fitness", "fitness-calcetto-arena", "calcetto-arena-verde-notte", "Calcetto Arena", "Cinque Contro Cinque", "Campi da calcetto e tornei serali.",
    "#0A1A12,#10251A,#ECF7F0,#7FA491,#22C55E,#FDE047", "Sans da stadio 40px|Sans 14px|risultati su tabellone luminoso",
    "8px|2px linea campo|8pt · schema di campo|balanced", "tab bar verde scura con pallone attivo|light|linee del campo tracciate a gesso",
    "erba sintetica notturna sotto i fari, pallone fermo, ombre nette",
    "campi → squadre → tabellone → torneo serale",
    "erba sintetica notturna e gesso di tracciatura|luce dei fari da campo notturno con aloni|verde notte con linee bianche|device sull'erba sintetica accanto al pallone|linee del campo tracciate attorno alle card",
    ["home:Campi di stasera", "schedule:Slot e disponibilità", "team:Squadre e convocati", "report:Tabellone del torneo", "D:admin:Campi, tornei e quote"]),

  X("fitness", "fitness-outdoor-functional", "outdoor-functional-sabbia-kaki", "Outdoor Functional", "Parco Forte", "Allenamento funzionale all'aperto.",
    "#F6F4EE,#FFFFFF,#1B1D17,#767A6C,#A16207,#4D7C0F", "Sans robusto 34px|Sans 15px|meteo integrato nell'header",
    "12px|1px kaki|8pt · card meteo-dipendenti|balanced", "tab bar sabbia con icona meteo|dark|icona meteo che cambia sezione",
    "allenamento nel parco all'alba, corde e kettlebell sull'erba, luce naturale",
    "meteo → sessione nel parco → attrezzi → gruppo",
    "corda naturale e sabbia da parco|luce naturale di prima mattina in un parco|sabbia con foglie e erba|device sull'erba tra kettlebell e corda|icona meteo grande dietro il titolo di sezione",
    ["home:Sessione all'aperto", "schedule:Calendario nel parco", "detail:Attrezzi e circuito", "team:Gruppo di allenamento", "D:admin:Sessioni, meteo e presenze"]),
];
