/** Espansione HOSPITALITY — 13 sotto-settori con stili esclusivi. */
import { X, type ExpansionRow } from "./mockup-identity-expansion-core";

export const HOSPITALITY_EXPANSION: ExpansionRow[] = [
  X("hospitality", "hosp-bb-borgo", "bb-borgo-pietra-calce", "B&B Borgo Pietra", "Casa del Vicolo", "Bed & breakfast nel borgo antico.",
    "#F7F2E9,#FFFFFF,#221D16,#847B6C,#9C6B3C,#6B7F6A", "Serif di paese 38px|Sans 15px|numeri civici come marcatori",
    "6px|1px pietra|8pt · colonna con foto quadrate|airy", "tab bar calce con chiave illustrata|dark|chiave antica come icona attiva",
    "vicoli in pietra, colazione sul tavolo di legno, luce di primo mattino",
    "borgo → camere → colazione → richiesta disponibilità",
    "pietra a vista e calce spatolata|luce di primo mattino nei vicoli|avorio con muro in pietra|device su tavolo di legno con chiave antica|chiave antica che apre ogni sezione",
    ["home:Il borgo e la casa", "catalog:Le nostre camere", "detail:Colazione del mattino", "booking:Verifica disponibilità", "D:admin:Camere, tariffe e colazioni"]),

  X("hospitality", "hosp-agriturismo", "agriturismo-grano-oliva", "Agriturismo Grano", "Podere Sette Querce", "Agriturismo con cucina dell'orto.",
    "#FAF6EA,#FFFFFF,#1F2116,#7C7F66,#8A9A2B,#C77C34", "Serif contadino 40px|Sans 15px|stagionalità in etichette",
    "10px|1px oliva|8pt · fasce di stagione|balanced", "tab bar grano con spiga attiva|dark|spiga di grano come indicatore",
    "campi di grano, verdure appena raccolte, luce dorata di campagna",
    "podere → alloggi → esperienze in fattoria → soggiorno",
    "iuta di sacco e foglia d'oliva|luce dorata di campagna al tramonto|grano con spighe mosse dal vento|device su cassetta di legno con verdure|spighe di grano piegate ai bordi delle card",
    ["home:Il podere", "catalog:Alloggi e casali", "detail:Esperienze in fattoria", "booking:Soggiorno con mezza pensione", "D:admin:Alloggi, orto e prenotazioni"]),

  X("hospitality", "hosp-hotel-business", "hotel-business-antracite-lime", "Hotel Business", "Hotel Meridiano", "Hotel business con sale meeting.",
    "#15181C,#1E2329,#EEF2F6,#8794A1,#A3E635,#38BDF8", "Sans efficiente 32px|Sans 14px|orari check-in in mono",
    "6px|1px antracite|8pt · griglia informativa densa|dense", "tab bar antracite con stato camera|light|indicatore di occupazione a barre",
    "hall business, vetrate, luce neutra, silhouette di viaggiatori",
    "check-in → camere → sale meeting → fattura aziendale",
    "vetro fumé e moquette tecnica|luce neutra da hall vetrata a doppia altezza|antracite con vetrate riflettenti|device su banco check-in in pietra scura|barre di occupazione dietro l'header",
    ["home:Check-in rapido", "catalog:Camere e tariffe corporate", "booking:Sale meeting", "docs:Fattura aziendale", "D:admin:Occupazione, tariffe e sale"]),

  X("hospitality", "hosp-ostello-urban", "ostello-urban-graffio-ciano", "Ostello Urban", "Letto Undici", "Ostello urbano per giovani viaggiatori.",
    "#101214,#191D21,#F2F5F7,#8A939B,#06B6D4,#FDE047", "Sans street 40px|Sans 14px|prezzi per letto in badge adesivo",
    "4px|2px ciano|8pt · griglia di letti|dense", "tab bar scura con badge adesivo|light|adesivi da valigia sovrapposti",
    "camerate colorate, zaini, luce artificiale mista, murales",
    "letti → camerate → eventi comuni → check-in self",
    "metallo verniciato dei letti e adesivi da valigia|luce artificiale mista di camerata|grigio urbano con murales sfocato|device su brandina con zaino accanto|adesivi da viaggio applicati sui bordi",
    ["home:Posti letto disponibili", "catalog:Camerate e private", "schedule:Eventi comuni", "order:Check-in self", "D:admin:Letti, turnover e pulizie"]),

  X("hospitality", "hosp-glamping", "glamping-tenda-canvas-fuoco", "Glamping Canvas", "Tende del Vento", "Glamping con tende safari e falò.",
    "#1A1712,#241F18,#F5EDE0,#9A8C79,#D97706,#84A07C", "Serif esploratore 38px|Sans 15px|coordinate GPS in mono",
    "12px|1px canvas|8pt · card da diario di viaggio|balanced", "tab bar canvas con lanterna attiva|light|lanterna che illumina la sezione attiva",
    "tende safari illuminate al crepuscolo, falò, cielo stellato",
    "campo → tende → falò serale → notti disponibili",
    "canvas da tenda e corda incatramata|luce di lanterna e falò al crepuscolo|bruno tenda con cielo stellato|device su tavolino da campo accanto alla lanterna|lanterna che illumina la sezione attiva",
    ["home:Il campo stellato", "catalog:Tende e suite outdoor", "detail:Falò e cena sotto le stelle", "booking:Notti disponibili", "D:admin:Piazzole, tende e stagione"]),

  X("hospitality", "hosp-resort-montagna", "resort-montagna-loden-neve", "Resort Loden", "Baita Corona", "Resort di montagna con spa e sci ai piedi.",
    "#131A18,#1C2523,#EFF4F2,#8A9A96,#0F766E,#E7E5E4", "Serif alpino 40px|Sans 15px|quote e piste in etichette",
    "8px|1px loden|8pt · sezioni a scalini|balanced", "tab bar loden con silhouette di vetta|light|silhouette di vetta come skyline",
    "legno antico e neve, spa con vista, luce fredda del pomeriggio alpino",
    "vetta → suite → spa → pacchetto sci",
    "legno di larice antico e lana loden|luce fredda del pomeriggio alpino|verde loden con vetta innevata|device su tavolo in larice con lana loden|silhouette della vetta che taglia l'header",
    ["home:Il resort e la vetta", "catalog:Suite e chalet", "detail:Spa e percorso benessere", "booking:Pacchetto sci", "D:admin:Suite, spa e skipass"]),

  X("hospitality", "hosp-casa-vacanze", "casavacanze-turchese-persiane", "Casa Vacanze Persiane", "Villetta Salina", "Case vacanza sul mare, gestione diretta.",
    "#F4FBFB,#FFFFFF,#0C2429,#6D8B90,#0891B2,#F4A261", "Sans marino 34px|Sans 15px|distanza dal mare in metri",
    "14px|1px turchese|8pt · card con persiane|balanced", "tab bar bianca con persiana come indicatore|dark|persiane a lamelle come divisori",
    "persiane azzurre, amache, mare sullo sfondo, luce di mezzogiorno estivo",
    "case → distanza dal mare → servizi → calendario disponibilità",
    "legno di persiana azzurra e lino da mare|luce di mezzogiorno estivo con riflesso marino|turchese con persiane socchiuse|device su tavolino con cappello di paglia|lamelle di persiana che filtrano le sezioni",
    ["home:Case sul mare", "catalog:Case e appartamenti", "detail:Servizi e distanze", "booking:Calendario disponibilità", "D:admin:Case, pulizie e calendario"]),

  X("hospitality", "hosp-boutique-design", "boutique-design-cemento-rame", "Boutique Design", "Numero Nove Suites", "Boutique hotel di design, nove suite.",
    "#1C1B1A,#252423,#F3F1EE,#8C8985,#B87333,#7C7A76", "Sans architetto 34px|Sans 14px|numeri suite in grande scala",
    "0px|hairline rame|8pt · griglia asimmetrica|airy", "tab bar cemento con numero suite|light|numero della suite in scala gigante",
    "arredi di design, cemento e rame, luce museale controllata",
    "suite → design e arredi → colazione d'autore → prenotazione diretta",
    "cemento levigato e rame ossidato|luce museale controllata a fascio strette|cemento con dettaglio in rame|device su blocco di cemento levigato|numero della suite gigante in filigrana",
    ["home:Nove suite d'autore", "catalog:Suite e arredi", "detail:Colazione firmata", "booking:Prenotazione diretta", "D:admin:Suite, tariffe e revenue"]),

  X("hospitality", "hosp-hotel-terme", "terme-travertino-vapore", "Terme Travertino", "Fonti Serene", "Hotel termale con acque sorgive.",
    "#F5F1EA,#FFFFFF,#1F1C17,#8A8175,#0E7490,#C2A878", "Serif termale 38px|Sans 15px|temperature acqua in gradi",
    "20px|1px travertino|8pt · vasche a fasce|airy", "tab bar travertino con onda termale|dark|onda d'acqua termale come separatore",
    "vasche di travertino, vapore che sale, luce dell'ora dorata",
    "fonti → percorso termale → camere → pacchetto benessere",
    "travertino poroso e acqua sorgiva|luce dell'ora dorata sul vapore che sale|beige travertino con vapore|device su bordo vasca in travertino bagnato|onda termale che attraversa i titoli",
    ["home:Le fonti", "catalog:Percorso termale", "detail:Camere e trattamenti", "booking:Pacchetto benessere", "D:admin:Vasche, turni e trattamenti"]),

  X("hospitality", "hosp-rifugio-alta-quota", "rifugio-legno-bruciato-stella", "Rifugio Legno Bruciato", "Rifugio Tre Cime", "Rifugio d'alta quota con mezza pensione.",
    "#100E0C,#1A1714,#F0E9DE,#918879,#EA580C,#93C5FD", "Sans essenziale 34px|Sans 15px|dislivelli in metri evidenziati",
    "4px|1px legno bruciato|8pt · lista sentieri|balanced", "tab bar scura con altimetro|light|altimetro a lancetta accanto ai titoli",
    "legno bruciato, cielo stellato d'alta quota, luce di candela",
    "sentieri → posti letto → cena in rifugio → prenotazione stagione",
    "legno bruciato dal sole e coperta di lana grezza|luce di candela e frontale in rifugio|nero notte con via lattea|device su tavolo di legno bruciato con frontale|altimetro a lancetta accanto ai titoli",
    ["home:Il rifugio e i sentieri", "catalog:Posti letto e camerate", "detail:Cena e mezza pensione", "booking:Prenotazione di stagione", "D:admin:Posti, sentieri e stagione"]),

  X("hospitality", "hosp-camping-village", "camping-village-verde-piazzola", "Camping Village", "Pineta Grande", "Camping village con piazzole e bungalow.",
    "#F3F8EF,#FFFFFF,#16210F,#728069,#65A30D,#F59E0B", "Sans famiglia 36px|Sans 15px|piazzole numerate a griglia",
    "16px|1px verde pino|8pt · mappa a griglia|balanced", "tab bar chiara con mappa piazzole|dark|mappa del village a griglia numerata",
    "pineta con camper, piscina del village, luce estiva filtrata dagli aghi di pino",
    "mappa village → piazzole e bungalow → animazione → soggiorno",
    "aghi di pino e telo da tenda cerato|luce estiva filtrata dai pini|verde pineta con ombre di aghi|device su tavolo da picnic in pineta|mappa a griglia con piazzole numerate in filigrana",
    ["home:Il village", "map:Mappa piazzole", "catalog:Bungalow e mobile home", "booking:Soggiorno in pineta", "D:admin:Piazzole, arrivi e animazione"]),

  X("hospitality", "hosp-residence-urbano", "residence-urbano-grigio-tortora", "Residence Urbano", "Residenza Portanova", "Residence urbano per soggiorni lunghi.",
    "#F6F6F5,#FFFFFF,#191A1A,#7B7D7D,#475569,#A78BFA", "Sans neutro 32px|Sans 14px|durata soggiorno in settimane",
    "10px|1px tortora|8pt · tabella tariffe a scaglioni|dense", "tab bar tortora con durata attiva|dark|scaglioni di durata a gradini",
    "appartamenti arredati, città dalla finestra, luce diurna piatta",
    "appartamenti → tariffe per durata → servizi inclusi → contratto",
    "tortora opaco e tessuto d'arredo tecnico|luce diurna piatta da finestra d'appartamento|tortora con città sfocata|device su piano cucina in laminato tortora|gradini di durata sopra la tabella tariffe",
    ["home:Soggiorni lunghi", "catalog:Appartamenti arredati", "wallet:Tariffe per durata", "docs:Contratto e servizi", "D:admin:Unità, contratti e utenze"]),

  X("hospitality", "hosp-dimora-storica", "dimora-storica-affresco-oro", "Dimora Storica Affresco", "Palazzo Bellante", "Dimora storica con sale affrescate.",
    "#F8F4EA,#FFFFFF,#1C1710,#877E6B,#8C6D1F,#5B4A6F", "Serif classico 44px|Sans 14px|secoli in numeri romani",
    "0px|1px oro antico|8pt · impaginato da volume antico|airy", "tab bar avorio con cornice dorata|dark|cornice dorata da quadro attorno alle sezioni",
    "affreschi, stucchi dorati, luce da finestre alte di palazzo",
    "storia → sale e appartamenti → eventi privati → soggiorno",
    "affresco a calce e foglia d'oro antica|luce da finestre alte di palazzo nobiliare|avorio con affresco sfocato|device su consolle dorata sotto un affresco|cornice dorata da quadro attorno alle sezioni",
    ["home:La dimora", "catalog:Sale e appartamenti", "detail:Eventi privati", "booking:Soggiorno d'epoca", "D:admin:Sale, eventi e manutenzioni"]),
];
