project_id = "gypnxirzmhpapmhjguaj"

[functions.ai-menu]
verify_jwt = false

[functions.ai-inventory]
verify_jwt = false

[functions.ai-translate]
verify_jwt = false

[functions.send-push-discount]
verify_jwt = false

[functions.assign-partner-role]
verify_jwt = false

[functions.empire-assistant]
verify_jwt = false
