export interface LowengeldStyle {
  slug: string;               // matches the file public/lowengeld-refs/{slug}.webp
  ref_url: string;            // "https://empireia.lovable.app/lowengeld-refs/{slug}.webp"
  brand_original: string;     // from title
  brand_italian: string;      // Italian-rebrand of the brand
  sector: "food" | "beauty" | "pet" | "fitness" | "ncc" | "hospitality" | "real_estate" | "construction" | "healthcare" | "retail" | "professional" | "childcare" | "automotive" | "wellness" | "events" | "nautical";
  sector_keywords: string[];
  style_name: string;
  palette: string;
  screen_labels: [string, string, string, string];
  vibe: string;
}

export const LOWENGELD_STYLES: LowengeldStyle[] = [
  {
    slug: "flame-kebab",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/flame-kebab.webp",
    brand_original: "Flame Kebab",
    brand_italian: "Fiamma Etnica Milano",
    sector: "food",
    sector_keywords: ["kebab", "street food", "fast casual", "griglia"],
    style_name: "Neon Fire Street Food",
    palette: "nero opaco, arancio brace, rosso peperoncino, oro caldo",
    screen_labels: ["Home", "Menu", "Dettaglio", "Ordina"],
    vibe: "Un'estetica street food ad alta energia, dominata dal bagliore della griglia e da tipografia bold da insegna luminosa.",
  },
  {
    slug: "aloha-pet-resorts",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/aloha-pet-resorts.webp",
    brand_original: "Aloha Pet Resorts",
    brand_italian: "Onyx Resort per Animali Torino",
    sector: "pet",
    sector_keywords: ["pet resort", "cani", "gatti", "boarding", "spa animali"],
    style_name: "Tropical Pet Luxe",
    palette: "verde palma, corallo, sabbia chiara, turchese",
    screen_labels: ["Home", "Servizi", "Dettaglio", "Prenota"],
    vibe: "Un rifugio tropicale e rilassato per animali, con illustrazioni morbide e colori da resort esotico.",
  },
  {
    slug: "otomaki-sushi",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/otomaki-sushi.webp",
    brand_original: "Otomaki Sushi",
    brand_italian: "Otomaki Sushi Bar Milano",
    sector: "food",
    sector_keywords: ["sushi", "giapponese", "ristorante", "delivery"],
    style_name: "Editorial Sakura Minimal",
    palette: "bianco perla, rosa sakura, nero laccato, oro sottile",
    screen_labels: ["Home", "Menu", "Dettaglio", "Prenota"],
    vibe: "Un'eleganza giapponese minimale, quasi editoriale, dove ogni piatto è fotografato come un'opera d'arte.",
  },
  {
    slug: "la-patrona",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/la-patrona.webp",
    brand_original: "La Patrona",
    brand_italian: "La Patrona Trattoria Bologna",
    sector: "food",
    sector_keywords: ["cucina tradizionale", "ristorante", "catering", "famiglia"],
    style_name: "Warm Editorial Terracotta",
    palette: "terracotta, crema, verde oliva, ruggine",
    screen_labels: ["Home", "Menu", "Dettaglio", "Prenota"],
    vibe: "Un calore casalingo e generoso, raccontato con toni terracotta e una tipografia da libro di ricette.",
  },
  {
    slug: "papagua",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/papagua.webp",
    brand_original: "Papagua",
    brand_italian: "Papagua Bowl Bar Napoli",
    sector: "food",
    sector_keywords: ["poke", "bowl", "tropicale", "healthy food"],
    style_name: "Playful Tropical Pop",
    palette: "giallo mango, verde lime, corallo, bianco panna",
    screen_labels: ["Home", "Menu", "Dettaglio", "Ordina"],
    vibe: "Un'esplosione di colori tropicali e forme arrotondate che comunicano freschezza e leggerezza.",
  },
  {
    slug: "meridia-rental-car",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/meridia-rental-car.webp",
    brand_original: "Meridia Rental Car",
    brand_italian: "Meridia Autonoleggio Firenze",
    sector: "automotive",
    sector_keywords: ["noleggio auto", "car rental", "flotta", "viaggi"],
    style_name: "Swiss Minimal Corporate",
    palette: "bianco, blu petrolio, grigio argento, accenti ciano",
    screen_labels: ["Home", "Flotta", "Dettaglio Auto", "Prenota"],
    vibe: "Un design pulito e funzionale ispirato allo swiss style, pensato per la fiducia e l'efficienza del business travel.",
  },
  {
    slug: "neo-nails-brickell",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/neo-nails-brickell.webp",
    brand_original: "Neo Nails Brickell",
    brand_italian: "Atelier Unghie Milano",
    sector: "beauty",
    sector_keywords: ["nail salon", "unghie", "manicure", "estetica"],
    style_name: "Frosted Glass Lavender",
    palette: "lavanda, pesca, cielo, bianco latte",
    screen_labels: ["Home", "Servizi", "Trattamento", "Prenota"],
    vibe: "Un glassmorphism etereo con pannelli traslucidi e gradienti pastello, ispirato all'estetica Vision Pro.",
  },
  {
    slug: "little-diamond-nursery",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/little-diamond-nursery.webp",
    brand_original: "Little Diamond Nursery",
    brand_italian: "Piccolo Diamante Nido Roma",
    sector: "childcare",
    sector_keywords: ["asilo nido", "bambini", "scuola infanzia", "attivita"],
    style_name: "Playful Kid Pastel",
    palette: "giallo sole, azzurro cielo, rosa corallo, verde menta",
    screen_labels: ["Home", "Programmi", "Attivita", "Iscrizione"],
    vibe: "Un mondo giocoso e vivace pensato per rassicurare i genitori e incantare i bambini.",
  },
  {
    slug: "midtown-kosher",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/midtown-kosher.webp",
    brand_original: "Midtown Kosher",
    brand_italian: "Midtown Kosher Deli Torino",
    sector: "food",
    sector_keywords: ["kosher", "ristorante", "gastronomia ebraica", "delivery"],
    style_name: "Israeli Modern Sapphire",
    palette: "blu zaffiro, bianco, argento, azzurro cielo",
    screen_labels: ["Home", "Menu", "Prodotto", "Checkout"],
    vibe: "Un modernismo pulito ispirato alla bandiera israeliana, con superfici bianche e accenti blu profondo.",
  },
  {
    slug: "asinara-charter",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/asinara-charter.webp",
    brand_original: "Asinara Charter",
    brand_italian: "Asinara Charter Costiero Genova",
    sector: "nautical",
    sector_keywords: ["charter", "yacht", "noleggio barche", "costa smeralda"],
    style_name: "Azure Marble Luxury",
    palette: "blu profondo, oro caldo, bianco marmo, avorio",
    screen_labels: ["Home", "Escursioni", "Imbarcazione", "Prenota"],
    vibe: "Un lusso marittimo senza tempo, tra marmo bianco e oro caldo, degno di uno yacht club esclusivo.",
  },
  {
    slug: "city-padel-milano",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/city-padel-milano.webp",
    brand_original: "City Padel Milano",
    brand_italian: "Padel Club Città Milano",
    sector: "fitness",
    sector_keywords: ["padel", "campo sportivo", "corsi", "prenotazione campo"],
    style_name: "Fresh iOS Green Clean",
    palette: "verde smeraldo, bianco, grigio chiaro, lime",
    screen_labels: ["Home", "Campi", "Corsi", "Prenota"],
    vibe: "Un design pulito in stile iOS 18, fresco e sportivo, pensato per prenotare un campo in pochi tocchi.",
  },
  {
    slug: "miami-boats-rental",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/miami-boats-rental.webp",
    brand_original: "Miami Boats Rental",
    brand_italian: "Riviera Boats Rental Genova",
    sector: "nautical",
    sector_keywords: ["noleggio barche", "yacht", "boat rental", "mare"],
    style_name: "Ocean Deep Blue Luxury",
    palette: "blu oceano, champagne, bianco spuma, turchese",
    screen_labels: ["Home", "Flotta", "Imbarcazione", "Prenota"],
    vibe: "Un'immersione nel blu profondo dell'oceano, con dettagli champagne che richiamano il lusso nautico.",
  },
  {
    slug: "cote-miami",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/cote-miami.webp",
    brand_original: "COTE Miami",
    brand_italian: "Bragia Milano Steakhouse",
    sector: "food",
    sector_keywords: ["steakhouse", "carne", "fine dining", "cucina coreana"],
    style_name: "Michelin Obsidian Steakhouse",
    palette: "nero ossidiana, oro brace, rosso vino, grafite",
    screen_labels: ["Home", "Menu", "Piatto", "Prenota"],
    vibe: "Un'atmosfera Michelin scura e magnetica, dove il nero ossidiana incontra il bagliore dorato della griglia.",
  },
  {
    slug: "mmi-resident-hub",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/mmi-resident-hub.webp",
    brand_original: "MMI Resident Hub",
    brand_italian: "Torre Aurora Residence Roma",
    sector: "real_estate",
    sector_keywords: ["residence", "condominio", "portale residenti", "gestione immobiliare"],
    style_name: "White Luxury Ocean Azure",
    palette: "bianco puro, azzurro oceano, grigio perla, oro rosa",
    screen_labels: ["Home", "Servizi", "Prenotazione", "Pagamenti"],
    vibe: "Un bianco luminoso e rarefatto da grattacielo di lusso, con tocchi di azzurro oceano rilassante.",
  },
  {
    slug: "far-medical-solutions",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/far-medical-solutions.webp",
    brand_original: "FAR Medical Solutions",
    brand_italian: "FAR Medical Devices Bologna",
    sector: "healthcare",
    sector_keywords: ["dispositivi medici", "sanita", "ricerca", "regolatorio"],
    style_name: "Ethereal Glass Azure",
    palette: "bianco ghiaccio, azzurro etereo, blu polvere, argento",
    screen_labels: ["Home", "Servizi", "Dettaglio", "Contatti"],
    vibe: "Una luce eterea e clinica, con superfici vetrose che comunicano precisione scientifica e affidabilità.",
  },
  {
    slug: "tatush-hair-fragrance",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/tatush-hair-fragrance.webp",
    brand_original: "Tatush Hair Fragrance",
    brand_italian: "Tatush Profumo Capelli Firenze",
    sector: "beauty",
    sector_keywords: ["profumo capelli", "haircare", "cosmetica", "beauty retail"],
    style_name: "Fresh Minimal Blanc",
    palette: "bianco puro, rosa cipria, oro rosa, avorio",
    screen_labels: ["Home", "Prodotti", "Dettaglio", "Carrello"],
    vibe: "Un minimalismo candido e delicato, illuminato da accenti rose gold degni di un profumo di nicchia.",
  },
  {
    slug: "miami-watersports",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/miami-watersports.webp",
    brand_original: "Miami Watersports",
    brand_italian: "Tropea Watersports Napoli",
    sector: "wellness",
    sector_keywords: ["sport acquatici", "jet ski", "parasailing", "noleggio"],
    style_name: "Tropical Energy Riviera",
    palette: "turchese acceso, corallo, giallo sole, bianco",
    screen_labels: ["Home", "Attivita", "Dettaglio", "Prenota"],
    vibe: "Un'energia tropicale vibrante che trasmette adrenalina e divertimento sotto il sole.",
  },
  {
    slug: "strapizzami",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/strapizzami.webp",
    brand_original: "STRAPIZZAMI",
    brand_italian: "Strapizzami Napoli DOC",
    sector: "food",
    sector_keywords: ["pizzeria", "pizza napoletana", "forno a legna", "delivery"],
    style_name: "Napoletana DOC Fuoco Moderno",
    palette: "rosso pomodoro, nero forno, bianco mozzarella, oro",
    screen_labels: ["Home", "Menu", "Carrello", "Ordini"],
    vibe: "Un fuoco moderno che celebra la tradizione napoletana con grafica bold e ingredienti in primo piano.",
  },
  {
    slug: "paperfish-sushi",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/paperfish-sushi.webp",
    brand_original: "Paperfish Sushi",
    brand_italian: "Paperfish Sushi Nikkei Milano",
    sector: "food",
    sector_keywords: ["sushi", "giapponese", "nikkei", "sakura"],
    style_name: "Sakura Ice Minimal",
    palette: "rosa sakura, bianco ghiaccio, nero laccato, verde matcha",
    screen_labels: ["Home", "Menu", "Dettaglio", "Ordina"],
    vibe: "Un equilibrio delicato tra freschezza ghiacciata e la poesia dei fiori di ciliegio giapponesi.",
  },
  {
    slug: "nick-s-plumbing-ac",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/nick-s-plumbing-ac.webp",
    brand_original: "Nick's Plumbing & AC",
    brand_italian: "Nicò Idraulica & Clima Torino",
    sector: "construction",
    sector_keywords: ["idraulico", "climatizzazione", "assistenza domestica", "riparazioni"],
    style_name: "Clean White Green Service",
    palette: "bianco, verde tecnico, grigio antracite, giallo sicurezza",
    screen_labels: ["Home", "Servizi", "Preventivo", "Prenota"],
    vibe: "Un servizio domestico affidabile raccontato con un bianco pulito e accenti verde tecnico rassicuranti.",
  },
  {
    slug: "la-vang-vietnamese-luxury",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/la-vang-vietnamese-luxury.webp",
    brand_original: "La Vang Vietnamese Luxury",
    brand_italian: "La Vang Saigon Luxury Roma",
    sector: "food",
    sector_keywords: ["vietnamita", "fine dining", "asian fusion", "luxury dining"],
    style_name: "Noir Saigon Jade Dynasty",
    palette: "nero laccato, giada, oro antico, rosso cremisi",
    screen_labels: ["Home", "Menu", "Piatto", "Prenota"],
    vibe: "Un noir orientale sofisticato, dove il verde giada e l'oro antico raccontano una dinastia di sapori.",
  },
  {
    slug: "ashley-s-playhouse",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/ashley-s-playhouse.webp",
    brand_original: "Ashley's Playhouse",
    brand_italian: "Casa Giocosa Bologna",
    sector: "childcare",
    sector_keywords: ["asilo", "childcare", "attivita bambini", "drop-in"],
    style_name: "Autumn Maple Gold Playhouse",
    palette: "arancio zucca, oro foglia, marrone caldo, crema",
    screen_labels: ["Home", "Programmi", "Attivita", "Iscrizione"],
    vibe: "Un tepore autunnale fatto di foglie dorate e zucche, accogliente come una seconda casa per i bambini.",
  },
  {
    slug: "batey-cevicheria-urbana",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/batey-cevicheria-urbana.webp",
    brand_original: "Batey Cevicheria Urbana",
    brand_italian: "Batey Cevicheria Urbana Milano",
    sector: "food",
    sector_keywords: ["cevicheria", "peruviano", "fine dining", "cucina latina"],
    style_name: "Costa del Pacifico Warm",
    palette: "blu pacifico, ocra, bianco calce, corallo",
    screen_labels: ["Home", "Menu", "Piatto", "Prenota"],
    vibe: "Un sabor peruviano autentico e caldo, con forme morbide e colori che ricordano la costa del Pacifico.",
  },
  {
    slug: "little-stars-daycare",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/little-stars-daycare.webp",
    brand_original: "Little Stars Daycare",
    brand_italian: "Piccole Stelle Daycare Verona",
    sector: "childcare",
    sector_keywords: ["asilo", "daycare", "bambini", "attivita"],
    style_name: "Playful Colorful Vivid",
    palette: "giallo, azzurro, rosa acceso, verde prato",
    screen_labels: ["Home", "Attivita", "Diario", "Prenota"],
    vibe: "Un vivace mosaico di colori pensato per rassicurare i genitori con trasparenza e allegria.",
  },
  {
    slug: "pawparadise",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/pawparadise.webp",
    brand_original: "PawParadise",
    brand_italian: "Paradiso a Quattro Zampe Torino",
    sector: "pet",
    sector_keywords: ["pet hotel", "toelettatura", "cani", "gatti"],
    style_name: "Clean Pastel Pet Boarding",
    palette: "azzurro polvere, panna, verde salvia, corallo tenue",
    screen_labels: ["Home", "Servizi", "Dettaglio", "Prenota"],
    vibe: "Un rifugio pastello soffice e pulito, pensato per il comfort di cani e gatti in vacanza.",
  },
  {
    slug: "top-golf-bay-app",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/top-golf-bay-app.webp",
    brand_original: "Top Golf Bay App",
    brand_italian: "Golf Bay Club Milano",
    sector: "fitness",
    sector_keywords: ["golf", "driving range", "prenotazione bay", "sport"],
    style_name: "Official Sport Bold",
    palette: "verde campo, bianco, nero grafite, giallo pallina",
    screen_labels: ["Home", "Prenota Bay", "Coda", "Dashboard"],
    vibe: "Un design sportivo ufficiale e diretto, costruito per la velocità di prenotazione e chiarezza dei dati.",
  },
  {
    slug: "luxdrive",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/luxdrive.webp",
    brand_original: "LuxDrive",
    brand_italian: "LuxDrive Auto Prestige Roma",
    sector: "automotive",
    sector_keywords: ["noleggio auto", "car rental", "auto sportive", "luxury cars"],
    style_name: "Midnight Emerald Dark",
    palette: "nero notte, verde smeraldo, argento, lime elettrico",
    screen_labels: ["Home", "Flotta", "Dettaglio Auto", "Prenota"],
    vibe: "Un'estetica dark premium da supercar, con riflessi smeraldo che accendono la notte.",
  },
  {
    slug: "texas-horse-ranch-5-style-proposals",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/texas-horse-ranch-5-style-proposals.webp",
    brand_original: "Texas Horse Ranch - 5 Style Proposals",
    brand_italian: "Tenuta del Cavallo Firenze",
    sector: "wellness",
    sector_keywords: ["equitazione", "ranch", "cavalli", "club equestre"],
    style_name: "Velvet Saddle Equestrian",
    palette: "marrone sella, verde prato, avorio, oro ottone",
    screen_labels: ["Home", "Servizi", "Cavallo", "Prenota"],
    vibe: "Un'eleganza rurale vellutata che celebra la tradizione equestre con materiali caldi e naturali.",
  },
  {
    slug: "aura-milano-spa",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/aura-milano-spa.webp",
    brand_original: "Aura Milano Spa",
    brand_italian: "Aura Wellness Spa Milano",
    sector: "wellness",
    sector_keywords: ["spa", "benessere", "trattamenti", "massaggi"],
    style_name: "Luce Pura Serenity",
    palette: "bianco latte, azzurro tenue, oro chiaro, grigio perla",
    screen_labels: ["Home", "Trattamenti", "Dettaglio", "Prenota"],
    vibe: "Una luce pura e serena che accompagna il visitatore in un percorso di totale relax.",
  },
  {
    slug: "dimora-milano",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/dimora-milano.webp",
    brand_original: "DIMORA Milano",
    brand_italian: "Dimora Immobiliare Milano",
    sector: "real_estate",
    sector_keywords: ["immobiliare", "agenzia", "annunci", "case di lusso"],
    style_name: "Eleganza Milanese Verde Urbano",
    palette: "verde urbano, grigio caldo, bianco, nero lusso",
    screen_labels: ["Home", "Annunci", "Immobile", "Contatti"],
    vibe: "Un'eleganza milanese sobria e urbana, dove il verde profondo dialoga con superfici minimali.",
  },
  {
    slug: "pokewaii-brescia",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/pokewaii-brescia.webp",
    brand_original: "Pokewaii Brescia",
    brand_italian: "Pokewaii Hawaiian Bowl Brescia",
    sector: "food",
    sector_keywords: ["poke", "hawaiano", "bowl", "delivery"],
    style_name: "Tropical Hawaiano Fresh",
    palette: "turchese, corallo, giallo ananas, bianco",
    screen_labels: ["Home", "Menu", "Dettaglio", "Ordina"],
    vibe: "Un tuffo tropicale hawaiano fresco e colorato, perfetto per un pasto veloce e sano.",
  },
  {
    slug: "pawcare",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/pawcare.webp",
    brand_original: "PawCare",
    brand_italian: "PawCare Spa Animali Bologna",
    sector: "pet",
    sector_keywords: ["grooming", "toelettatura", "veterinaria", "spa animali"],
    style_name: "Clean Pastel Minimal",
    palette: "azzurro polvere, panna, verde salvia, bianco",
    screen_labels: ["Home", "Servizi", "Prenotazione", "Dashboard"],
    vibe: "Un minimalismo pastello rassicurante, pensato per il benessere di cani e gatti e la comodità dei proprietari.",
  },
  {
    slug: "addio-dipendenti-da-oggi-l-ia-lavora-per-te",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/addio-dipendenti-da-oggi-l-ia-lavora-per-te.webp",
    brand_original: "ADDIO DIPENDENTI! DA OGGI L'IA LAVORA PER TE",
    brand_italian: "Voce Digitale AI Milano",
    sector: "professional",
    sector_keywords: ["ai voice agent", "automazione", "ristorazione", "assistente virtuale"],
    style_name: "Tech Neon Landing",
    palette: "nero profondo, blu elettrico, viola neon, bianco",
    screen_labels: ["Home", "Funzionalita", "Demo", "Contatti"],
    vibe: "Un'estetica tech futuristica dai riflessi neon, che promette efficienza automatizzata 24 ore su 24.",
  },
  {
    slug: "reformer-pilates",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/reformer-pilates.webp",
    brand_original: "REFORMER Pilates",
    brand_italian: "Reformer Studio Torino",
    sector: "fitness",
    sector_keywords: ["pilates", "reformer", "studio fitness", "benessere"],
    style_name: "Blush Editorial Aesthetic",
    palette: "rosa blush, bordeaux, avorio, nero opaco",
    screen_labels: ["Home", "Orario", "Lezione", "Dashboard"],
    vibe: "Un'estetica editoriale delicata in rosa blush, elegante e rilassata come uno studio di pilates boutique.",
  },
  {
    slug: "orygano-pizzeria-gourmet",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/orygano-pizzeria-gourmet.webp",
    brand_original: "Orygano Pizzeria Gourmet",
    brand_italian: "Orygano Pizzeria Gourmet Catania",
    sector: "food",
    sector_keywords: ["pizzeria gourmet", "forno", "ristorazione", "delivery"],
    style_name: "Dark Gourmet Natural",
    palette: "nero profondo, verde salvia, oro tenue, crema",
    screen_labels: ["Home", "Menu", "Dettaglio", "Carrello"],
    vibe: "Un gourmet oscuro ed elegante, con foglie decorative che portano naturalezza sul nero profondo.",
  },
  {
    slug: "meraki-greek-bistro",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/meraki-greek-bistro.webp",
    brand_original: "Meraki Greek Bistro",
    brand_italian: "Meraki Bistrot Greco Bari",
    sector: "food",
    sector_keywords: ["cucina greca", "bistrot", "fine dining", "mediterraneo"],
    style_name: "Greek Flag Luxury Marble",
    palette: "blu egeo, oro, bianco marmo, azzurro cielo",
    screen_labels: ["Home", "Menu", "Piatto", "Prenota"],
    vibe: "Un lusso mediterraneo ispirato all'Egeo, tra marmo bianco e riflessi dorati.",
  },
  {
    slug: "tiramistu",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/tiramistu.webp",
    brand_original: "Tiramistu",
    brand_italian: "Tiramistu Caffe Milano",
    sector: "food",
    sector_keywords: ["tiramisu", "coffee bar", "dolci", "caffetteria"],
    style_name: "Crema Italiano Warm",
    palette: "crema, marrone caffe, cacao, oro tenue",
    screen_labels: ["Home", "Menu", "Dettaglio", "Carrello"],
    vibe: "Un calore italiano cremoso, dolce e avvolgente come il tiramisù stesso.",
  },
  {
    slug: "arredissima",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/arredissima.webp",
    brand_original: "ArredissimA",
    brand_italian: "Arredissima Home Design Torino",
    sector: "retail",
    sector_keywords: ["arredamento", "content automation", "instagram", "catalogo mobili"],
    style_name: "Bold Geometric Corporate",
    palette: "rosso corporate, bianco, grigio chiaro, nero",
    screen_labels: ["Dashboard", "Calendario", "Catalogo", "Analytics"],
    vibe: "Un corporate bold e geometrico, dominato dal rosso brand su superfici bianche pulite.",
  },
  {
    slug: "alma-regina-relais-5-style-proposals",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/alma-regina-relais-5-style-proposals.webp",
    brand_original: "Alma Regina Relais - 5 Style Proposals",
    brand_italian: "Alma Regina Relais Napoli",
    sector: "hospitality",
    sector_keywords: ["b&b", "boutique hotel", "ospitalita", "relais"],
    style_name: "Cipria Boudoir Luxury",
    palette: "rosa cipria, oro champagne, avorio, bordeaux tenue",
    screen_labels: ["Home", "Camere", "Camera", "Dashboard"],
    vibe: "Un boudoir cipria intimo e raffinato, che accoglie l'ospite come in un piccolo palazzo napoletano.",
  },
  {
    slug: "assocard-le-convenzioni",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/assocard-le-convenzioni.webp",
    brand_original: "ASSOCARD - Le Convenzioni",
    brand_italian: "AssoConvenzioni Milano",
    sector: "professional",
    sector_keywords: ["membership", "convenzioni", "sconti", "tessera soci"],
    style_name: "RevPoints Violet Membership",
    palette: "viola intenso, magenta, bianco, argento",
    screen_labels: ["Home", "Catalogo", "Convenzione", "Tessera"],
    vibe: "Un'identità membership vivace in viola e magenta, pensata per premiare la fedeltà dei soci.",
  },
  {
    slug: "agarty-atelier-digitale",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/agarty-atelier-digitale.webp",
    brand_original: "AGARTY - Atelier Digitale",
    brand_italian: "Agarty Atelier Milano",
    sector: "beauty",
    sector_keywords: ["atelier moda", "couture", "boutique luxury", "fashion tech"],
    style_name: "Powder Rose Old Money",
    palette: "rosa cipria, crema, oro pallido, tortora",
    screen_labels: ["Boutique", "AI Studio", "Dashboard", "Concierge"],
    vibe: "Un'eleganza old money in rosa cipria e crema, raffinata e discreta per una clientela luxury.",
  },
  {
    slug: "dental-masters-admin-suite",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/dental-masters-admin-suite.webp",
    brand_original: "DENTAL MASTERS - Admin Suite",
    brand_italian: "Dental Masters Suite Bologna",
    sector: "healthcare",
    sector_keywords: ["studio dentistico", "marketing dentale", "gestionale", "agenzia"],
    style_name: "Clean Corporate Teal",
    palette: "teal medicale, bianco, grigio chiaro, blu ghiaccio",
    screen_labels: ["Dashboard", "Calendario", "Marketing AI", "Analytics"],
    vibe: "Un corporate clinico e pulito in teal medicale, pensato per l'efficienza gestionale degli studi dentistici.",
  },
  {
    slug: "luxury-car-wash",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/luxury-car-wash.webp",
    brand_original: "LUXURY CAR WASH",
    brand_italian: "Luxury Car Wash Milano",
    sector: "automotive",
    sector_keywords: ["autolavaggio", "car wash", "bistrot", "detailing"],
    style_name: "Neon Green Glow Sport",
    palette: "nero opaco, verde lime neon, grigio antracite, bianco",
    screen_labels: ["Home", "Booking", "Menu Bistrot", "Dashboard"],
    vibe: "Un dark luxury sportivo dai bagliori verde lime, ispirato all'estetica delle supercar tedesche.",
  },
  {
    slug: "gestionale-studio-longobardi",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/gestionale-studio-longobardi.webp",
    brand_original: "Gestionale Studio Longobardi",
    brand_italian: "Studio Longobardi Napoli",
    sector: "healthcare",
    sector_keywords: ["clinica dentale", "gestionale", "pazienti", "estetica dentale"],
    style_name: "Minimal Editorial Premium",
    palette: "avorio, oro rosa, grigio caldo, bianco",
    screen_labels: ["Dashboard", "Pazienti", "Trattamenti", "Portale"],
    vibe: "Un editoriale minimale e premium in avorio e oro rosa, per una clinica dentale di alta gamma.",
  },
  {
    slug: "gold-vento-real-estate",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/gold-vento-real-estate.webp",
    brand_original: "Gold Vento Real Estate",
    brand_italian: "Vento Immobiliare Milano",
    sector: "real_estate",
    sector_keywords: ["agenzia immobiliare", "dubai", "proprieta di lusso", "broker"],
    style_name: "Gold Royale Luxury",
    palette: "antracite, oro royale, nero, avorio",
    screen_labels: ["Home", "Proprieta", "Chi Siamo", "Contatti"],
    vibe: "Un lusso royale in oro e antracite, pensato per proprietà esclusive e clientela internazionale.",
  },
  {
    slug: "annalisa-longobardi-luxury-dental-app",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/annalisa-longobardi-luxury-dental-app.webp",
    brand_original: "Annalisa Longobardi Luxury Dental App",
    brand_italian: "Dott.ssa Longobardi Dental Napoli",
    sector: "healthcare",
    sector_keywords: ["studio dentistico", "dentista luxury", "invisalign", "estetica"],
    style_name: "Prugna Signature Editorial",
    palette: "prugna, avorio, oro champagne, crema",
    screen_labels: ["Home", "Servizi", "Trattamento", "Prenota"],
    vibe: "Una firma cromatica prugna elegante, arricchita da oro champagne su tonalità avorio luminose.",
  },
  {
    slug: "edilprogress-matera",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/edilprogress-matera.webp",
    brand_original: "Edilprogress Matera",
    brand_italian: "Edilprogress Costruzioni Matera",
    sector: "construction",
    sector_keywords: ["edilizia", "costruzioni", "restauro", "impresa edile"],
    style_name: "Warm Mediterraneo Sassi",
    palette: "ocra, terracotta, pietra chiara, bruno caldo",
    screen_labels: ["Home", "Portfolio", "Realizzazioni", "Contatti"],
    vibe: "Un calore mediterraneo ispirato ai Sassi, con terre e ocra che richiamano l'edilizia storica.",
  },
  {
    slug: "studio-elettro-impianti",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/studio-elettro-impianti.webp",
    brand_original: "Studio Elettro Impianti",
    brand_italian: "Studio Elettro Impianti Verona",
    sector: "construction",
    sector_keywords: ["impianti elettrici", "ingegneria", "fotovoltaico", "domotica"],
    style_name: "Green Energy Clean",
    palette: "verde rinnovabile, bianco, grigio tecnico, ciano",
    screen_labels: ["Home", "Servizi", "Studio", "Contatti"],
    vibe: "Un tecnicismo pulito in verde energia, che comunica sostenibilità e competenza ingegneristica.",
  },
  {
    slug: "termoacciai-matera",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/termoacciai-matera.webp",
    brand_original: "Termoacciai Matera",
    brand_italian: "Termoacciai Impianti Matera",
    sector: "construction",
    sector_keywords: ["termoidraulica", "assistenza tecnica", "magazino ricambi", "gestionale"],
    style_name: "Clean Corporate Blue",
    palette: "blu aziendale, bianco, grigio chiaro, azzurro ghiaccio",
    screen_labels: ["Ordini", "Magazzino", "Assistenza", "AI Preventivi"],
    vibe: "Un corporate pulito in blu aziendale, costruito per la gestione efficiente di ordini e assistenza.",
  },
  {
    slug: "edil-prato-sito-web",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/edil-prato-sito-web.webp",
    brand_original: "Edil Prato Sito Web",
    brand_italian: "Edil Prato Costruzioni Firenze",
    sector: "construction",
    sector_keywords: ["edilizia", "costruzioni", "ristrutturazioni", "impresa edile"],
    style_name: "Eleganza Toscana Corporate",
    palette: "verde cipresso, crema, terracotta, grigio pietra",
    screen_labels: ["Home", "Progetti", "Dettaglio", "Contatti"],
    vibe: "Un'eleganza toscana sobria, tra crema e verde cipresso, che racconta solidità costruttiva.",
  },
  {
    slug: "edil-prato-gestionale",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/edil-prato-gestionale.webp",
    brand_original: "Edil Prato Gestionale",
    brand_italian: "Edil Prato Gestionale Firenze",
    sector: "construction",
    sector_keywords: ["gestionale edile", "cantieri", "preventivi", "AI edilizia"],
    style_name: "Minimal Editorial Cipresso",
    palette: "verde cipresso, bianco, grigio chiaro, crema",
    screen_labels: ["Cantieri", "Preventivi", "Squadre", "AI Computo"],
    vibe: "Un gestionale minimale in verde cipresso, pensato per la chiarezza operativa dei cantieri.",
  },
  {
    slug: "dr-costruzioni",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/dr-costruzioni.webp",
    brand_original: "DR Costruzioni",
    brand_italian: "DR Costruzioni Benevento",
    sector: "construction",
    sector_keywords: ["edilizia", "costruzioni", "ristrutturazioni", "consulenza tecnica"],
    style_name: "Cantiere Premium Heritage",
    palette: "bruno cantiere, ocra, bianco, grigio cemento",
    screen_labels: ["Home", "Portfolio", "Dettaglio", "Preventivo"],
    vibe: "Un heritage mediterraneo robusto, con toni cantiere premium che ispirano fiducia tecnica.",
  },
  {
    slug: "termoacciai-sito-web",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/termoacciai-sito-web.webp",
    brand_original: "Termoacciai Sito Web",
    brand_italian: "Termoacciai Showroom Matera",
    sector: "construction",
    sector_keywords: ["termoidraulica", "showroom", "assistenza 24/7", "vendita ricambi"],
    style_name: "Corporate Blu Coerente",
    palette: "blu aziendale, bianco, arancio caldo, grigio chiaro",
    screen_labels: ["Home", "Prodotti", "Assistenza", "Contatti"],
    vibe: "Una coerenza corporate blu che unisce showroom e assistenza in un'esperienza affidabile.",
  },
  {
    slug: "idraulica-carrieri",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/idraulica-carrieri.webp",
    brand_original: "Idraulica Carrieri",
    brand_italian: "Idraulica Carrieri Ferrara",
    sector: "construction",
    sector_keywords: ["idraulica", "climatizzazione", "caldaie", "ristrutturazione bagni"],
    style_name: "Blu Premium Navy Orange",
    palette: "blu navy, arancio, bianco, grigio antracite",
    screen_labels: ["Home", "Servizi", "Preventivo", "Contatti"],
    vibe: "Un premium tecnico in navy e arancio, che trasmette solidità e prontezza d'intervento.",
  },
  {
    slug: "domus-clima",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/domus-clima.webp",
    brand_original: "Domus Clima",
    brand_italian: "Domus Clima Roma",
    sector: "construction",
    sector_keywords: ["climatizzazione", "condizionatori", "pompe di calore", "caldaie"],
    style_name: "Teal Clima Fresh",
    palette: "teal, azzurro, ambra, bianco",
    screen_labels: ["Home", "Servizi", "Preventivo", "Contatti"],
    vibe: "Una freschezza tecnica in teal e azzurro, con tocchi ambra che scaldano l'esperienza.",
  },
  {
    slug: "bmp-piscine",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/bmp-piscine.webp",
    brand_original: "BMP Piscine",
    brand_italian: "BMP Piscine Mediterranee Palermo",
    sector: "construction",
    sector_keywords: ["piscine", "progettazione piscine", "manutenzione", "outdoor luxury"],
    style_name: "Mediterraneo Luxury Aqua",
    palette: "azzurro piscina, bianco calce, turchese, sabbia",
    screen_labels: ["Home", "Servizi", "Realizzazioni", "Preventivo"],
    vibe: "Un lusso mediterraneo acquatico, con azzurri piscina e bianco calce da resort esclusivo.",
  },
  {
    slug: "prato-noleggi",
    ref_url: "https://empireia.lovable.app/lowengeld-refs/prato-noleggi.webp",
    brand_original: "Prato Noleggi",
    brand_italian: "Prato Noleggi Macchine Firenze",
    sector: "construction",
    sector_keywords: ["noleggio piattaforme", "gru", "edilizia in quota", "macchine edili"],
    style_name: "Cantiere Hi-Vis Tecnico",
    palette: "arancio hi-vis, grigio industriale, nero, giallo sicurezza",
    screen_labels: ["Home", "Catalogo", "Lavori", "Preventivo"],
    vibe: "Un'estetica industriale hi-vis, tecnica e diretta, pensata per chi lavora dove altri non arrivano.",
  },
];

export function findLowengeldStyleForSector(sector: string): LowengeldStyle | null {
  const s = sector.toLowerCase();
  for (const style of LOWENGELD_STYLES) {
    if (style.sector_keywords.some((kw) => s.includes(kw) || kw.includes(s))) {
      return style;
    }
  }
  return null;
}
