/**
 * sectorFeatures.ts — Universal + sector-specific features and AI agents
 * Used by DemoSitePage and DemoAdminPage to render complete feature showcases
 */

export interface FeatureItem {
  icon: string;
  title: string;
  desc: string;
  category: "crm" | "booking" | "marketing" | "finance" | "analytics" | "operations" | "ai" | "sector";
}

export interface WorkflowStep {
  icon: string;
  label: string;
  detail: string;
}

export interface AIAgent {
  name: string;
  emoji: string;
  desc: string;
  capabilities: string[];
  isUniversal: boolean;
  hoursPerWeek?: number;
  accuracy?: number;
  category?: string;
  workflow?: WorkflowStep[];
  example?: string;
  result?: string;
}

// ═══════════════════════════════════════════
// UNIVERSAL FEATURES (all 25 sectors)
// ═══════════════════════════════════════════
export const UNIVERSAL_FEATURES: FeatureItem[] = [
  { icon: "Users", title: "CRM Intelligente AI", desc: "Profili completi con storico, preferenze e azioni proattive dell'AI per ogni cliente", category: "crm" },
  { icon: "Filter", title: "Segmentazione Automatica", desc: "Segmenta clienti per comportamento, spesa media, frequenza e valore lifetime", category: "crm" },
  { icon: "Calendar", title: "Booking Online 24/7", desc: "Prenotazioni anche di notte, sync Google Calendar e zero doppie prenotazioni", category: "booking" },
  { icon: "CalendarClock", title: "Agenda Multi-Operatore", desc: "Disponibilità team in tempo reale, gestione sovrapposizioni e pause", category: "booking" },
  { icon: "MessageCircle", title: "Reminder WhatsApp/SMS", desc: "Riduzione no-show del 70% con conferme e promemoria automatici", category: "booking" },
  { icon: "Phone", title: "WhatsApp Business", desc: "Risposte dalla dashboard, messaggi automatici e catalogo integrato", category: "marketing" },
  { icon: "Mail", title: "Email Marketing AI", desc: "Newsletter, promozioni personalizzate, A/B testing e testi scritti dall'AI", category: "marketing" },
  { icon: "Smartphone", title: "SMS Marketing", desc: "Tasso apertura 98%, orari ottimizzati dall'AI per massimo engagement", category: "marketing" },
  { icon: "Bot", title: "Chatbot AI Arianna", desc: "Live chat multilingua 12 lingue, 24/7, prende prenotazioni in autonomia", category: "ai" },
  { icon: "FileText", title: "Fatturazione Elettronica", desc: "XML SDI automatico, conservazione digitale e invio al Sistema di Interscambio", category: "finance" },
  { icon: "CreditCard", title: "Pagamenti Online", desc: "Stripe, PayPal, bonifico con riconciliazione automatica degli incassi", category: "finance" },
  { icon: "FileSignature", title: "Preventivi Digitali", desc: "Firma digitale, conversione automatica in ordine o fattura confermata", category: "finance" },
  { icon: "BarChart3", title: "Dashboard Analytics", desc: "Fatturato, clienti, trend, grafici interattivi aggiornati in tempo reale", category: "analytics" },
  { icon: "Send", title: "Report Settimanali", desc: "Report automatico via email ogni lunedì con KPI e suggerimenti AI", category: "analytics" },
  { icon: "TrendingUp", title: "Previsioni AI", desc: "Trend futuri, stagionalità, picchi di domanda previsti con machine learning", category: "analytics" },
  { icon: "Globe", title: "Landing Page Builder", desc: "Template ottimizzati per il tuo settore con A/B testing integrato", category: "marketing" },
  { icon: "MapPin", title: "Google My Business", desc: "Gestione recensioni, SEO locale e posizionamento su Google Maps", category: "marketing" },
  { icon: "Instagram", title: "Social Media AI", desc: "Post Instagram, Facebook e TikTok in autopilota con AI generativa", category: "marketing" },
  { icon: "UserCog", title: "Gestione Dipendenti", desc: "Turni, ferie, presenze, performance tracking e buste paga digitali", category: "operations" },
  { icon: "Award", title: "Programma Fedeltà", desc: "Wallet digitale, punti, premi, cashback e offerte personalizzate", category: "operations" },
  { icon: "QrCode", title: "QR Code & Tracking", desc: "Link tracciabili, QR per menu, prenotazioni e promozioni misurabili", category: "operations" },
];

// ═══════════════════════════════════════════
// 7 UNIVERSAL AI AGENTS
// ═══════════════════════════════════════════
export const UNIVERSAL_AGENTS: AIAgent[] = [
  { name: "Arianna — AI Concierge", emoji: "🎧", desc: "Receptionist 24/7 in 12 lingue: prende prenotazioni, qualifica lead e risponde a ogni domanda", capabilities: ["Booking automatico", "Lead qualification", "12 lingue", "Risposta istantanea"], isUniversal: true, hoursPerWeek: 168, accuracy: 97, category: "Concierge",
    workflow: [{ icon: "📩", label: "Messaggio in arrivo", detail: "Il cliente scrive via chat, WhatsApp o telefono" }, { icon: "🧠", label: "Analisi AI", detail: "Arianna identifica lingua, intento e urgenza" }, { icon: "📅", label: "Azione", detail: "Prenota, risponde o qualifica il lead in autonomia" }, { icon: "✅", label: "Conferma", detail: "Invia conferma al cliente e notifica al team" }],
    example: "Cliente scrive 'Vorrei prenotare per domani sera' → Arianna verifica disponibilità, propone 20:30, conferma e invia reminder",
    result: "Risparmio: 168h/settimana · Conversion rate: +42%" },
  { name: "Analytics Agent", emoji: "📊", desc: "Business Intelligence con KPI real-time, report automatici e previsioni vendite predittive", capabilities: ["KPI real-time", "Report automatici", "Forecast vendite", "Trend analysis"], isUniversal: true, hoursPerWeek: 15, accuracy: 94, category: "Analytics",
    workflow: [{ icon: "📥", label: "Raccolta dati", detail: "Aggrega dati da vendite, CRM, prenotazioni" }, { icon: "📈", label: "Analisi trend", detail: "Identifica pattern, anomalie e stagionalità" }, { icon: "🔮", label: "Previsioni", detail: "Genera forecast con machine learning" }, { icon: "📧", label: "Report", detail: "Invia report settimanale con suggerimenti" }],
    example: "Lunedì mattina ricevi: 'Fatturato +18% vs settimana scorsa. Il martedì sera è il tuo slot più redditizio (+€340). Suggerimento: promo lunedì per bilanciare.'",
    result: "Risparmio: 15h/settimana · Decisioni data-driven: +94%" },
  { name: "Marketing Agent", emoji: "📣", desc: "Content & Campaigns: post social, newsletter, ads con ROI +240% medio", capabilities: ["Post social AI", "Newsletter", "Ads management", "ROI +240%"], isUniversal: true, hoursPerWeek: 20, accuracy: 91, category: "Marketing",
    workflow: [{ icon: "🎯", label: "Strategia", detail: "Analizza target, trend e competitor" }, { icon: "✍️", label: "Creazione", detail: "Genera testi, immagini e hashtag ottimizzati" }, { icon: "📱", label: "Pubblicazione", detail: "Pubblica su Instagram, Facebook, TikTok" }, { icon: "📊", label: "Ottimizzazione", detail: "Misura risultati e migliora in automatico" }],
    example: "Crea post Instagram con foto del piatto del giorno → Hashtag ottimizzati → Pubblica alle 12:30 (orario migliore) → +340 impression",
    result: "Risparmio: 20h/settimana · ROI medio: +240%" },
  { name: "Sales Agent", emoji: "💼", desc: "Lead scoring, follow-up automatici e sequenze personalizzate per chiudere più vendite", capabilities: ["Lead scoring", "Follow-up auto", "Sequenze email", "Pipeline CRM"], isUniversal: true, hoursPerWeek: 12, accuracy: 89, category: "Vendite",
    workflow: [{ icon: "🎣", label: "Lead capture", detail: "Cattura lead da sito, social e referral" }, { icon: "⭐", label: "Scoring", detail: "Assegna punteggio in base a interesse e budget" }, { icon: "📧", label: "Follow-up", detail: "Sequenza email/WhatsApp personalizzata" }, { icon: "🤝", label: "Chiusura", detail: "Notifica al team quando il lead è pronto" }],
    example: "Nuovo lead da Google → Score 85/100 (alto interesse) → Email personalizzata dopo 2h → Follow-up WhatsApp dopo 24h → Conversione",
    result: "Risparmio: 12h/settimana · Conversion rate: +35%" },
  { name: "Operations Agent", emoji: "⚙️", desc: "Workflow automation: scheduling, assegnazioni e notifiche — risparmia 15h/settimana", capabilities: ["Scheduling AI", "Assegnazioni auto", "Notifiche smart", "15h risparmiate"], isUniversal: true, hoursPerWeek: 15, accuracy: 96, category: "Operazioni",
    workflow: [{ icon: "📋", label: "Task detection", detail: "Identifica attività ricorrenti e bottleneck" }, { icon: "🤖", label: "Automazione", detail: "Crea workflow automatici senza codice" }, { icon: "👥", label: "Assegnazione", detail: "Distribuisce task al team in base a carico" }, { icon: "🔔", label: "Notifiche", detail: "Alert smart solo quando serve" }],
    example: "Nuova prenotazione → Assegna operatore libero → Prepara materiali → Invia conferma al cliente → Reminder 24h prima",
    result: "Risparmio: 15h/settimana · Errori operativi: -72%" },
  { name: "Compliance Agent", emoji: "🛡️", desc: "Normative GDPR, scadenze documenti e compliance automatica per ogni settore", capabilities: ["GDPR audit", "Scadenze auto", "Documenti conformi", "Alert normativi"], isUniversal: true, hoursPerWeek: 8, accuracy: 99, category: "Compliance",
    workflow: [{ icon: "🔍", label: "Scan", detail: "Analizza dati e processi per conformità" }, { icon: "⚠️", label: "Alert", detail: "Identifica scadenze e non-conformità" }, { icon: "📄", label: "Documenti", detail: "Genera documenti GDPR e consensi" }, { icon: "✅", label: "Certificazione", detail: "Report compliance aggiornato" }],
    example: "Scadenza certificato tra 30gg → Alert al responsabile → Prepara documentazione → Reminder settimanali fino al rinnovo",
    result: "Risparmio: 8h/settimana · Compliance: 100%" },
  { name: "Customer Success", emoji: "❤️", desc: "Prevede abbandoni, gestisce NPS e campagne win-back — retention +35%", capabilities: ["Churn prediction", "NPS tracking", "Win-back auto", "Retention +35%"], isUniversal: true, hoursPerWeek: 10, accuracy: 92, category: "Retention",
    workflow: [{ icon: "📉", label: "Monitoring", detail: "Analizza comportamento e frequenza clienti" }, { icon: "🚨", label: "Churn alert", detail: "Identifica clienti a rischio abbandono" }, { icon: "🎁", label: "Win-back", detail: "Invia offerta personalizzata automatica" }, { icon: "📊", label: "NPS", detail: "Misura soddisfazione e migliora servizio" }],
    example: "Cliente non torna da 45gg → Churn risk 78% → Invia sconto 15% personalizzato → Cliente ritorna entro 7gg",
    result: "Risparmio: 10h/settimana · Retention: +35%" },
];

// ═══════════════════════════════════════════
// SECTOR-SPECIFIC FEATURES
// ═══════════════════════════════════════════
export const SECTOR_SPECIFIC_FEATURES: Record<string, FeatureItem[]> = {
  food: [
    { icon: "QrCode", title: "Menu Digitale QR", desc: "Clienti scansionano e ordinano dal tavolo con foto HD e traduzioni", category: "sector" },
    { icon: "ChefHat", title: "Kitchen Display System", desc: "Ordini in tempo reale con priorità, tempi e stato preparazione", category: "sector" },
    { icon: "LayoutGrid", title: "Gestione Tavoli Mappa", desc: "Mappa interattiva tavoli con stati, assegnazioni e coperti", category: "sector" },
    { icon: "Truck", title: "Ordini Delivery", desc: "Gestione delivery, takeaway e ordini WhatsApp in un'unica interfaccia", category: "sector" },
    { icon: "Package", title: "Magazzino Ingredienti", desc: "Inventario con alert scorte, food cost e ordini fornitori automatici", category: "sector" },
    { icon: "Calculator", title: "Food Cost Calculator", desc: "Calcolo costo piatto, margini e suggerimenti pricing ottimale", category: "sector" },
  ],
  ncc: [
    { icon: "Car", title: "Booking Transfer", desc: "Prenotazioni con calcolo automatico prezzo per tratta e veicolo", category: "sector" },
    { icon: "Truck", title: "Gestione Flotta", desc: "Veicoli, scadenze, manutenzione, assicurazioni e revisioni", category: "sector" },
    { icon: "UserCheck", title: "Assegnazione Autisti AI", desc: "L'AI assegna automaticamente l'autista migliore per ogni corsa", category: "sector" },
    { icon: "Navigation", title: "GPS Tracking", desc: "Posizione veicoli in tempo reale e tracking condiviso col cliente", category: "sector" },
    { icon: "TrendingUp", title: "Tariffario Dinamico", desc: "Pricing che si adatta a stagione, domanda e tipo di servizio", category: "sector" },
  ],
  beauty: [
    { icon: "Camera", title: "Portfolio Before/After", desc: "Gallery professionale dei trattamenti per social e sito web", category: "sector" },
    { icon: "ClipboardList", title: "Schede Cliente", desc: "Storico completo trattamenti, allergie, prodotti usati e preferenze", category: "sector" },
    { icon: "Users", title: "Multi-Operatore", desc: "Gestione completa staff con slot individuali e specializzazioni", category: "sector" },
    { icon: "ShoppingBag", title: "Prodotti Retail", desc: "Vendita prodotti in salone con inventario e suggerimenti AI", category: "sector" },
  ],
  healthcare: [
    { icon: "FileText", title: "Cartelle Cliniche", desc: "Storico visite, referti, prescrizioni e allergie in formato digitale", category: "sector" },
    { icon: "Video", title: "Telemedicina", desc: "Videoconsulti integrati con cartella clinica collegata", category: "sector" },
    { icon: "Pill", title: "Prescrizioni Digitali", desc: "Prescrizioni elettroniche con invio diretto in farmacia", category: "sector" },
    { icon: "Shield", title: "Sala Attesa Digitale", desc: "Gestione code virtuali con notifica al paziente via SMS", category: "sector" },
  ],
  retail: [
    { icon: "ShoppingCart", title: "E-commerce", desc: "Negozio online integrato con catalogo, varianti e spedizioni", category: "sector" },
    { icon: "Barcode", title: "Inventario Barcode", desc: "Scansione codici a barre, giacenze in tempo reale e alert scorte", category: "sector" },
    { icon: "Monitor", title: "POS Digitale", desc: "Punto cassa digitale con scontrini e chiusura fiscale", category: "sector" },
    { icon: "Image", title: "Catalogo Premium", desc: "Catalogo prodotti con foto professionali e filtri avanzati", category: "sector" },
  ],
  fitness: [
    { icon: "Ticket", title: "Abbonamenti", desc: "Gestione piani, rinnovi automatici e scadenze con notifiche", category: "sector" },
    { icon: "Calendar", title: "Prenotazione Corsi", desc: "Iscrizione online a lezioni e personal training", category: "sector" },
    { icon: "QrCode", title: "Check-in QR", desc: "Accesso alla palestra con scansione QR dal telefono", category: "sector" },
    { icon: "ClipboardList", title: "Schede Allenamento", desc: "Programmi personalizzati con tracking progressi", category: "sector" },
  ],
  hospitality: [
    { icon: "Building", title: "Gestione Camere", desc: "Disponibilità, tariffe, pulizie e manutenzione camere", category: "sector" },
    { icon: "Globe", title: "Booking Diretto", desc: "Prenotazioni dirette zero commissioni OTA con booking engine", category: "sector" },
    { icon: "Smartphone", title: "Check-in Digitale", desc: "Check-in online con documento e preferenze ospite", category: "sector" },
    { icon: "Sparkles", title: "Concierge Digitale", desc: "Info su servizi, ristoranti ed escursioni per gli ospiti", category: "sector" },
  ],
  beach: [
    { icon: "LayoutGrid", title: "Mappa Ombrelloni", desc: "Mappa interattiva con prenotazione ombrelloni e lettini", category: "sector" },
    { icon: "Calendar", title: "Prenotazioni Online", desc: "Prenotazione posto spiaggia con pagamento anticipato", category: "sector" },
    { icon: "Ticket", title: "Abbonamenti Stagionali", desc: "Gestione abbonamenti, pass e ingressi giornalieri", category: "sector" },
    { icon: "Coffee", title: "Ordini Bar dal Lettino", desc: "I clienti ordinano dal lettino con consegna diretta", category: "sector" },
  ],
  plumber: [
    { icon: "Wrench", title: "Gestione Interventi", desc: "Ticket lavori con stato, foto, preventivi e fatturazione", category: "sector" },
    { icon: "FileSignature", title: "Preventivi dal Cantiere", desc: "Crea preventivi professionali direttamente dal telefono", category: "sector" },
    { icon: "Navigation", title: "GPS Dispatch", desc: "Assegna interventi al tecnico più vicino con AI routing", category: "sector" },
    { icon: "Package", title: "Magazzino Ricambi", desc: "Inventario pezzi di ricambio con alert scorte automatici", category: "sector" },
  ],
  electrician: [
    { icon: "Wrench", title: "Gestione Lavori", desc: "Gestione completa interventi elettrici con tracking stato", category: "sector" },
    { icon: "Shield", title: "Certificazioni DICO/DIRI", desc: "Generazione automatica certificati di conformità", category: "sector" },
    { icon: "Package", title: "Materiali & Forniture", desc: "Inventario materiali con ordini automatici ai fornitori", category: "sector" },
    { icon: "Globe", title: "Portale Clienti", desc: "Area clienti con storico lavori, documenti e fatture", category: "sector" },
  ],
  agriturismo: [
    { icon: "Building", title: "Camere & Alloggi", desc: "Gestione camere, appartamenti e disponibilità stagionale", category: "sector" },
    { icon: "UtensilsCrossed", title: "Ristorante km0", desc: "Menu con prodotti dell'azienda, ordini e prenotazioni", category: "sector" },
    { icon: "Sparkles", title: "Attività Esperienze", desc: "Tour, degustazioni, corsi e attività all'aperto prenotabili", category: "sector" },
    { icon: "ShoppingBag", title: "Shop Prodotti", desc: "E-commerce prodotti locali con spedizione in tutta Italia", category: "sector" },
  ],
  cleaning: [
    { icon: "FileText", title: "Contratti", desc: "Gestione contratti di pulizia con rinnovi e SLA", category: "sector" },
    { icon: "Calendar", title: "Scheduling Operatori", desc: "Pianificazione turni e assegnazione zone automatica", category: "sector" },
    { icon: "ClipboardList", title: "Checklist Qualità", desc: "Checklist digitali con foto e firma del responsabile", category: "sector" },
    { icon: "Ticket", title: "Abbonamenti", desc: "Piani di pulizia ricorrenti con fatturazione automatica", category: "sector" },
  ],
  legal: [
    { icon: "FileText", title: "Gestione Pratiche", desc: "Fascicoli digitali con documenti, scadenze e stato avanzamento", category: "sector" },
    { icon: "Clock", title: "Scadenzario", desc: "Alert automatici per udienze, termini e scadenze processuali", category: "sector" },
    { icon: "Calculator", title: "Parcelle Timesheet", desc: "Tracking ore, calcolo parcella e fatturazione automatica", category: "sector" },
    { icon: "Archive", title: "Archivio Documenti", desc: "Archivio digitale con ricerca full-text e versioning", category: "sector" },
  ],
  accounting: [
    { icon: "Clock", title: "Scadenze Fiscali", desc: "Calendario scadenze con notifiche automatiche a te e ai clienti", category: "sector" },
    { icon: "Globe", title: "Portale Clienti", desc: "Area riservata per upload documenti e consultazione stato", category: "sector" },
    { icon: "FileText", title: "Dichiarazioni", desc: "Gestione dichiarazioni con stato avanzamento e firma digitale", category: "sector" },
    { icon: "BarChart3", title: "Bilanci", desc: "Analisi bilancio, indici e report personalizzati per cliente", category: "sector" },
  ],
  garage: [
    { icon: "Wrench", title: "Gestione Riparazioni", desc: "Accettazione digitale, stato lavori e notifica al cliente", category: "sector" },
    { icon: "Smartphone", title: "Accettazione Digitale", desc: "Check-in veicolo con foto e firma del cliente", category: "sector" },
    { icon: "Package", title: "Magazzino Ricambi", desc: "Inventario pezzi con compatibilità veicoli e ordini OEM", category: "sector" },
    { icon: "Car", title: "Storico Veicoli", desc: "Scheda tecnica per ogni veicolo con storico interventi completo", category: "sector" },
  ],
  photography: [
    { icon: "Camera", title: "Gestione Shooting", desc: "Pianificazione sessioni con brief, location e mood board", category: "sector" },
    { icon: "Image", title: "Portfolio Online", desc: "Gallery professionale con lightbox e protezione watermark", category: "sector" },
    { icon: "Download", title: "Consegna Gallerie", desc: "Link privati per download foto con selezione del cliente", category: "sector" },
    { icon: "FileSignature", title: "Contratti & Liberatorie", desc: "Firma digitale contratti e liberatorie modelle/location", category: "sector" },
  ],
  construction: [
    { icon: "HardHat", title: "Gestione Cantieri", desc: "Dashboard cantieri con SAL, materiali e squadre assegnate", category: "sector" },
    { icon: "Calculator", title: "Computo Metrico", desc: "Computo metrico estimativo con voci di prezzo aggiornate", category: "sector" },
    { icon: "Package", title: "Materiali", desc: "Ordini materiali, bolle di consegna e giacenze cantiere", category: "sector" },
    { icon: "Users", title: "Subappaltatori", desc: "Gestione squadre, subappalti e documentazione sicurezza", category: "sector" },
  ],
  gardening: [
    { icon: "Wrench", title: "Manutenzioni", desc: "Calendario manutenzioni periodiche con storico interventi", category: "sector" },
    { icon: "Ticket", title: "Abbonamenti", desc: "Piani manutenzione stagionale con fatturazione automatica", category: "sector" },
    { icon: "Camera", title: "Before/After Portfolio", desc: "Gallery progetti con confronto prima/dopo per il marketing", category: "sector" },
    { icon: "Calendar", title: "Scheduling Stagionale", desc: "Pianificazione lavori in base a clima e stagione", category: "sector" },
  ],
  veterinary: [
    { icon: "ClipboardList", title: "Cartelle Animali", desc: "Storico visite, vaccinazioni, allergie e terapie per ogni animale", category: "sector" },
    { icon: "Bell", title: "Promemoria Vaccini", desc: "Alert automatici ai proprietari per richiami e check-up", category: "sector" },
    { icon: "Pill", title: "Farmacia", desc: "Gestione farmaci veterinari con prescrizioni e giacenze", category: "sector" },
    { icon: "AlertTriangle", title: "Emergenze", desc: "Gestione urgenze con triage e slot di emergenza dedicati", category: "sector" },
  ],
  tattoo: [
    { icon: "Calendar", title: "Appuntamenti", desc: "Booking con durata stimata, deposito e conferma automatica", category: "sector" },
    { icon: "Image", title: "Portfolio Artisti", desc: "Gallery per artista con stili, categorie e flash disponibili", category: "sector" },
    { icon: "FileSignature", title: "Consensi Digitali", desc: "Firma digitale consensi e liberatorie pre-sessione", category: "sector" },
    { icon: "Heart", title: "Cura Post Tattoo", desc: "Istruzioni aftercare inviate automaticamente via WhatsApp", category: "sector" },
  ],
  childcare: [
    { icon: "Baby", title: "Gestione Bambini", desc: "Schede personali con allergie, contatti e note mediche", category: "sector" },
    { icon: "CheckCircle", title: "Presenze", desc: "Check-in/out con notifica ai genitori in tempo reale", category: "sector" },
    { icon: "BookOpen", title: "Attività Educative", desc: "Pianificazione attività didattiche e ludiche settimanali", category: "sector" },
    { icon: "MessageCircle", title: "Diario Genitori", desc: "Aggiornamenti foto e attività inviati ai genitori ogni giorno", category: "sector" },
  ],
  education: [
    { icon: "BookOpen", title: "Catalogo Corsi", desc: "Corsi con programma, docente, durata e iscrizione online", category: "sector" },
    { icon: "Monitor", title: "LMS", desc: "Piattaforma e-learning con video, quiz e materiali scaricabili", category: "sector" },
    { icon: "Ticket", title: "Iscrizioni", desc: "Iscrizione online con pagamento, fattura e conferma automatica", category: "sector" },
    { icon: "Award", title: "Certificati Automatici", desc: "Generazione attestati al completamento del corso", category: "sector" },
  ],
  events: [
    { icon: "Calendar", title: "Gestione Completa", desc: "Pianificazione eventi con timeline, task e deadline", category: "sector" },
    { icon: "Calculator", title: "Budget", desc: "Gestione budget per voce con tracking spese reali vs preventivo", category: "sector" },
    { icon: "Users", title: "Fornitori", desc: "Database fornitori con preventivi, contratti e rating", category: "sector" },
    { icon: "ClipboardList", title: "Lista Ospiti RSVP", desc: "Inviti digitali con RSVP, tavoli assegnati e menu scelte", category: "sector" },
  ],
  logistics: [
    { icon: "Truck", title: "Spedizioni", desc: "Gestione spedizioni con tracking, bolle e documenti di trasporto", category: "sector" },
    { icon: "Navigation", title: "Tracking GPS", desc: "Posizione mezzi in tempo reale con ETA aggiornato", category: "sector" },
    { icon: "Car", title: "Flotta", desc: "Gestione veicoli commerciali con scadenze e manutenzione", category: "sector" },
    { icon: "Route", title: "Rotte Ottimizzate", desc: "AI ottimizza percorsi per ridurre km, tempo e carburante", category: "sector" },
  ],
  custom: [
    { icon: "Settings", title: "Configuratore Moduli", desc: "Scegli i moduli che ti servono e personalizza ogni dettaglio", category: "sector" },
    { icon: "Workflow", title: "Workflow Builder", desc: "Crea automazioni custom con trigger, condizioni e azioni", category: "sector" },
    { icon: "Code", title: "API Custom", desc: "Integra i tuoi sistemi esistenti con API RESTful documentate", category: "sector" },
    { icon: "Bot", title: "AI Configurator", desc: "Configura il comportamento degli agenti AI per il tuo caso d'uso", category: "sector" },
  ],
};

// ═══════════════════════════════════════════
// SECTOR-SPECIFIC AI AGENTS
// ═══════════════════════════════════════════
export const SECTOR_SPECIFIC_AGENTS: Record<string, AIAgent[]> = {
  food: [
    { name: "Chef AI", emoji: "👨‍🍳", desc: "Ottimizza menu analizzando vendite, margini e trend stagionali", capabilities: ["Analisi menu", "Food cost", "Ottimizzazione margini"], isUniversal: false, accuracy: 93, hoursPerWeek: 12,
      workflow: [{ icon: "📊", label: "Analisi vendite", detail: "Scansiona vendite degli ultimi 30gg per piatto" }, { icon: "💰", label: "Margini", detail: "Calcola food cost e margine per ogni portata" }, { icon: "🍽️", label: "Suggerimenti", detail: "Propone modifiche menu per massimizzare profitto" }, { icon: "📈", label: "Monitoring", detail: "Traccia risultati e affina suggerimenti" }],
      example: "Hai 5kg salmone in scadenza → Suggerisco 'Tartare di salmone' come piatto del giorno → Margine +22%, zero spreco",
      result: "Risparmio: 12h/sett · Margine medio: +18%" },
    { name: "Food Cost Optimizer", emoji: "💰", desc: "Riduce sprechi e ottimizza acquisti ingredienti in base alla domanda", capabilities: ["Demand forecast", "Waste reduction", "Ordini fornitori"], isUniversal: false, accuracy: 91, hoursPerWeek: 10,
      workflow: [{ icon: "📦", label: "Inventario", detail: "Monitora scorte e scadenze in tempo reale" }, { icon: "🔮", label: "Previsione", detail: "Prevede domanda basata su storico e meteo" }, { icon: "🛒", label: "Ordini", detail: "Genera ordini fornitori ottimizzati" }, { icon: "♻️", label: "Anti-spreco", detail: "Suggerisce utilizzi per ingredienti in scadenza" }],
      example: "Domani previsti 40 coperti (meteo pioggia) → Riduci ordine verdure del 30% → Risparmio €85",
      result: "Spreco ridotto: -45% · Risparmio acquisti: €2.400/mese" },
    { name: "Review Manager AI", emoji: "⭐", desc: "Risponde automaticamente alle recensioni e gestisce la reputazione", capabilities: ["Risposte auto", "Sentiment analysis", "Alert negativi"], isUniversal: false, accuracy: 88, hoursPerWeek: 6,
      workflow: [{ icon: "🔔", label: "Alert", detail: "Monitora Google, TripAdvisor, TheFork 24/7" }, { icon: "🧠", label: "Sentiment", detail: "Analizza tono e identifica criticità" }, { icon: "✍️", label: "Risposta", detail: "Genera risposta professionale personalizzata" }, { icon: "📊", label: "Report", detail: "Report settimanale reputazione con trend" }],
      example: "Recensione 3★ 'Attesa lunga ma cibo ottimo' → Risposta empatica in 5 min → Cliente aggiorna a 4★",
      result: "Tempo risposta: -90% · Rating medio: +0.4★" },
    { name: "Kitchen Display AI", emoji: "🖥️", desc: "Gestisce priorità ordini e tempi di preparazione in cucina", capabilities: ["Priorità ordini", "Tempi cottura", "Coordinamento portate"], isUniversal: false, accuracy: 95, hoursPerWeek: 8,
      workflow: [{ icon: "📋", label: "Ordine ricevuto", detail: "Ordine entra nel KDS con tempi stimati" }, { icon: "⏱️", label: "Prioritizzazione", detail: "AI ordina per urgenza e complessità" }, { icon: "🔥", label: "Coordinamento", detail: "Sincronizza uscita portate per tavolo" }, { icon: "✅", label: "Completamento", detail: "Notifica cameriere e traccia tempi" }],
      example: "Tavolo 7: antipasto pronto → AI ritarda secondo di 3min per servizio simultaneo → Cliente soddisfatto",
      result: "Tempi servizio: -25% · Soddisfazione: +32%" },
    { name: "Sommelier AI", emoji: "🍷", desc: "Suggerisce abbinamenti vino-piatto e gestisce la cantina", capabilities: ["Pairing AI", "Gestione cantina", "Upselling vini"], isUniversal: false, accuracy: 90, hoursPerWeek: 5,
      workflow: [{ icon: "🍽️", label: "Piatto ordinato", detail: "Il cliente ordina un piatto dal menu" }, { icon: "🍇", label: "Analisi", detail: "AI analizza sapori e consistenze del piatto" }, { icon: "🍷", label: "Suggerimento", detail: "Propone 3 vini con descrizione e prezzo" }, { icon: "💰", label: "Upsell", detail: "Scontrino medio vini +€12 per tavolo" }],
      example: "Ordinano Tagliata di manzo → AI suggerisce Barolo Riserva 2018 → Accettano → +€38 per tavolo",
      result: "Vendite vini: +28% · Scontrino medio: +€14" },
  ],
  ncc: [
    { name: "Route Optimizer AI", emoji: "🗺️", desc: "Ottimizza percorsi per ridurre tempi e costi carburante", capabilities: ["Route planning", "Traffic prediction", "Fuel savings"], isUniversal: false, accuracy: 94, hoursPerWeek: 14,
      workflow: [{ icon: "📍", label: "Pickup/Dropoff", detail: "Riceve punti di partenza e destinazione" }, { icon: "🛣️", label: "Calcolo rotta", detail: "Analizza traffico, pedaggi e distanza" }, { icon: "⛽", label: "Ottimizzazione", detail: "Sceglie percorso con miglior rapporto tempo/costo" }, { icon: "📱", label: "Notifica", detail: "Invia ETA e tracking al cliente" }],
      example: "Transfer Napoli-Costiera: 3 opzioni → AI sceglie autostrada+statale (risparmio 15min e €8 pedaggio)",
      result: "Carburante: -18% · Tempi: -22%" },
    { name: "Fleet Maintenance AI", emoji: "🔧", desc: "Prevede guasti e pianifica manutenzione preventiva della flotta", capabilities: ["Predictive maintenance", "Alert scadenze", "Cost tracking"], isUniversal: false, accuracy: 96, hoursPerWeek: 8,
      workflow: [{ icon: "🚗", label: "Monitoraggio", detail: "Traccia km, ore motore e condizioni veicolo" }, { icon: "⚠️", label: "Previsione", detail: "Prevede prossima manutenzione necessaria" }, { icon: "📅", label: "Scheduling", detail: "Pianifica intervento in slot a bassa domanda" }, { icon: "📊", label: "Costi", detail: "Traccia costo manutenzione per veicolo" }],
      example: "Mercedes Classe S: 28.500km → Tagliando tra 1.500km → Prenotato officina per giovedì (giorno scarico)",
      result: "Guasti imprevisti: -85% · Costi manutenzione: -30%" },
    { name: "Dynamic Pricing AI", emoji: "💎", desc: "Tariffe che si adattano a stagione, domanda e tipo di servizio", capabilities: ["Surge pricing", "Seasonal rates", "Client segmentation"], isUniversal: false, accuracy: 91, hoursPerWeek: 6,
      workflow: [{ icon: "📊", label: "Analisi domanda", detail: "Monitora booking e stagionalità" }, { icon: "🎯", label: "Segmentazione", detail: "Tariffe diverse per business, turismo, VIP" }, { icon: "💰", label: "Pricing", detail: "Calcola prezzo ottimale per massimizzare ricavi" }, { icon: "📈", label: "A/B Test", detail: "Testa variazioni e ottimizza continuamente" }],
      example: "Alta stagione Agosto: transfer aeroporto +25% → Occupancy rimane al 95% → Revenue +€3.200/mese",
      result: "Revenue per corsa: +22% · Margine: +€1.800/mese" },
    { name: "Driver Assignment AI", emoji: "👔", desc: "Assegna automaticamente l'autista migliore per ogni servizio", capabilities: ["Matching autista-servizio", "Lingua cliente", "Rating optimization"], isUniversal: false, accuracy: 93, hoursPerWeek: 10,
      workflow: [{ icon: "📋", label: "Nuova prenotazione", detail: "Richiesta transfer con dettagli cliente" }, { icon: "🧠", label: "Matching", detail: "Analizza lingua, preferenze, tipo veicolo" }, { icon: "👤", label: "Assegnazione", detail: "Seleziona autista con miglior compatibilità" }, { icon: "📱", label: "Conferma", detail: "Notifica autista e invia dettagli al cliente" }],
      example: "Cliente tedesco VIP → Assegna Marco (parla tedesco, rating 4.9, Mercedes S-Class) → Review 5★",
      result: "Rating medio: +0.3★ · Clienti ricorrenti: +40%" },
  ],
  beauty: [
    { name: "Beauty Advisor AI", emoji: "💄", desc: "Suggerisce trattamenti in base a storico e trend stagionali", capabilities: ["Suggerimenti", "Cross-selling", "Trend beauty"], isUniversal: false, accuracy: 90, hoursPerWeek: 8,
      workflow: [{ icon: "👤", label: "Profilo cliente", detail: "Analizza storico trattamenti e preferenze" }, { icon: "📅", label: "Stagionalità", detail: "Considera trend e stagione corrente" }, { icon: "💡", label: "Suggerimento", detail: "Propone trattamento personalizzato" }, { icon: "📱", label: "Invio", detail: "Invia proposta via WhatsApp con prezzo" }],
      example: "Cliente non fa peeling da 6 mesi → Inverno = ideale → Suggerisce peeling chimico → Prenota +€85",
      result: "Cross-selling: +35% · Scontrino medio: +€28" },
    { name: "Inventory AI", emoji: "📦", desc: "Gestione scorte prodotti con alert riordino automatico", capabilities: ["Stock management", "Auto-reorder", "Expiry tracking"], isUniversal: false, accuracy: 95, hoursPerWeek: 5,
      workflow: [{ icon: "📊", label: "Monitoring", detail: "Traccia giacenze e consumi per prodotto" }, { icon: "⚠️", label: "Alert", detail: "Avvisa quando un prodotto scende sotto soglia" }, { icon: "🛒", label: "Ordine", detail: "Genera ordine al fornitore con quantità ottimale" }, { icon: "📅", label: "Scadenze", detail: "Alert prodotti in scadenza per promozioni" }],
      example: "Crema viso premium: 3 pezzi rimasti → Ordine automatico 12 pezzi → Consegna in 48h",
      result: "Rotture stock: -92% · Scaduti: -75%" },
    { name: "Stylist Scheduler AI", emoji: "✂️", desc: "Ottimizza agenda operatori per massimizzare appuntamenti e pause", capabilities: ["Agenda optimization", "Buffer management", "No-show prediction"], isUniversal: false, accuracy: 92, hoursPerWeek: 7,
      workflow: [{ icon: "📅", label: "Analisi agenda", detail: "Scansiona slot liberi e prenotati" }, { icon: "🧠", label: "Ottimizzazione", detail: "Riorganizza per minimizzare tempi morti" }, { icon: "📱", label: "Suggerimenti", detail: "Propone slot ai clienti in lista d'attesa" }, { icon: "📊", label: "Report", detail: "Tasso utilizzo operatore per ottimizzare turni" }],
      example: "Slot 15:30 libero tra due appuntamenti → Propone piega express (30min) a 3 clienti vicini → Prenotato",
      result: "Utilizzo operatori: +20% · Revenue/giorno: +€120" },
    { name: "Social Beauty AI", emoji: "📸", desc: "Crea contenuti social con before/after e tutorial automatizzati", capabilities: ["Before/After auto", "Reel generation", "Hashtag optimization"], isUniversal: false, accuracy: 87, hoursPerWeek: 10,
      workflow: [{ icon: "📷", label: "Foto", detail: "Scatta before/after dopo il trattamento" }, { icon: "✍️", label: "Content", detail: "Genera caption e hashtag ottimizzati" }, { icon: "📱", label: "Pubblicazione", detail: "Pubblica su Instagram e TikTok" }, { icon: "📊", label: "Analytics", detail: "Misura engagement e replica contenuti top" }],
      example: "Balayage completato → Before/after automatico → Caption 'Trasformazione estate 2025' → 2.400 like",
      result: "Follower: +45%/mese · Nuovi clienti da social: +30%" },
  ],
  healthcare: [
    { name: "Triage AI", emoji: "🩺", desc: "Pre-valutazione sintomi e prioritizzazione urgenze", capabilities: ["Symptom analysis", "Priorità urgenze", "Suggerimenti visite"], isUniversal: false, accuracy: 97, hoursPerWeek: 15,
      workflow: [{ icon: "📱", label: "Richiesta", detail: "Paziente descrive sintomi via chat" }, { icon: "🧠", label: "Analisi", detail: "AI valuta sintomi con database medico" }, { icon: "🚨", label: "Priorità", detail: "Classifica urgenza: verde/giallo/rosso" }, { icon: "📅", label: "Azione", detail: "Prenota visita urgente o suggerisce orario" }],
      example: "Paziente: 'Dolore toracico da 2 ore' → Priorità ROSSA → Slot urgenza in 30min → Notifica al medico",
      result: "Tempi triage: -80% · Urgenze gestite: +95%" },
    { name: "Medical Compliance AI", emoji: "📋", desc: "Verifica conformità normativa e gestione consensi GDPR", capabilities: ["GDPR audit", "Consensi tracking", "Data retention"], isUniversal: false, accuracy: 99, hoursPerWeek: 6,
      workflow: [{ icon: "🔍", label: "Scan", detail: "Verifica tutti i consensi e documenti" }, { icon: "⚠️", label: "Alert", detail: "Identifica consensi scaduti o mancanti" }, { icon: "📄", label: "Genera", detail: "Crea documenti conformi aggiornati" }, { icon: "✅", label: "Conferma", detail: "Certificazione compliance completa" }],
      example: "Consenso privacy paziente X scaduto → Genera nuovo modulo → Invia via email → Firmato digitalmente",
      result: "Compliance: 100% · Sanzioni evitate: €0" },
    { name: "Patient Engagement AI", emoji: "❤️", desc: "Follow-up automatici, reminder screening e comunicazioni personalizzate", capabilities: ["Follow-up auto", "Screening reminder", "Engagement score"], isUniversal: false, accuracy: 92, hoursPerWeek: 8,
      workflow: [{ icon: "📊", label: "Profilo", detail: "Analizza storico visite e screening" }, { icon: "📅", label: "Calendario", detail: "Identifica screening e controlli dovuti" }, { icon: "📱", label: "Comunicazione", detail: "Invia reminder personalizzato via SMS" }, { icon: "📈", label: "Tracking", detail: "Monitora aderenza terapeutica" }],
      example: "Sig.ra Bianchi: mammografia scaduta da 6 mesi → SMS personalizzato → Prenota in 24h",
      result: "Aderenza screening: +45% · Soddisfazione: +38%" },
    { name: "Prescription AI", emoji: "💊", desc: "Assistente prescrizioni con controllo interazioni farmacologiche", capabilities: ["Drug interaction check", "Dosaggio AI", "E-prescription"], isUniversal: false, accuracy: 98, hoursPerWeek: 12,
      workflow: [{ icon: "📋", label: "Visita", detail: "Medico inserisce diagnosi e terapia" }, { icon: "⚠️", label: "Check", detail: "Verifica interazioni con farmaci in corso" }, { icon: "📄", label: "Prescrizione", detail: "Genera prescrizione elettronica conforme" }, { icon: "📱", label: "Invio", detail: "Invia in farmacia e notifica il paziente" }],
      example: "Prescrizione antibiotico → Alert: interazione con anticoagulante in corso → Medico modifica terapia",
      result: "Errori prescrizione: -94% · Tempo: -60%" },
  ],
  retail: [
    { name: "Visual Merchandising AI", emoji: "🎨", desc: "Suggerisce layout vetrina e posizionamento prodotti per massimizzare vendite", capabilities: ["Layout optimization", "Product placement", "Seasonal display"], isUniversal: false, accuracy: 87, hoursPerWeek: 6,
      workflow: [{ icon: "📊", label: "Dati vendite", detail: "Analizza performance prodotti per posizione" }, { icon: "🎯", label: "Hotspot", detail: "Identifica zone ad alto traffico nel negozio" }, { icon: "🖼️", label: "Layout", detail: "Suggerisce riposizionamento prodotti" }, { icon: "📈", label: "Risultati", detail: "Misura impatto sulle vendite" }],
      example: "Prodotto premium in zona C → AI suggerisce zona A (ingresso) → Vendite +45% in 2 settimane",
      result: "Vendite per m²: +28% · Conversione: +15%" },
    { name: "Demand Forecasting AI", emoji: "📈", desc: "Prevede domanda per ogni prodotto e suggerisce quantità ordine", capabilities: ["Demand prediction", "Stock optimization", "Seasonal trends"], isUniversal: false, accuracy: 93, hoursPerWeek: 8,
      workflow: [{ icon: "📦", label: "Storico", detail: "Analizza vendite passate e trend" }, { icon: "🔮", label: "Previsione", detail: "Prevede domanda prossime 4 settimane" }, { icon: "🛒", label: "Ordini", detail: "Genera ordini ottimizzati ai fornitori" }, { icon: "📊", label: "Accuracy", detail: "Confronta previsione vs realtà e migliora" }],
      example: "Black Friday tra 3 settimane → Prevede +180% vendite sneakers → Ordine extra 200 paia → Zero rotture stock",
      result: "Rotture stock: -70% · Overstock: -40%" },
    { name: "Pricing Optimizer AI", emoji: "💲", desc: "Ottimizza prezzi in base a concorrenza, domanda e margini target", capabilities: ["Dynamic pricing", "Competitor analysis", "Margin optimization"], isUniversal: false, accuracy: 90, hoursPerWeek: 5,
      workflow: [{ icon: "🔍", label: "Competitor", detail: "Monitora prezzi concorrenza in tempo reale" }, { icon: "📊", label: "Analisi", detail: "Calcola elasticità prezzo per prodotto" }, { icon: "💰", label: "Ottimizzazione", detail: "Suggerisce prezzo per max margine" }, { icon: "🏷️", label: "Aggiornamento", detail: "Aggiorna listino e stampa etichette" }],
      example: "Competitor abbassa prezzo -10% su giacca → AI suggerisce: mantieni prezzo ma aggiungi sconto 15% loyalty → Margine preservato",
      result: "Margine: +8% · Competitività: mantenuta" },
    { name: "Loyalty Program AI", emoji: "🎁", desc: "Personalizza premi e offerte per massimizzare retention e scontrino", capabilities: ["Personalized rewards", "Tier management", "Gamification"], isUniversal: false, accuracy: 89, hoursPerWeek: 4,
      workflow: [{ icon: "👤", label: "Profilo", detail: "Analizza storico acquisti del cliente" }, { icon: "🎯", label: "Segmentazione", detail: "Assegna tier e identifica preferenze" }, { icon: "🎁", label: "Offerta", detail: "Genera offerta personalizzata" }, { icon: "📱", label: "Invio", detail: "Push notification con sconto mirato" }],
      example: "Cliente Gold non acquista da 20gg → Sconto 20% sulla sua categoria preferita → Ritorna e spende €180",
      result: "Retention VIP: +42% · Scontrino medio: +€25" },
  ],
  fitness: [
    { name: "Fitness Coach AI", emoji: "🏋️", desc: "Crea schede allenamento personalizzate e monitora progressi", capabilities: ["Workout planning", "Progress tracking", "Nutrition tips"], isUniversal: false, accuracy: 88, hoursPerWeek: 12,
      workflow: [{ icon: "📋", label: "Assessment", detail: "Valuta livello, obiettivi e limitazioni" }, { icon: "🏃", label: "Programma", detail: "Genera scheda personalizzata settimanale" }, { icon: "📊", label: "Tracking", detail: "Monitora progressi e aderenza" }, { icon: "🔄", label: "Adattamento", detail: "Modifica programma in base ai risultati" }],
      example: "Marco, obiettivo: massa muscolare → Scheda 4gg/sett con progressione carico → +3kg massa in 8 settimane",
      result: "Retention iscritti: +35% · Soddisfazione: 4.8/5" },
    { name: "Retention Gym AI", emoji: "🔄", desc: "Prevede abbandoni e attiva campagne di retention personalizzate", capabilities: ["Churn prediction", "Re-engagement", "Offerte personalizzate"], isUniversal: false, accuracy: 91, hoursPerWeek: 6,
      workflow: [{ icon: "📉", label: "Monitoring", detail: "Traccia frequenza accessi di ogni iscritto" }, { icon: "🚨", label: "Alert", detail: "Identifica iscritti a rischio abbandono" }, { icon: "🎁", label: "Intervento", detail: "Invia offerta personalizzata o invito PT" }, { icon: "📊", label: "Follow-up", detail: "Verifica ritorno e aggiorna profilo" }],
      example: "Sara: 0 accessi in 3 settimane → Rischio 82% → Offerta PT gratuita → Torna e rinnova abbonamento",
      result: "Churn: -40% · Rinnovi: +28%" },
    { name: "Class Optimizer AI", emoji: "📅", desc: "Ottimizza orari e capienza corsi basandosi sui dati di partecipazione", capabilities: ["Demand analysis", "Schedule optimization", "Instructor matching"], isUniversal: false, accuracy: 93, hoursPerWeek: 5,
      workflow: [{ icon: "📊", label: "Analisi", detail: "Studia partecipazione per orario e tipo corso" }, { icon: "🎯", label: "Ottimizzazione", detail: "Sposta corsi scarsi in slot migliori" }, { icon: "👥", label: "Matching", detail: "Assegna istruttore più richiesto" }, { icon: "📱", label: "Notifica", detail: "Avvisa iscritti dei nuovi orari" }],
      example: "Yoga martedì 14:00: 3 iscritti → Spostato a giovedì 19:00 → 18 iscritti → Sala piena",
      result: "Occupancy corsi: +45% · Revenue corsi: +€2.100/mese" },
    { name: "Nutrition AI", emoji: "🥗", desc: "Piani alimentari personalizzati integrati con gli obiettivi fitness", capabilities: ["Meal planning", "Macro tracking", "Recipe suggestions"], isUniversal: false, accuracy: 86, hoursPerWeek: 8,
      workflow: [{ icon: "🎯", label: "Obiettivo", detail: "Definisce target calorico e macro" }, { icon: "🍽️", label: "Piano", detail: "Genera piano alimentare settimanale" }, { icon: "📱", label: "Tracking", detail: "App per logging pasti quotidiano" }, { icon: "🔄", label: "Aggiustamento", detail: "Adatta piano in base a risultati e feedback" }],
      example: "Obiettivo: definizione → Piano 2.200kcal, 40% proteine → Menu settimanale con ricette e lista spesa",
      result: "Risultati clienti: +55% · Upsell piani premium: +€800/mese" },
  ],
  hospitality: [
    { name: "Revenue Management AI", emoji: "💰", desc: "Ottimizza tariffe camere in base a occupancy, stagione e competitor", capabilities: ["Dynamic pricing", "Occupancy forecast", "RevPAR optimization"], isUniversal: false, accuracy: 94, hoursPerWeek: 10,
      workflow: [{ icon: "📊", label: "Analisi", detail: "Monitora occupancy e tariffe competitor" }, { icon: "🔮", label: "Forecast", detail: "Prevede domanda prossimi 30-90 giorni" }, { icon: "💰", label: "Pricing", detail: "Aggiorna tariffe per massimizzare RevPAR" }, { icon: "📈", label: "Risultati", detail: "Traccia revenue e confronta con budget" }],
      example: "Occupancy 60% per prossimo weekend → AI abbassa tariffa del 15% → Occupancy sale a 92% → RevPAR +€18",
      result: "RevPAR: +22% · Revenue annuo: +€45.000" },
    { name: "Guest Experience AI", emoji: "🌟", desc: "Personalizza il soggiorno in base a preferenze e storico ospite", capabilities: ["Guest profiling", "Upsell suggestions", "Review management"], isUniversal: false, accuracy: 90, hoursPerWeek: 12,
      workflow: [{ icon: "👤", label: "Check-in", detail: "Recupera profilo e preferenze ospite" }, { icon: "🎯", label: "Personalizzazione", detail: "Prepara camera con preferenze note" }, { icon: "💡", label: "Upsell", detail: "Suggerisce upgrade, spa, ristorante" }, { icon: "⭐", label: "Feedback", detail: "Raccoglie feedback e gestisce review" }],
      example: "Ospite ricorrente: preferisce cuscino in piuma e prosecco → Camera preparata → Accoglienza wow → Review 5★",
      result: "Upsell revenue: +35% · Guest satisfaction: +0.5★" },
    { name: "Housekeeping AI", emoji: "🛏️", desc: "Ottimizza pulizie camere e gestione biancheria in tempo reale", capabilities: ["Room status tracking", "Staff optimization", "Laundry management"], isUniversal: false, accuracy: 93, hoursPerWeek: 8,
      workflow: [{ icon: "🚪", label: "Check-out", detail: "Rileva check-out e aggiorna stato camera" }, { icon: "👥", label: "Assegnazione", detail: "Assegna pulizia all'addetto più vicino" }, { icon: "📋", label: "Checklist", detail: "Checklist digitale con foto verifica" }, { icon: "✅", label: "Ready", detail: "Camera pronta per nuovo check-in" }],
      example: "Check-out camera 305 → Assegnata a Maria (piano 3) → Pulizia completata in 28min → Pronta per check-in 14:00",
      result: "Tempo pulizia: -20% · Camere pronte: +30 min prima" },
  ],
  beach: [
    { name: "Beach Optimizer AI", emoji: "🏖️", desc: "Ottimizza disposizione ombrelloni e pricing in base a meteo e domanda", capabilities: ["Weather-based pricing", "Layout optimization", "Demand forecast"], isUniversal: false, accuracy: 89, hoursPerWeek: 6,
      workflow: [{ icon: "🌤️", label: "Meteo", detail: "Monitora previsioni meteo 7 giorni" }, { icon: "📊", label: "Domanda", detail: "Prevede affluenza basata su storico e meteo" }, { icon: "💰", label: "Pricing", detail: "Adatta tariffe a domanda e giornata" }, { icon: "🗺️", label: "Layout", detail: "Ottimizza disposizione ombrelloni per comfort" }],
      example: "Domenica sole 34°C → Previsti 95% occupancy → Tariffa +20% → Revenue giornata: €3.200 vs €2.400 media",
      result: "Revenue/stagione: +25% · Occupancy: ottimizzata" },
    { name: "F&B Beach AI", emoji: "🍹", desc: "Gestione ordini bar da ombrellone con suggerimenti basati su meteo", capabilities: ["Smart menu", "Delivery optimization", "Weather-based promos"], isUniversal: false, accuracy: 87, hoursPerWeek: 8,
      workflow: [{ icon: "📱", label: "Ordine", detail: "Cliente ordina dal lettino via QR" }, { icon: "🌡️", label: "Smart menu", detail: "Suggerisce in base a meteo e ora" }, { icon: "🏃", label: "Routing", detail: "Ottimizza percorso cameriere per zona" }, { icon: "📊", label: "Analytics", detail: "Analisi vendite per zona e orario" }],
      example: "36°C ore 14:00 → Suggerisce granita e frutta fresca → Ombrellone 42: ordine €28 → Servito in 4min",
      result: "Vendite bar: +40% · Tempo servizio: -35%" },
    { name: "Season Pass AI", emoji: "🎫", desc: "Gestisce abbonamenti stagionali con rinnovi e upgrade automatici", capabilities: ["Pass management", "Auto-renewal", "Upgrade suggestions"], isUniversal: false, accuracy: 91, hoursPerWeek: 4,
      workflow: [{ icon: "📅", label: "Scadenza", detail: "Monitora scadenze abbonamenti" }, { icon: "📱", label: "Reminder", detail: "Invia promemoria rinnovo personalizzato" }, { icon: "⬆️", label: "Upgrade", detail: "Suggerisce upgrade basato su utilizzo" }, { icon: "💳", label: "Pagamento", detail: "Rinnovo con pagamento online" }],
      example: "Famiglia Rossi: pass settimanale → Usano 5gg/7 → Suggerisce mensile (-30%) → Upgrade accettato",
      result: "Rinnovi: +55% · Revenue stagionale: +18%" },
  ],
  plumber: [
    { name: "Emergency Dispatch AI", emoji: "🚨", desc: "Assegna urgenze al tecnico più vicino con routing ottimale", capabilities: ["GPS dispatch", "Priority triage", "SLA tracking"], isUniversal: false, accuracy: 95, hoursPerWeek: 12,
      workflow: [{ icon: "📞", label: "Chiamata", detail: "Cliente segnala emergenza idraulica" }, { icon: "🗺️", label: "GPS", detail: "Localizza tecnici disponibili nella zona" }, { icon: "👤", label: "Assegnazione", detail: "Assegna al tecnico più vicino e qualificato" }, { icon: "📱", label: "ETA", detail: "Comunica tempo arrivo stimato al cliente" }],
      example: "Tubo rotto a Via Roma → Tecnico Mario a 2.3km → Assegnato → Arrivo in 18min → Problema risolto",
      result: "Tempo risposta: -60% · SLA rispettati: 98%" },
    { name: "Preventive Maintenance AI", emoji: "🔧", desc: "Pianifica manutenzioni preventive basate su storico e stagione", capabilities: ["Maintenance calendar", "Client reminders", "Parts forecast"], isUniversal: false, accuracy: 92, hoursPerWeek: 6,
      workflow: [{ icon: "📊", label: "Storico", detail: "Analizza interventi passati per indirizzo" }, { icon: "📅", label: "Piano", detail: "Genera calendario manutenzioni preventive" }, { icon: "📱", label: "Reminder", detail: "Invia promemoria al cliente" }, { icon: "🛒", label: "Materiali", detail: "Pre-ordina ricambi necessari" }],
      example: "Condominio Via Verdi: ultimo controllo caldaia 11 mesi fa → Reminder → 8 condomini prenotano → Fatturato €2.400",
      result: "Interventi preventivi: +120% · Revenue ricorrente: +€3.000/mese" },
    { name: "Quote Builder AI", emoji: "📝", desc: "Genera preventivi professionali dal cantiere in 2 minuti", capabilities: ["Auto-pricing", "Material database", "Digital signature"], isUniversal: false, accuracy: 90, hoursPerWeek: 8,
      workflow: [{ icon: "📷", label: "Foto", detail: "Scatta foto del problema sul posto" }, { icon: "🧠", label: "Analisi", detail: "AI stima lavoro, materiali e tempo" }, { icon: "📄", label: "Preventivo", detail: "Genera PDF professionale con prezzi" }, { icon: "✍️", label: "Firma", detail: "Cliente firma digitale e conferma" }],
      example: "Sostituzione miscelatore → Foto → AI: materiale €45 + manodopera €80 → Preventivo PDF → Firmato in 30sec",
      result: "Conversione preventivi: +38% · Tempo creazione: -85%" },
  ],
  electrician: [
    { name: "Electrical Compliance AI", emoji: "⚡", desc: "Genera certificazioni DICO/DIRI e verifica conformità normativa", capabilities: ["Auto-certification", "Compliance check", "Document generation"], isUniversal: false, accuracy: 98, hoursPerWeek: 10,
      workflow: [{ icon: "📋", label: "Lavoro completato", detail: "Tecnico registra tipo intervento" }, { icon: "🔍", label: "Verifica", detail: "AI verifica conformità con normativa CEI" }, { icon: "📄", label: "Certificato", detail: "Genera DICO/DIRI compilata automaticamente" }, { icon: "📧", label: "Invio", detail: "Invia a cliente e archivio digitale" }],
      example: "Impianto nuovo appartamento → Dati inseriti → DICO generata in 3min con tutti i riferimenti normativi",
      result: "Tempo documentazione: -80% · Conformità: 100%" },
    { name: "Quote Calculator AI", emoji: "🧮", desc: "Calcola preventivi basati su tipo di lavoro, materiali e tempistiche", capabilities: ["Auto-quoting", "Material pricing", "Time estimation"], isUniversal: false, accuracy: 91, hoursPerWeek: 7,
      workflow: [{ icon: "📏", label: "Sopralluogo", detail: "Misura e valuta tipo di intervento" }, { icon: "📦", label: "Materiali", detail: "Calcola materiali necessari con prezzi aggiornati" }, { icon: "⏱️", label: "Tempistiche", detail: "Stima ore di lavoro per complessità" }, { icon: "📄", label: "Preventivo", detail: "PDF professionale con dettaglio voci" }],
      example: "Rifacimento impianto 80m² → 450m cavo, 28 punti luce, 3 quadri → Preventivo €4.800 → Accettato",
      result: "Conversione: +42% · Precisione stime: 94%" },
    { name: "Safety Inspector AI", emoji: "🛡️", desc: "Verifica sicurezza impianti esistenti e genera report ispettivi", capabilities: ["Safety audit", "Risk assessment", "Inspection reports"], isUniversal: false, accuracy: 96, hoursPerWeek: 5,
      workflow: [{ icon: "🔍", label: "Ispezione", detail: "Checklist guidata per verifica impianto" }, { icon: "⚠️", label: "Rischi", detail: "Identifica non-conformità e rischi" }, { icon: "📄", label: "Report", detail: "Genera report ispettivo dettagliato" }, { icon: "📧", label: "Comunicazione", detail: "Invia report a cliente con raccomandazioni" }],
      example: "Verifica impianto condominio → 3 non-conformità trovate → Report con foto e soluzioni → Preventivo lavori €1.200",
      result: "Ispezioni/mese: +200% · Revenue extra: €2.500/mese" },
  ],
  agriturismo: [
    { name: "Agri-Tourism Experience AI", emoji: "🌾", desc: "Suggerisce esperienze e pacchetti in base a stagione e profilo ospite", capabilities: ["Package creation", "Seasonal suggestions", "Experience curation"], isUniversal: false, accuracy: 88, hoursPerWeek: 8,
      workflow: [{ icon: "👤", label: "Profilo", detail: "Analizza tipologia ospite e interessi" }, { icon: "🌿", label: "Stagione", detail: "Considera attività disponibili per periodo" }, { icon: "📦", label: "Pacchetto", detail: "Crea pacchetto esperienziale personalizzato" }, { icon: "📱", label: "Proposta", detail: "Invia proposta con prezzo e disponibilità" }],
      example: "Coppia romantica ad ottobre → Pacchetto vendemmia: raccolta uva + degustazione + cena km0 → €120/coppia",
      result: "Revenue esperienze: +45% · Guest satisfaction: 4.9/5" },
    { name: "Farm-to-Table AI", emoji: "🥗", desc: "Ottimizza menu ristorante in base a prodotti disponibili dall'azienda", capabilities: ["Menu planning", "Product availability", "Seasonal recipes"], isUniversal: false, accuracy: 90, hoursPerWeek: 6,
      workflow: [{ icon: "🌱", label: "Raccolto", detail: "Monitora prodotti disponibili dall'orto" }, { icon: "🍽️", label: "Menu", detail: "Genera menu con ingredienti di stagione" }, { icon: "💰", label: "Costi", detail: "Calcola food cost quasi zero per prodotti propri" }, { icon: "📸", label: "Marketing", detail: "Foto e descrizioni km0 per social" }],
      example: "50kg pomodori San Marzano maturi → Menu speciale: bruschetta, pappa al pomodoro, sugo fresco → Food cost €0.30",
      result: "Food cost: -60% · Storytelling km0: +clienti 35%" },
  ],
  cleaning: [
    { name: "Cleaning Scheduler AI", emoji: "🧹", desc: "Pianifica turni ottimali e assegna zone in base a competenze e carico", capabilities: ["Shift planning", "Zone assignment", "Workload balancing"], isUniversal: false, accuracy: 93, hoursPerWeek: 10,
      workflow: [{ icon: "📋", label: "Contratti", detail: "Mappa tutti i contratti attivi e frequenze" }, { icon: "👥", label: "Staff", detail: "Verifica disponibilità e competenze" }, { icon: "🗺️", label: "Routing", detail: "Ottimizza percorsi per minimizzare spostamenti" }, { icon: "📱", label: "Notifica", detail: "Invia turno con dettagli al team" }],
      example: "5 cantieri lunedì → Ottimizza percorso: A→B→C→D→E (vs A→D→B→E→C) → Risparmio 45min e €12 benzina",
      result: "Efficienza turni: +30% · Costi trasporto: -25%" },
    { name: "Quality Control AI", emoji: "✅", desc: "Analizza checklist e foto per verificare standard di qualità", capabilities: ["Photo analysis", "Quality scoring", "Issue detection"], isUniversal: false, accuracy: 91, hoursPerWeek: 6,
      workflow: [{ icon: "📸", label: "Foto", detail: "Operatore scatta foto a fine pulizia" }, { icon: "🧠", label: "Analisi", detail: "AI valuta pulizia da foto con score 0-100" }, { icon: "⚠️", label: "Alert", detail: "Segnala zone sotto lo standard" }, { icon: "📊", label: "Report", detail: "Report qualità mensile per cliente" }],
      example: "Ufficio Via Dante: foto bagno → Score 72/100 (sotto soglia 85) → Alert → Ripulitura in 20min → Score 95",
      result: "Reclami: -65% · Soddisfazione clienti: 4.7/5" },
  ],
  legal: [
    { name: "Legal Research AI", emoji: "📚", desc: "Ricerca giurisprudenza e normativa pertinente al caso", capabilities: ["Case research", "Precedent analysis", "Normative updates"], isUniversal: false, accuracy: 89, hoursPerWeek: 15,
      workflow: [{ icon: "📝", label: "Query", detail: "Avvocato descrive il caso e la questione" }, { icon: "🔍", label: "Ricerca", detail: "AI cerca in database giurisprudenziale" }, { icon: "📄", label: "Risultati", detail: "Presenta sentenze e articoli pertinenti" }, { icon: "📋", label: "Sintesi", detail: "Genera sintesi con riferimenti normativi" }],
      example: "Questione: responsabilità per vizio occulto → 12 sentenze pertinenti → Sintesi con orientamento prevalente",
      result: "Tempo ricerca: -75% · Qualità argomentazioni: +40%" },
    { name: "Legal Deadline AI", emoji: "⏰", desc: "Monitora tutte le scadenze processuali e genera alert prioritizzati", capabilities: ["Deadline tracking", "Priority alerts", "Calendar sync"], isUniversal: false, accuracy: 99, hoursPerWeek: 5,
      workflow: [{ icon: "📅", label: "Calendario", detail: "Importa tutte le scadenze processuali" }, { icon: "🔔", label: "Alert", detail: "Notifiche progressive: 30gg, 7gg, 1gg" }, { icon: "🚨", label: "Urgenze", detail: "Alert rosso per scadenze imminenti" }, { icon: "📊", label: "Dashboard", detail: "Vista complessiva scadenze per avvocato" }],
      example: "Termine deposito memorie: 15 marzo → Alert a 30gg, 7gg, 3gg, 1gg → Mai persa una scadenza",
      result: "Scadenze perse: 0% · Stress team: -50%" },
    { name: "Client Intake AI", emoji: "📝", desc: "Qualifica nuovi clienti, raccoglie informazioni e prepara il fascicolo", capabilities: ["Client screening", "Document collection", "Case assessment"], isUniversal: false, accuracy: 87, hoursPerWeek: 8,
      workflow: [{ icon: "📱", label: "Primo contatto", detail: "Cliente compila form o scrive via chat" }, { icon: "🧠", label: "Screening", detail: "AI valuta tipo di caso e competenza" }, { icon: "📋", label: "Documenti", detail: "Richiede documenti necessari automaticamente" }, { icon: "📁", label: "Fascicolo", detail: "Crea fascicolo digitale pronto per l'avvocato" }],
      example: "Nuovo contatto: separazione consensuale → Checklist documenti inviata → 80% documenti raccolti prima del primo incontro",
      result: "Tempo intake: -60% · Preparazione fascicoli: +80%" },
  ],
  accounting: [
    { name: "Tax Calendar AI", emoji: "📅", desc: "Calendario fiscale personalizzato con scadenze per ogni cliente", capabilities: ["Tax deadlines", "Client notifications", "Regulatory updates"], isUniversal: false, accuracy: 98, hoursPerWeek: 8,
      workflow: [{ icon: "📋", label: "Profilo cliente", detail: "Mappa regime fiscale e obblighi" }, { icon: "📅", label: "Calendario", detail: "Genera scadenziario personalizzato" }, { icon: "📱", label: "Alert", detail: "Notifica cliente e commercialista" }, { icon: "✅", label: "Conferma", detail: "Traccia adempimento completato" }],
      example: "Liquidazione IVA trimestrale → Alert a 15gg → Documenti raccolti → Invio F24 in tempo → Zero sanzioni",
      result: "Scadenze rispettate: 100% · Sanzioni: €0" },
    { name: "Document Classifier AI", emoji: "📄", desc: "Classifica automaticamente documenti ricevuti dai clienti", capabilities: ["Auto-classification", "OCR extraction", "Filing automation"], isUniversal: false, accuracy: 94, hoursPerWeek: 12,
      workflow: [{ icon: "📧", label: "Ricezione", detail: "Documento arriva via email o upload" }, { icon: "🧠", label: "OCR", detail: "Estrae testo e dati dal documento" }, { icon: "🏷️", label: "Classificazione", detail: "Categorizza: fattura, ricevuta, contratto..." }, { icon: "📁", label: "Archiviazione", detail: "Archivia nel fascicolo corretto del cliente" }],
      example: "Cliente invia 47 documenti misti → AI classifica: 23 fatture, 12 ricevute, 8 estratti conto, 4 contratti → Tutto archiviato",
      result: "Tempo classificazione: -90% · Errori filing: -95%" },
    { name: "Tax Advisory AI", emoji: "💡", desc: "Suggerisce ottimizzazioni fiscali basate sul profilo del cliente", capabilities: ["Tax optimization", "Deduction finder", "Compliance check"], isUniversal: false, accuracy: 91, hoursPerWeek: 6,
      workflow: [{ icon: "📊", label: "Analisi", detail: "Esamina situazione fiscale del cliente" }, { icon: "🔍", label: "Opportunità", detail: "Identifica deduzioni e agevolazioni applicabili" }, { icon: "💰", label: "Simulazione", detail: "Calcola risparmio fiscale potenziale" }, { icon: "📄", label: "Report", detail: "Presenta opzioni con pro/contro" }],
      example: "SRL con utili €80k → Suggerisce: regime patent box su software → Risparmio IRES €12.000/anno",
      result: "Risparmio medio clienti: €3.200/anno · Soddisfazione: +45%" },
  ],
  garage: [
    { name: "Diagnostic AI", emoji: "🔍", desc: "Analisi sintomi veicolo e suggerimento diagnosi probabile", capabilities: ["Symptom analysis", "Diagnosis suggestion", "Parts identification"], isUniversal: false, accuracy: 88, hoursPerWeek: 10,
      workflow: [{ icon: "🚗", label: "Sintomo", detail: "Meccanico descrive rumore/problema" }, { icon: "🧠", label: "Database", detail: "AI confronta con milioni di casi" }, { icon: "🔍", label: "Diagnosi", detail: "Suggerisce 3 cause probabili con %" }, { icon: "📦", label: "Ricambi", detail: "Identifica pezzi necessari e prezzi" }],
      example: "Rumore metallico in frenata → 87% pastiglie, 10% disco, 3% pinza → Verifica conferma pastiglie → Riparazione rapida",
      result: "Tempo diagnosi: -50% · Precisione: 88%" },
    { name: "Parts Procurement AI", emoji: "📦", desc: "Trova ricambi migliori al miglior prezzo da fornitori verificati", capabilities: ["Part search", "Price comparison", "Supplier rating"], isUniversal: false, accuracy: 92, hoursPerWeek: 6,
      workflow: [{ icon: "🔍", label: "Identificazione", detail: "Identifica codice OEM del ricambio" }, { icon: "💰", label: "Confronto", detail: "Compara prezzi da 5+ fornitori" }, { icon: "⭐", label: "Rating", detail: "Considera qualità e tempi consegna" }, { icon: "🛒", label: "Ordine", detail: "Ordine automatico al miglior fornitore" }],
      example: "Filtro olio BMW 320d → 5 fornitori confrontati → Miglior prezzo €12.50 (vs €18 listino) → Consegna domani",
      result: "Costi ricambi: -25% · Tempi approvvigionamento: -40%" },
    { name: "Service Reminder AI", emoji: "🔔", desc: "Invia promemoria tagliandi e revisioni basati su km e scadenze", capabilities: ["Km tracking", "Service intervals", "Auto-reminders"], isUniversal: false, accuracy: 96, hoursPerWeek: 4,
      workflow: [{ icon: "📊", label: "Database", detail: "Traccia km e scadenze per veicolo" }, { icon: "📅", label: "Previsione", detail: "Calcola prossimo tagliando/revisione" }, { icon: "📱", label: "SMS", detail: "Invia reminder personalizzato al cliente" }, { icon: "📋", label: "Prenotazione", detail: "Link diretto per prenotare l'intervento" }],
      example: "Fiat 500 Marco: revisione tra 45gg → SMS → Marco prenota online → Slot riempito",
      result: "Clienti ricorrenti: +55% · Revenue manutenzione: +€2.800/mese" },
  ],
  photography: [
    { name: "Creative Brief AI", emoji: "🎯", desc: "Genera brief creativi basati su tipo di shooting e stile richiesto", capabilities: ["Brief generation", "Mood board", "Style matching"], isUniversal: false, accuracy: 85, hoursPerWeek: 6,
      workflow: [{ icon: "📝", label: "Richiesta", detail: "Cliente descrive tipo di shooting" }, { icon: "🎨", label: "Mood board", detail: "AI genera mood board con riferimenti" }, { icon: "📋", label: "Brief", detail: "Crea brief completo: location, luce, outfit" }, { icon: "📧", label: "Invio", detail: "Invia brief al cliente per approvazione" }],
      example: "Shooting matrimonio boho → Mood board con 12 ref → Brief: golden hour, location oliveto, bouquet wildflowers",
      result: "Tempo briefing: -70% · Soddisfazione clienti: +30%" },
    { name: "Editing Workflow AI", emoji: "🖼️", desc: "Ottimizza il workflow di post-produzione e suggerisce editing", capabilities: ["Batch processing", "Style consistency", "Delivery tracking"], isUniversal: false, accuracy: 87, hoursPerWeek: 15,
      workflow: [{ icon: "📸", label: "Import", detail: "Importa RAW e seleziona le migliori" }, { icon: "🎨", label: "Preset", detail: "Applica preset coerente con lo stile" }, { icon: "✂️", label: "Fine-tuning", detail: "Suggerisce crop e ritocchi specifici" }, { icon: "📦", label: "Delivery", detail: "Prepara gallery con link download" }],
      example: "Shooting 800 foto → AI seleziona top 120 → Preset 'Film Grain' applicato → Gallery pronta in 2h vs 8h",
      result: "Tempo post-produzione: -65% · Consegne puntuali: 100%" },
    { name: "Client Gallery AI", emoji: "🖥️", desc: "Crea gallerie online con protezione, selezione e ordini stampa", capabilities: ["Gallery creation", "Watermark protection", "Print orders"], isUniversal: false, accuracy: 92, hoursPerWeek: 4,
      workflow: [{ icon: "📤", label: "Upload", detail: "Carica foto editate nella gallery" }, { icon: "🔒", label: "Protezione", detail: "Watermark e link protetto da password" }, { icon: "❤️", label: "Selezione", detail: "Cliente seleziona preferite per album" }, { icon: "🖨️", label: "Ordini", detail: "Stampe e album ordinabili online" }],
      example: "Gallery matrimonio Rossi → 250 foto → Sposi selezionano 80 per album → Ordine album €350 direttamente online",
      result: "Revenue stampe: +45% · Esperienza cliente: premium" },
  ],
  construction: [
    { name: "Project Timeline AI", emoji: "📊", desc: "Genera Gantt automatici e monitora avanzamento cantiere", capabilities: ["Gantt auto", "Milestone tracking", "Delay prediction"], isUniversal: false, accuracy: 90, hoursPerWeek: 12,
      workflow: [{ icon: "📋", label: "Progetto", detail: "Inserisci fasi, durate e dipendenze" }, { icon: "📊", label: "Gantt", detail: "AI genera timeline con percorso critico" }, { icon: "📱", label: "Tracking", detail: "Aggiornamenti giornalieri dal cantiere" }, { icon: "⚠️", label: "Alert", detail: "Prevede ritardi e suggerisce soluzioni" }],
      example: "Ritardo murature di 3gg → AI ricalcola: sposta impianti elettrici avanti → Recupero 2gg → Consegna in tempo",
      result: "Ritardi: -45% · Rispetto deadline: +60%" },
    { name: "Material Cost AI", emoji: "💰", desc: "Stima costi materiali e trova fornitori al miglior prezzo", capabilities: ["Cost estimation", "Supplier comparison", "Budget tracking"], isUniversal: false, accuracy: 92, hoursPerWeek: 8,
      workflow: [{ icon: "📦", label: "Lista", detail: "Genera lista materiali da progetto" }, { icon: "💰", label: "Preventivi", detail: "Richiede preventivi a 5+ fornitori" }, { icon: "📊", label: "Confronto", detail: "Compara qualità, prezzo e tempi" }, { icon: "🛒", label: "Ordine", detail: "Ordina e traccia consegne" }],
      example: "500m² pavimentazione → 4 fornitori → Migliore: €28/m² (vs €35 media) → Risparmio €3.500 su lotto",
      result: "Costi materiali: -20% · Budget rispettato: 95% casi" },
    { name: "Safety Compliance AI", emoji: "⛑️", desc: "Verifica conformità sicurezza cantiere e genera documenti obbligatori", capabilities: ["Safety audit", "Document generation", "Training tracking"], isUniversal: false, accuracy: 97, hoursPerWeek: 6,
      workflow: [{ icon: "📋", label: "Checklist", detail: "Verifica DPI, segnaletica, estintori" }, { icon: "📸", label: "Evidenze", detail: "Foto documentazione stato cantiere" }, { icon: "📄", label: "Documenti", detail: "Genera POS, DUVRI aggiornati" }, { icon: "✅", label: "Certificazione", detail: "Cantiere conforme per ispezione" }],
      example: "Ispezione ASL annunciata → AI verifica: 2 DPI mancanti, segnaletica incompleta → Corretto in 2h → Ispezione superata",
      result: "Sanzioni: €0 · Conformità: 100%" },
  ],
  gardening: [
    { name: "Garden Planner AI", emoji: "🌿", desc: "Progetta giardini in base a clima, terreno e preferenze del cliente", capabilities: ["Garden design", "Plant selection", "Season planning"], isUniversal: false, accuracy: 86, hoursPerWeek: 8,
      workflow: [{ icon: "📏", label: "Sopralluogo", detail: "Misure, esposizione, tipo terreno" }, { icon: "🌱", label: "Piante", detail: "Seleziona specie adatte al contesto" }, { icon: "🎨", label: "Progetto", detail: "Genera layout con render 3D" }, { icon: "💰", label: "Preventivo", detail: "Dettaglio costi piante, materiali, lavoro" }],
      example: "Giardino 200m², zona ombra parziale → AI: 12 piante mediterranee, irrigazione a goccia → Preventivo €3.800",
      result: "Conversione progetti: +40% · Soddisfazione: 4.8/5" },
    { name: "Seasonal Task AI", emoji: "🍂", desc: "Genera calendario manutenzioni in base a stagione e tipo di piante", capabilities: ["Task scheduling", "Plant care", "Weather alerts"], isUniversal: false, accuracy: 90, hoursPerWeek: 5,
      workflow: [{ icon: "📅", label: "Calendario", detail: "Genera programma annuale per giardino" }, { icon: "🌡️", label: "Meteo", detail: "Adatta interventi alle previsioni" }, { icon: "📱", label: "Reminder", detail: "Notifica cliente per intervento programmato" }, { icon: "📊", label: "Report", detail: "Report salute giardino stagionale" }],
      example: "Novembre → Potatura rose, protezione agrumi, concimazione prato → Calendario inviato a 45 clienti → 38 confermano",
      result: "Interventi stagionali: +85% · Revenue ricorrente: +€4.500/mese" },
  ],
  veterinary: [
    { name: "Vet Triage AI", emoji: "🐾", desc: "Pre-valutazione sintomi animali e prioritizzazione emergenze", capabilities: ["Symptom check", "Emergency priority", "Species-specific"], isUniversal: false, accuracy: 93, hoursPerWeek: 10,
      workflow: [{ icon: "📱", label: "Segnalazione", detail: "Proprietario descrive sintomi via chat" }, { icon: "🧠", label: "Analisi", detail: "AI valuta sintomi per specie e razza" }, { icon: "🚨", label: "Priorità", detail: "Classifica: routine, urgente, emergenza" }, { icon: "📅", label: "Azione", detail: "Prenota visita con priorità appropriata" }],
      example: "Labrador vomita da 6h → Sintomi compatibili con ostruzione → URGENTE → Slot in 1h → Diagnosi confermata",
      result: "Emergenze gestite: +95% · Tempo risposta: -70%" },
    { name: "Pet Health Reminder AI", emoji: "💉", desc: "Promemoria vaccini, sverminazioni e check-up per ogni paziente", capabilities: ["Vaccine calendar", "Health alerts", "Owner notifications"], isUniversal: false, accuracy: 97, hoursPerWeek: 4,
      workflow: [{ icon: "📋", label: "Scheda", detail: "Consulta storico vaccinazioni animale" }, { icon: "📅", label: "Scadenze", detail: "Calcola prossimi richiami e check-up" }, { icon: "📱", label: "SMS", detail: "Invia reminder al proprietario" }, { icon: "📋", label: "Prenotazione", detail: "Link diretto per prenotare" }],
      example: "Gatto Luna: richiamo trivalente tra 2 settimane → SMS alla sig.ra Bianchi → Prenota online → Slot riempito",
      result: "Richiami puntuali: +80% · Revenue vaccini: +€1.200/mese" },
    { name: "Pet Nutrition AI", emoji: "🍖", desc: "Piani alimentari personalizzati per ogni animale con allergie e patologie", capabilities: ["Diet planning", "Allergy management", "Supplement suggestions"], isUniversal: false, accuracy: 89, hoursPerWeek: 6,
      workflow: [{ icon: "📋", label: "Profilo", detail: "Specie, razza, età, peso, patologie" }, { icon: "🍽️", label: "Piano", detail: "Genera dieta personalizzata" }, { icon: "📦", label: "Prodotti", detail: "Suggerisce prodotti specifici disponibili" }, { icon: "📊", label: "Monitoring", detail: "Traccia peso e condizioni" }],
      example: "Bulldog francese 3 anni, dermatite → Dieta ipoallergenica grain-free → Miglioramento in 4 settimane",
      result: "Compliance dieta: +60% · Vendite prodotti nutrition: +€800/mese" },
  ],
  tattoo: [
    { name: "Tattoo Booking AI", emoji: "🎨", desc: "Gestisce prenotazioni con stima durata, deposito e sessioni multiple", capabilities: ["Duration estimation", "Deposit management", "Multi-session"], isUniversal: false, accuracy: 89, hoursPerWeek: 8,
      workflow: [{ icon: "📱", label: "Richiesta", detail: "Cliente invia idea e zona corpo" }, { icon: "⏱️", label: "Stima", detail: "AI stima durata e numero sessioni" }, { icon: "💰", label: "Deposito", detail: "Richiede deposito e conferma prenotazione" }, { icon: "📅", label: "Scheduling", detail: "Pianifica sessioni con intervalli guarigione" }],
      example: "Sleeve completo → AI: 4 sessioni da 5h, intervallo 3 settimane → Deposito €200 → 4 date pianificate",
      result: "No-show: -70% · Pianificazione: automatica" },
    { name: "Aftercare AI", emoji: "💊", desc: "Istruzioni personalizzate post-tattoo inviate in automatico", capabilities: ["Custom aftercare", "Follow-up reminders", "Healing tracking"], isUniversal: false, accuracy: 94, hoursPerWeek: 3,
      workflow: [{ icon: "✅", label: "Sessione completata", detail: "Artista segna fine sessione" }, { icon: "📱", label: "Istruzioni", detail: "WhatsApp automatico con cura personalizzata" }, { icon: "📅", label: "Follow-up", detail: "Check guarigione a 3gg, 7gg, 14gg" }, { icon: "📸", label: "Foto", detail: "Cliente invia foto per valutazione" }],
      example: "Tatuaggio colore su braccio → Istruzioni specifiche per colore → Check a 7gg: 'Guarigione perfetta, evita sole 2 sett'",
      result: "Complicazioni: -80% · Soddisfazione: 4.9/5" },
    { name: "Flash Day AI", emoji: "⚡", desc: "Organizza flash day con catalogo digitale e prenotazioni istantanee", capabilities: ["Flash catalog", "Instant booking", "Social promotion"], isUniversal: false, accuracy: 88, hoursPerWeek: 5,
      workflow: [{ icon: "🎨", label: "Catalogo", detail: "Artisti caricano disegni flash" }, { icon: "📱", label: "Pubblicazione", detail: "Gallery online con prezzi fissi" }, { icon: "📅", label: "Booking", detail: "Clienti prenotano il flash preferito" }, { icon: "📣", label: "Promo", detail: "Countdown e promo social automatiche" }],
      example: "Flash Day sabato: 20 disegni → Gallery online → 18 prenotati in 24h → Revenue giornata €2.800",
      result: "Slot riempiti: 95% · Revenue flash day: +€2.500" },
  ],
  childcare: [
    { name: "Child Activity Planner AI", emoji: "🎨", desc: "Pianifica attività educative adatte all'età e interessi dei bambini", capabilities: ["Age-appropriate activities", "Learning goals", "Material prep"], isUniversal: false, accuracy: 88, hoursPerWeek: 8,
      workflow: [{ icon: "👶", label: "Gruppo", detail: "Analizza età e interessi del gruppo" }, { icon: "🎯", label: "Obiettivi", detail: "Definisce obiettivi pedagogici settimanali" }, { icon: "🎨", label: "Attività", detail: "Genera programma con materiali necessari" }, { icon: "📋", label: "Report", detail: "Documenta risultati e progressi" }],
      example: "Gruppo 3-4 anni, tema: stagioni → 5 attività creative: collage foglie, pittura albero, gioco dei colori → Materiali pronti",
      result: "Tempo pianificazione: -70% · Qualità educativa: +40%" },
    { name: "Parent Communication AI", emoji: "👪", desc: "Genera aggiornamenti quotidiani con foto e attività per i genitori", capabilities: ["Daily reports", "Photo sharing", "Milestone tracking"], isUniversal: false, accuracy: 92, hoursPerWeek: 6,
      workflow: [{ icon: "📸", label: "Foto", detail: "Educatrici scattano foto durante la giornata" }, { icon: "📝", label: "Report", detail: "AI genera aggiornamento con pasti, sonnellino, attività" }, { icon: "📱", label: "Invio", detail: "Ogni genitore riceve report personalizzato" }, { icon: "❤️", label: "Feedback", detail: "Genitori possono commentare e comunicare" }],
      example: "15:30: Report giornaliero → 'Marco ha mangiato tutto, dormito 1.5h, dipinto un sole bellissimo 🌞' → Foto allegata",
      result: "Soddisfazione genitori: 4.9/5 · Comunicazione: -80% tempo" },
  ],
  education: [
    { name: "Course Designer AI", emoji: "📚", desc: "Progetta programmi didattici e materiali in base agli obiettivi", capabilities: ["Curriculum design", "Material generation", "Assessment creation"], isUniversal: false, accuracy: 87, hoursPerWeek: 12,
      workflow: [{ icon: "🎯", label: "Obiettivi", detail: "Definisce competenze target del corso" }, { icon: "📖", label: "Programma", detail: "Genera syllabus con moduli e lezioni" }, { icon: "📄", label: "Materiali", detail: "Crea slide, esercizi e quiz" }, { icon: "📊", label: "Assessment", detail: "Genera test di verifica per ogni modulo" }],
      example: "Corso Marketing Digitale 40h → 8 moduli → 32 lezioni → 8 quiz → Certificato finale → Pronto in 2 giorni vs 2 settimane",
      result: "Tempo creazione corsi: -80% · Qualità contenuti: +35%" },
    { name: "Student Engagement AI", emoji: "🎓", desc: "Monitora engagement studenti e suggerisce interventi per il dropout", capabilities: ["Engagement tracking", "Dropout prediction", "Personalized nudges"], isUniversal: false, accuracy: 90, hoursPerWeek: 6,
      workflow: [{ icon: "📊", label: "Monitoring", detail: "Traccia accessi, completamenti, voti" }, { icon: "⚠️", label: "Alert", detail: "Identifica studenti a rischio dropout" }, { icon: "📱", label: "Nudge", detail: "Invia messaggio motivazionale personalizzato" }, { icon: "👤", label: "Tutoring", detail: "Suggerisce sessione di supporto" }],
      example: "Luca: 0 accessi da 10gg, quiz non completati → Email motivazionale + offerta tutoring gratuito → Luca riprende",
      result: "Dropout: -55% · Completamento corsi: +40%" },
    { name: "Certificate AI", emoji: "🏆", desc: "Genera attestati automatici con verifica credenziali e blockchain", capabilities: ["Auto-certification", "Skills validation", "Digital badge"], isUniversal: false, accuracy: 95, hoursPerWeek: 3,
      workflow: [{ icon: "✅", label: "Completamento", detail: "Studente supera esame finale" }, { icon: "📄", label: "Certificato", detail: "Genera attestato personalizzato con QR" }, { icon: "🔗", label: "Verifica", detail: "Link pubblico per verifica autenticità" }, { icon: "📧", label: "Invio", detail: "Email con PDF e badge digitale LinkedIn" }],
      example: "Maria supera esame Web Design → Certificato PDF con QR verifica → Badge LinkedIn → Condiviso 45 volte",
      result: "Tempo emissione: istantaneo · Credibilità: +premium" },
  ],
  events: [
    { name: "Event Planner AI", emoji: "🎉", desc: "Pianifica eventi con timeline, task e coordinamento fornitori", capabilities: ["Timeline automation", "Task assignment", "Vendor coordination"], isUniversal: false, accuracy: 91, hoursPerWeek: 15,
      workflow: [{ icon: "📋", label: "Brief", detail: "Tipo evento, budget, n. ospiti, data" }, { icon: "📊", label: "Timeline", detail: "Genera cronoprogramma con milestone" }, { icon: "👥", label: "Fornitori", detail: "Suggerisce e coordina fornitori" }, { icon: "📱", label: "Tracking", detail: "Dashboard avanzamento in tempo reale" }],
      example: "Matrimonio 120 ospiti, budget €25k → Timeline 6 mesi → 18 task → 8 fornitori coordinati → Tutto perfetto",
      result: "Tempo organizzazione: -50% · Budget rispettato: 98%" },
    { name: "Budget Optimizer AI", emoji: "💳", desc: "Ottimizza budget evento trovando le migliori offerte per ogni voce", capabilities: ["Cost optimization", "Vendor negotiation", "Budget tracking"], isUniversal: false, accuracy: 89, hoursPerWeek: 6,
      workflow: [{ icon: "💰", label: "Budget", detail: "Definisce budget per categoria" }, { icon: "🔍", label: "Ricerca", detail: "Trova fornitori con miglior rapporto q/p" }, { icon: "📊", label: "Confronto", detail: "Compara preventivi e negozia" }, { icon: "📈", label: "Tracking", detail: "Monitora speso vs budget in tempo reale" }],
      example: "Catering 120 ospiti → 5 preventivi → Miglior offerta €42/persona (vs media €55) → Risparmio €1.560",
      result: "Risparmio medio: -22% · ROI ottimizzazione: 8x" },
    { name: "Guest Experience AI", emoji: "🌟", desc: "Personalizza esperienza ospiti con preferenze menu, seating e comunicazioni", capabilities: ["Guest profiling", "Seating optimization", "Menu preferences"], isUniversal: false, accuracy: 88, hoursPerWeek: 8,
      workflow: [{ icon: "📧", label: "RSVP", detail: "Inviti digitali con conferma online" }, { icon: "🍽️", label: "Preferenze", detail: "Raccoglie allergie, menu e preferenze" }, { icon: "🪑", label: "Seating", detail: "Ottimizza tavoli per affinità e dinamiche" }, { icon: "📱", label: "Day-of", detail: "App per ospiti con programma e info" }],
      example: "120 ospiti → RSVP digitale → 8 allergie gestite → Tavoli ottimizzati → App con timeline → Zero problemi",
      result: "Soddisfazione ospiti: 4.9/5 · Problemi: -90%" },
  ],
  logistics: [
    { name: "Route Planner AI", emoji: "🗺️", desc: "Ottimizza rotte di consegna per minimizzare km e tempi", capabilities: ["Multi-stop optimization", "Traffic prediction", "Delivery windows"], isUniversal: false, accuracy: 94, hoursPerWeek: 12,
      workflow: [{ icon: "📦", label: "Ordini", detail: "Raccoglie consegne del giorno" }, { icon: "🗺️", label: "Ottimizzazione", detail: "Calcola percorso ottimale multi-stop" }, { icon: "📱", label: "Dispatch", detail: "Invia rotta a ogni autista" }, { icon: "📊", label: "Tracking", detail: "Monitora avanzamento in tempo reale" }],
      example: "28 consegne → Rotta ottimizzata: 94km (vs 142km manuale) → Risparmio 48km, 1.5h, €28 carburante",
      result: "Km percorsi: -35% · Consegne/giorno: +25%" },
    { name: "Fleet Maintenance AI", emoji: "🔧", desc: "Manutenzione predittiva veicoli commerciali con alert proattivi", capabilities: ["Predictive maintenance", "Fuel optimization", "Cost tracking"], isUniversal: false, accuracy: 95, hoursPerWeek: 6,
      workflow: [{ icon: "🚛", label: "Telemetria", detail: "Monitora km, consumo, stato veicolo" }, { icon: "🔮", label: "Previsione", detail: "Prevede prossima manutenzione necessaria" }, { icon: "📅", label: "Scheduling", detail: "Prenota officina in slot a bassa attività" }, { icon: "💰", label: "Costi", detail: "Report costo per km e veicolo" }],
      example: "Fiat Ducato #3: 92.000km → Tagliando tra 3.000km → Prenotato per sabato → Nessun fermo veicolo",
      result: "Fermi imprevisti: -80% · Costo manutenzione: -25%" },
    { name: "Delivery Optimizer AI", emoji: "📦", desc: "Massimizza efficienza consegne con batching e slot intelligenti", capabilities: ["Batch optimization", "Slot management", "Priority routing"], isUniversal: false, accuracy: 92, hoursPerWeek: 8,
      workflow: [{ icon: "📋", label: "Ordini", detail: "Analizza ordini per zona e urgenza" }, { icon: "📦", label: "Batching", detail: "Raggruppa per zona geografica" }, { icon: "⏰", label: "Slot", detail: "Assegna fasce orarie ottimali" }, { icon: "🚛", label: "Dispatch", detail: "Assegna batch a veicolo appropriato" }],
      example: "45 ordini → 6 batch per zona → 3 veicoli → Tutte consegnate entro 16:00 (vs 19:00 senza batching)",
      result: "Efficienza: +40% · Costo per consegna: -30%" },
    { name: "Warehouse AI", emoji: "🏭", desc: "Ottimizza stoccaggio e picking per velocizzare le spedizioni", capabilities: ["Layout optimization", "Pick path", "Stock rotation"], isUniversal: false, accuracy: 91, hoursPerWeek: 10,
      workflow: [{ icon: "📊", label: "Analisi", detail: "Studia frequenza prelievo per articolo" }, { icon: "🗺️", label: "Layout", detail: "Posiziona prodotti ad alta rotazione vicino" }, { icon: "📱", label: "Pick list", detail: "Genera percorso picking ottimale" }, { icon: "📦", label: "Spedizione", detail: "Prepara colli con documentazione" }],
      example: "100 ordini/giorno → Picking ottimizzato: 3.2min/ordine (vs 5.8min) → +45% produttività",
      result: "Tempo picking: -45% · Errori: -80%" },
  ],
  custom: [
    { name: "Universal AI Configurator", emoji: "🔧", desc: "Configura il comportamento degli agenti AI per qualsiasi caso d'uso", capabilities: ["Custom workflows", "Rule engine", "Integration builder"], isUniversal: false, accuracy: 90, hoursPerWeek: 10,
      workflow: [{ icon: "📋", label: "Analisi", detail: "Studia il tuo processo attuale" }, { icon: "🔧", label: "Configurazione", detail: "Personalizza regole e trigger" }, { icon: "🔗", label: "Integrazione", detail: "Connette con i tuoi strumenti" }, { icon: "🚀", label: "Deploy", detail: "Attiva e monitora performance" }],
      example: "Processo approvazione ordini → Trigger: ordine >€500 → Notifica manager → Approvazione in-app → Automazione completa",
      result: "Automazione processi: +80% · Errori manuali: -90%" },
    { name: "Custom Integration AI", emoji: "🔗", desc: "Connette i tuoi sistemi esistenti e automatizza i flussi di dati", capabilities: ["API connector", "Data sync", "Webhook management"], isUniversal: false, accuracy: 93, hoursPerWeek: 8,
      workflow: [{ icon: "🔍", label: "Discovery", detail: "Analizza sistemi e API disponibili" }, { icon: "🔗", label: "Connessione", detail: "Crea bridge tra i sistemi" }, { icon: "🔄", label: "Sync", detail: "Sincronizza dati in tempo reale" }, { icon: "📊", label: "Monitoring", detail: "Dashboard stato integrazioni" }],
      example: "CRM esterno + gestionale + email → Tutto sincronizzato → Dato inserito una volta sola → Zero duplicati",
      result: "Data entry: -70% · Errori sync: -95%" },
  ],
};

/**
 * Get all features for a sector (universal + sector-specific)
 */
export function getAllFeaturesForSector(sector: string): FeatureItem[] {
  return [...UNIVERSAL_FEATURES, ...(SECTOR_SPECIFIC_FEATURES[sector] || [])];
}

/**
 * Get all AI agents for a sector (universal + sector-specific)
 */
export function getAllAgentsForSector(sector: string): AIAgent[] {
  return [...UNIVERSAL_AGENTS, ...(SECTOR_SPECIFIC_AGENTS[sector] || [])];
}
