// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
var whoami_default = defineTool({
  name: "whoami",
  title: "Chi sono",
  description: "Restituisce l'utente autenticato (id, email) collegato al client MCP.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non autenticato" }], isError: true };
    }
    const payload = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      client_id: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-companies.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_companies_default = defineTool2({
  name: "list_companies",
  title: "Elenca le mie aziende",
  description: "Restituisce le aziende (companies) visibili all'utente autenticato, filtrate da RLS.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("Numero massimo di aziende da restituire.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non autenticato" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("companies").select("id, name, industry, slug, created_at").limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { companies: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-restaurants.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_restaurants_default = defineTool3({
  name: "list_restaurants",
  title: "Elenca i miei ristoranti",
  description: "Restituisce i ristoranti visibili all'utente autenticato, filtrati da RLS.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).default(20).describe("Numero massimo di ristoranti da restituire.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non autenticato" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("restaurants").select("id, name, slug, created_at").limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { restaurants: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-leads.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_leads_default = defineTool4({
  name: "list_leads",
  title: "Elenca i miei lead",
  description: "Restituisce i lead visibili all'utente autenticato (partner), filtrati da RLS.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).default(25).describe("Numero massimo di lead.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non autenticato" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("leads").select("id, business_name, sector, city, status, phone, website, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gypnxirzmhpapmhjguaj";
var mcp_default = defineMcp({
  name: "empireia-mcp",
  title: "Empire IA \xB7 Agent Integrations",
  version: "0.1.0",
  instructions: "Strumenti Empire IA per il tuo account autenticato: leggi le tue aziende, ristoranti e lead. Ogni chiamata rispetta RLS e si autentica come l'utente collegato.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_companies_default, list_restaurants_default, list_leads_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
