
-- Table for push notification subscriptions
CREATE TABLE public.push_subscriptions (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  restaurant_id UUID NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
  customer_phone TEXT,
  endpoint TEXT NOT NULL,
  p256dh TEXT NOT NULL,
  auth_key TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  is_active BOOLEAN NOT NULL DEFAULT true,
  UNIQUE(restaurant_id, endpoint)
);

ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;

-- Anyone can subscribe (public PWA)
CREATE POLICY "Anyone can create push subscription"
  ON public.push_subscriptions FOR INSERT
  WITH CHECK (true);

-- Restaurant owners can read their subs
CREATE POLICY "Owners read push subscriptions"
  ON public.push_subscriptions FOR SELECT
  USING (is_restaurant_owner(restaurant_id) OR is_super_admin());

-- Users can delete own subscription
CREATE POLICY "Anyone can delete own subscription"
  ON public.push_subscriptions FOR DELETE
  USING (true);

-- Table for wallet passes issued
CREATE TABLE public.wallet_passes (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  restaurant_id UUID NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
  customer_phone TEXT NOT NULL,
  pass_type TEXT NOT NULL DEFAULT 'discount',
  discount_percent INTEGER NOT NULL DEFAULT 10,
  serial_number TEXT NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,
  redeemed BOOLEAN NOT NULL DEFAULT false,
  redeemed_at TIMESTAMP WITH TIME ZONE,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now() + interval '7 days'),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.wallet_passes ENABLE ROW LEVEL SECURITY;

-- Restaurant owners manage wallet passes
CREATE POLICY "Owners manage wallet passes"
  ON public.wallet_passes FOR ALL
  USING (is_restaurant_owner(restaurant_id) OR is_super_admin());

-- Public can read their own passes by serial
CREATE POLICY "Public read own wallet passes"
  ON public.wallet_passes FOR SELECT
  USING (true);

-- Public can insert (generated by edge function)
CREATE POLICY "System creates wallet passes"
  ON public.wallet_passes FOR INSERT
  WITH CHECK (true);
