
-- Table for kitchen access PINs generated by restaurant owners
CREATE TABLE public.kitchen_access_pins (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
  pin_code text NOT NULL,
  label text DEFAULT 'Cucina',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz,
  UNIQUE(restaurant_id, pin_code)
);

ALTER TABLE public.kitchen_access_pins ENABLE ROW LEVEL SECURITY;

-- Only restaurant owners and super admins can manage PINs
CREATE POLICY "Owners manage kitchen pins"
  ON public.kitchen_access_pins FOR ALL
  USING (is_restaurant_owner(restaurant_id) OR is_super_admin());

-- Public can read active pins (needed for PIN login verification)
CREATE POLICY "Anyone can verify active pins"
  ON public.kitchen_access_pins FOR SELECT
  USING (is_active = true);
