/**
 * Catalog Companions Registry — 3 premium AI companion iPhone screens per hero.
 *
 * Each hero PNG in `catalog-mockup-registry.ts` has a matching triple of
 * companion screens (menu, detail, booking) generated by Gemini using the
 * hero as visual reference. This guarantees identical palette / typography /
 * lighting across the 4-phone lineup shown on `/portfolio`.
 */

import type { IndustryId } from "@/config/industry-config";

// Eagerly import every companion PNG. Vite gives us a stable module URL.
const companionFiles = import.meta.glob(
  "@/assets/mockups/catalog/companions/*.png",
  { eager: true, import: "default" },
) as Record<string, string>;

// Group companions by their hero stem (portion before "--<index>-<slug>.png")
const byStem = new Map<string, string[]>();
for (const [path, url] of Object.entries(companionFiles)) {
  const filename = path.split("/").pop() ?? "";
  const m = filename.match(/^(.+?)--(\d+)-.+\.png$/);
  if (!m) continue;
  const stem = m[1];
  const idx = parseInt(m[2], 10);
  const bucket = byStem.get(stem) ?? [];
  bucket[idx - 2] = url; // indices are 2,3,4 → array slot 0,1,2
  byStem.set(stem, bucket);
}

/**
 * Map every (sector::brand-slug::style-slug) → hero PNG stem so we can look
 * up the matching companions without having to touch each registry line.
 *
 * The hero stem is the filename (without extension) of the source PNG in
 * `src/assets/mockups/catalog/`. Multiple keys can share the same hero when
 * the main registry reuses the same PNG.
 */
const HERO_STEM_BY_KEY: Record<string, string> = {
  // FOOD — Onyx Brace Steakhouse
  "food::onyx-brace-steakhouse::obsidian":       "food-onyx-obsidian",
  "food::onyx-brace-steakhouse::ivory":          "food-onyx-ivory",
  "food::onyx-brace-steakhouse::hanok":          "food-sakura-sakura",
  "food::onyx-brace-steakhouse::gangnam":        "food-indocina-neon-spice",
  "food::onyx-brace-steakhouse::joseon":         "food-sakura-luxury-dark",
  // FOOD — Sakura Atelier
  "food::sakura-atelier::sakura":                "food-sakura-sakura",
  "food::sakura-atelier::luxury-dark":           "food-sakura-luxury-dark",
  "food::sakura-atelier::white-clean":           "food-onyx-ivory",
  "food::sakura-atelier::miami-ocean":           "food-pacifico-costa",
  "food::sakura-atelier::pearl-gold":            "food-levante-deli",
  "food::sakura-atelier::marble-zen":            "food-sakura-sakura",
  "food::sakura-atelier::champagne-rose":        "beauty-aurora-lavender",
  "food::sakura-atelier::arctic-crystal":        "healthcare-lumen-glass",
  "food::sakura-atelier::tsukiji-ice":           "food-sakura-luxury-dark",
  "food::sakura-atelier::sakura-garden":         "veterinary-tropico-resort",
  "food::sakura-atelier::wabi-sabi-marble":      "food-sakura-sakura",
  "food::sakura-atelier::hinoki-frost":          "hospitality-cala-vento-azure",
  // FOOD — Indocina Noir
  "food::indocina-noir::noir-saigon":            "food-sakura-luxury-dark",
  "food::indocina-noir::jade-dynasty":           "food-levante-deli",
  "food::indocina-noir::crimson-silk":           "food-brace-kebab",
  "food::indocina-noir::golden-hour":            "hospitality-cala-vento-sunset",
  "food::indocina-noir::neon-spice":             "food-indocina-neon-spice",
  "food::indocina-noir::matcha-blaze":           "fitness-onda-aqua",
  "food::indocina-noir::obsidian-gold":          "food-onyx-obsidian",
  // FOOD — Pacifico Ceviche
  "food::pacifico-ceviche::costa-pacifico":      "food-pacifico-costa",
  "food::pacifico-ceviche::casa-nostra":         "food-onyx-ivory",
  "food::pacifico-ceviche::bianco-memoria":      "food-sakura-sakura",
  "food::pacifico-ceviche::ocra-lima":           "food-levante-deli",
  // FOOD — Levante Deli
  "food::levante-deli::style-a":                 "food-levante-deli",
  "food::levante-deli::style-b":                 "food-pacifico-costa",
  "food::levante-deli::style-c":                 "food-sakura-sakura",
  "food::levante-deli::style-d":                 "food-onyx-ivory",
  "food::levante-deli::style-e":                 "hospitality-cala-vento-sunset",
  "food::levante-deli::style-f":                 "beauty-aurora-lavender",
  "food::levante-deli::style-h":                 "food-indocina-neon-spice",
  // FOOD — Brace Kebab
  "food::brace-kebab::default":                  "food-brace-kebab",
  // BEAUTY
  "beauty::aurora-nail-atelier::lavender-luxe":  "beauty-aurora-lavender",
  "beauty::aurora-nail-atelier::blush-rosegold": "beauty-aurora-blush-rosegold",
  "beauty::velluto-hair-lab::mobile":            "beauty-velluto-editorial",
  "beauty::velluto-hair-lab::desktop":           "beauty-aurora-lavender",
  // NCC
  "ncc::marina-riviera::style-a":                "ncc-marina-riviera",
  "ncc::marina-riviera::style-c":                "ncc-marina-amalfi-style-b",
  "ncc::marina-riviera::style-f":                "hospitality-cala-vento-sunset",
  "ncc::marina-riviera::style-g":                "hospitality-cala-vento-azure",
  "ncc::marina-riviera::style-h":                "ncc-marina-riviera",
  "ncc::cala-vento-charter::emerald-cove":       "hospitality-cala-vento-azure",
  "ncc::cala-vento-charter::golden-sunset":      "hospitality-cala-vento-sunset",
  "ncc::cala-vento-charter::sardinia-azure-desktop":  "hospitality-cala-vento-azure",
  "ncc::cala-vento-charter::emerald-cove-desktop":    "hospitality-cala-vento-sunset",
  // HOSPITALITY
  "hospitality::cala-vento-charter::sardinia-azure":  "hospitality-cala-vento-azure",
  "hospitality::cala-vento-charter::sunset-suite":    "hospitality-cala-vento-sunset",
  // VETERINARY
  "veterinary::tropico-pet-resort::style-a":     "veterinary-tropico-resort",
  "veterinary::tropico-pet-resort::style-e":     "childcare-stelle-playful",
  "veterinary::tropico-pet-resort::style-f":     "veterinary-tropico-resort",
  // CHILDCARE
  "childcare::stelle-nursery::playful-colorful": "childcare-stelle-playful",
  "childcare::stelle-nursery::nature-explorer":  "veterinary-tropico-resort",
  "childcare::stelle-nursery::ocean-breeze":     "hospitality-cala-vento-azure",
  "childcare::stelle-nursery::sunny-garden":     "childcare-arcobaleno-bauhaus",
  "childcare::stelle-nursery::sunset-playful":   "hospitality-cala-vento-sunset",
  "childcare::arcobaleno-playhouse::style-a":    "childcare-arcobaleno-bauhaus",
  // FITNESS
  "fitness::centro-padel-brera::sage-luxe":      "fitness-padel-sage",
  "fitness::centro-padel-brera::fresh-azzurro":  "fitness-onda-aqua",
  "fitness::onda-sport-club::wave-pro":          "fitness-onda-aqua",
  // HEALTHCARE
  "healthcare::lumen-clinic::ethereal-glass":    "healthcare-lumen-glass",
  "healthcare::lumen-clinic::azure-gradient":    "hospitality-cala-vento-azure",
  "healthcare::lumen-clinic::ice-crystal":       "healthcare-lumen-glass",
  "healthcare::lumen-clinic::soft-blue":         "ncc-marina-riviera",
  // CONSTRUCTION
  "construction::domus-living::ocean-azure":     "construction-domus-ocean-azure",
  "construction::domus-living::living-coral":    "construction-domus-living-coral",
  "construction::domus-living::ice-blue":        "construction-domus-ice-blue",
  "construction::domus-living::rose-gold":       "construction-domus-rose-gold",
  // PLUMBER
  "plumber::idro-pronto::style-a":               "plumber-idro-pronto-style-a",
  "plumber::idro-pronto::style-b":               "plumber-idro-pronto-style-b",
};

function slug(v: string): string {
  return v.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

/**
 * Returns the 3 companion screen URLs (menu, detail, booking) for a given
 * (sector, brand, style) triple, or null when no premium companions exist.
 */
export function catalogCompanionUrls(
  sector: IndustryId,
  brand: string,
  style: string,
): string[] | null {
  const key = `${sector}::${slug(brand)}::${slug(style)}`;
  const stem = HERO_STEM_BY_KEY[key];
  if (!stem) return null;
  const urls = byStem.get(stem);
  if (!urls || urls.length < 3 || urls.some((u) => !u)) return null;
  return urls.slice(0, 3);
}
