/**
 * Catalog Companions Registry — 3 premium AI companion iPhone screens per hero.
 *
 * Each hero PNG in `catalog-mockup-registry.ts` has a matching triple of
 * companion screens (menu, detail, booking) generated by Gemini using the
 * hero as visual reference. This guarantees identical palette / typography /
 * lighting across the 4-phone lineup shown on `/portfolio`.
 *
 * Lookup is by the imported hero URL (they end with a unique hashed filename
 * after Vite processing) → array of 3 companion URLs in order.
 */

// helper: dynamic Vite import glob → { hero-stem : [companion urls ordered by index] }
const companionFiles = import.meta.glob(
  "@/assets/mockups/catalog/companions/*.png",
  { eager: true, import: "default" },
) as Record<string, string>;

// Group companions by their hero stem (portion before "--")
const byStem = new Map<string, { index: number; url: string }[]>();
for (const [path, url] of Object.entries(companionFiles)) {
  const filename = path.split("/").pop() ?? "";
  const m = filename.match(/^(.+?)--(\d+)-.+\.png$/);
  if (!m) continue;
  const stem = m[1];
  const idx = parseInt(m[2], 10);
  const bucket = byStem.get(stem) ?? [];
  bucket.push({ index: idx, url });
  byStem.set(stem, bucket);
}
for (const bucket of byStem.values()) bucket.sort((a, b) => a.index - b.index);

/**
 * Map a hero PNG import URL to its 3 companion URLs (menu, detail, booking).
 * Returns null when no companions exist for that hero.
 */
export function companionsForHero(heroUrl: string): string[] | null {
  // Vite hashes the filename but keeps the stem prefix, so extract it.
  const filename = heroUrl.split("/").pop() ?? "";
  // e.g. "food-onyx-obsidian-abc123.png" or "food-onyx-obsidian.png"
  const stem = filename.replace(/\.png(\?.*)?$/, "").replace(/-[A-Za-z0-9_]{6,}$/, "");
  // Try progressively shorter suffix trims because Vite hash length varies.
  const tries = new Set<string>([stem]);
  const parts = filename.replace(/\.png(\?.*)?$/, "").split("-");
  for (let i = parts.length - 1; i >= 2; i--) {
    tries.add(parts.slice(0, i).join("-"));
  }
  for (const candidate of tries) {
    const bucket = byStem.get(candidate);
    if (bucket && bucket.length >= 3) return bucket.slice(0, 3).map((b) => b.url);
  }
  return null;
}
